/**
 * generated by Xtext 2.23.0.M1
 */
package hu.bme.mit.gamma.fmeda.language.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FMEDALanguageGenerator extends AbstractGenerator {
  private final String ename = "fault";
  
  private final String modeltype = "sync";
  
  private final String sctname = "FailureModeSCT";
  
  private final String sctportname = "FaultPort";
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    throw new Error("Unresolved compilation problems:"
      + "\nhu.bme.mit.gamma.fmeda.model.Package cannot be resolved to a type."
      + "\nname cannot be resolved"
      + "\n+ cannot be resolved");
  }
}
