/*
 * generated by Xtext 2.23.0.M1
 */
package hu.bme.mit.gamma.fmeda.language.serializer;

import com.google.inject.Inject;
import hu.bme.mit.gamma.fmeda.language.services.FMEDALanguageGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class FMEDALanguageSyntacticSequencer extends AbstractSyntacticSequencer {

	protected FMEDALanguageGrammarAccess grammarAccess;
	protected AbstractElementAlias match_FMEDAComponentDef___LeftSquareBracketKeyword_3_0_RightSquareBracketKeyword_3_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (FMEDALanguageGrammarAccess) access;
		match_FMEDAComponentDef___LeftSquareBracketKeyword_3_0_RightSquareBracketKeyword_3_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFMEDAComponentDefAccess().getLeftSquareBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getFMEDAComponentDefAccess().getRightSquareBracketKeyword_3_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_FMEDAComponentDef___LeftSquareBracketKeyword_3_0_RightSquareBracketKeyword_3_2__q.equals(syntax))
				emit_FMEDAComponentDef___LeftSquareBracketKeyword_3_0_RightSquareBracketKeyword_3_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('[' ']')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) '{' '}' (rule end)
	 *     name=ID (ambiguity) '{' channels+=Channel
	 *     name=ID (ambiguity) '{' failuremodes+=FailureModeDef
	 *     name=ID (ambiguity) '{' failuremodes+=PartFailureModeDef
	 *     name=ID (ambiguity) '{' failurepropagations+=FailurePropagationDef
	 *     name=ID (ambiguity) '{' subcomponents+=FMEDAComponentInstance
	 */
	protected void emit_FMEDAComponentDef___LeftSquareBracketKeyword_3_0_RightSquareBracketKeyword_3_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
