
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	stochmodel -> detmodel : Orion.SoftwareTimer  ::  Timing.Schedule at 1000.0068969726562
stochmodel -> detmodel : Orion.SoftwareTimer  ::  Timing.Schedule at 1999.8600463867188
stochmodel -> detmodel : Orion.SoftwareTimer  ::  Timing.Schedule at 2999.8496704101562
stochmodel -> detmodel : Orion.SoftwareTimer  ::  Timing.Schedule at 3999.7156372070312
stochmodel -> detmodel : Orion.SoftwareTimer  ::  Timing.Schedule at 4999.7156982421875
detmodel -> detmodel : "Gamma timeout, 3 ms at 4999.7156982421875"
stochmodel -> detmodel : Orion.SoftwareTimer  ::  Timing.Schedule at 5999.649475097656
detmodel -> analysis : "SystemConnStatus.conn at time 5999.649475097656"
hnote over analysis 
EndConditionOrion_SystemConnStatus_Conn is reached
endnote
@enduml