<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stochastic" nsURI="hu.bme.mit.gamma.environment.stochastic.model"
    nsPrefix="stochastic">
  <eClassifiers xsi:type="ecore:EClass" name="StochasticModel" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomVariable" abstract="true" eSuperTypes="#//StochasticModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinouosRandomVariable" abstract="true"
      eSuperTypes="#//RandomVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="StochasticProcess" abstract="true" eSuperTypes="#//StochasticModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="PoissonProcess" abstract="true" eSuperTypes="#//StochasticProcess"/>
  <eClassifiers xsi:type="ecore:EClass" name="NormalRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mean" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExponentialRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteRandomVariable" abstract="true"
      eSuperTypes="#//RandomVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="BernoulliRandomVariable" eSuperTypes="#//DiscreteRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GaussianProcess" eSuperTypes="#//StochasticProcess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kernel" lowerBound="1"
        eType="#//Kernel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kernel" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinearKernel" eSuperTypes="#//Kernel"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrownianKernel" eSuperTypes="#//Kernel"/>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicKernel" eSuperTypes="#//Kernel"/>
  <eClassifiers xsi:type="ecore:EClass" name="RBFKernel" eSuperTypes="#//Kernel"/>
  <eClassifiers xsi:type="ecore:EClass" name="SumKernel" eSuperTypes="#//Kernel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kernels" lowerBound="2"
        upperBound="2" eType="#//Kernel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FittedGaussianProcess" eSuperTypes="#//GaussianProcess #//FittedModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfluxDB" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;localhost&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiracProcess" eSuperTypes="#//StochasticProcess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//DataSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PythonSimulation" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoricalProbabaility" eSuperTypes="#//StochasticModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HomogeneousPoissonProcess" eSuperTypes="#//PoissonProcess"/>
  <eClassifiers xsi:type="ecore:EClass" name="InhomogeneousPoissonProcess" eSuperTypes="#//PoissonProcess"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeibullRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkovProcess" eSuperTypes="#//StochasticProcess"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticProgram" eSuperTypes="#//StochasticModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="FittedModel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//DataSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lr" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.05"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FittedNormalRandomVariable" eSuperTypes="#//FittedContinuousRandomVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="FittedExponentialRandomVariable" eSuperTypes="#//FittedContinuousRandomVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="FittedGammaRandomVariable" eSuperTypes="#//FittedContinuousRandomVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="GammaRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FittedContinuousRandomVariable" abstract="true"
      eSuperTypes="#//ContinouosRandomVariable #//FittedModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inverse_cdf" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//FunctionDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StochasticExpression" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="randomvariable" lowerBound="1"
        eType="#//RandomVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniformRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BetaRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="apha" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beta" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogNormalRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mean" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParetoRandomVariable" eSuperTypes="#//ContinouosRandomVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alpha" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
