/*
 * generated by Xtext 2.25.0
 */
package hu.mit.gamma.environment.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EnvironmentLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/mit/gamma/environment/language/parser/antlr/internal/InternalEnvironmentLanguage.tokens");
	}
}
