<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reducertrace" nsURI="http://www.mit.bme.hu/environment/transformation/Traceability"
    nsPrefix="reducertrace">
  <eClassifiers xsi:type="ecore:EClass" name="ReducerTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//AbstractTrace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTrace" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementaryTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//ElementaryEnvironmentComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeTarget" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/statechart.ecore#//StatechartDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceTarget" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousCompositeInstanceTrace"
      eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentAsynchronousCompositeComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//AsynchronousComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousCompositeInstanceTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentSynchronousCompositeComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//SynchronousComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CascadeCompositeInstanceTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//SynchronousComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentCascadeCompositeComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousCompositeComponentTrace"
      eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentAsynchronousCompositeComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//AsynchronousCompositeComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousCompositeComponentTrace"
      eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentSynchronousCompositeComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//SynchronousCompositeComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CascadeCompositeComponentTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//CascadeCompositeComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentCascadeCompositeComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleChannelTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//SimpleChannel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//SimpleChannel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//PortBinding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//PortBinding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BroadcastChannelTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//BroadcastChannel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//BroadcastChannel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
  </eClassifiers>
</ecore:EPackage>
