/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.environment.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EnvironmentLanguageUiModule extends AbstractEnvironmentLanguageUiModule {

	public EnvironmentLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
