/*
 * generated by Xtext 2.24.0
 */
package hu.mit.gamma.environment.language.scoping;

import hu.bme.mit.gamma.statechart.language.scoping.StatechartLanguageScopeProvider;

public abstract class AbstractEnvironmentLanguageScopeProvider extends StatechartLanguageScopeProvider {
}
