/*
 * generated by Xtext 2.20.0
 */
package hu.mit.gamma.environment.language;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EnvironmentLanguageStandaloneSetup extends EnvironmentLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new EnvironmentLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
