/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.environment.language.scoping;

import hu.bme.mit.gamma.statechart.language.scoping.StatechartLanguageScopeProvider;

public abstract class AbstractEnvironmentLanguageScopeProvider extends StatechartLanguageScopeProvider {
}
