/**
 * generated by Xtext 2.30.0.M2
 */
package hu.bme.mit.gamma.environment.language.ui.wizard;

import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.IProjectTemplateProvider;

/**
 * Create a list with all project templates to be shown in the template new project wizard.
 * 
 * Each template is able to generate one or more projects. Each project can be configured such that any number of files are included.
 */
@SuppressWarnings("all")
public class EnvironmentLanguageProjectTemplateProvider implements IProjectTemplateProvider {
  @Override
  public AbstractProjectTemplate[] getProjectTemplates() {
    GenericStochasticGammaProject _genericStochasticGammaProject = new GenericStochasticGammaProject();
    IoTStochasticGammaProject _ioTStochasticGammaProject = new IoTStochasticGammaProject();
    DualGPSStochasticGammaProject _dualGPSStochasticGammaProject = new DualGPSStochasticGammaProject();
    return new AbstractProjectTemplate[] { _genericStochasticGammaProject, _ioTStochasticGammaProject, _dualGPSStochasticGammaProject };
  }
}
