/*
 * generated by Xtext 2.30.0.M2
 */
package hu.bme.mit.gamma.environment.language.scoping;

import hu.bme.mit.gamma.statechart.language.scoping.StatechartLanguageScopeProvider;

public abstract class AbstractEnvironmentLanguageScopeProvider extends StatechartLanguageScopeProvider {
}
