
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{40725_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1467985212802887"
{40738_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1467985212802887
{40694_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19498175382614136"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19498175382614136
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19498175382614136
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19498175382614136
{40710_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2194596529006958"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2194596529006958
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2194596529006958
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2194596529006958
{40695_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3429906964302063"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3429906964302063
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3429906964302063
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3429906964302063
{40711_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4135861247777939"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4135861247777939
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4135861247777939
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4135861247777939
{40738_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5642860531806946"
{40738_start} <-> {40738_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml