
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29884_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16902534663677216"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.16902534663677216
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16902534663677216
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16902534663677216
{29900_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.23546133935451508"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.23546133935451508
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23546133935451508
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23546133935451508
{29885_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3323056101799011"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3323056101799011
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3323056101799011
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3323056101799011
{29901_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4275943636894226"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4275943636894226
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4275943636894226
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4275943636894226
{29886_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5508832335472107"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5508832335472107
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5508832335472107
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5508832335472107
{29902_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6644455939531326"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6644455939531326
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6644455939531326
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6644455939531326
{29887_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7392366230487823"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7392366230487823
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7392366230487823
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7392366230487823
{29903_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8868676871061325"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8868676871061325
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8868676871061325
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8868676871061325
{29888_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9579774141311646"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9579774141311646
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9579774141311646
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9579774141311646
{29904_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.092830553650856"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.092830553650856
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.092830553650856
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.092830553650856
{29889_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1982479393482208"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.1982479393482208
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1982479393482208
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1982479393482208
{29905_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3059920966625214"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.3059920966625214
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3059920966625214
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3059920966625214
{29890_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4019169360399246"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.4019169360399246
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4019169360399246
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4019169360399246
{29915_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4328032732009888"
{29921_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.4328032732009888
{29906_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4862801879644394"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4862801879644394
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4862801879644394
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4862801879644394
{29916_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5123034343123436"
{29917_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.6067750751972198"
{29891_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.6158517897129059"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6158517897129059
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.6158517897129059
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.6158517897129059
{29907_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6797314435243607"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.6797314435243607
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6797314435243607
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6797314435243607
{29892_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.7961384057998657"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.7961384057998657
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7961384057998657
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7961384057998657
{29908_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.8919351696968079"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.8919351696968079
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.8919351696968079
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.8919351696968079
{29921_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.9859402775764465"
{29921_start} <-> {29921_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml