
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{16557_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1766221672296524"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1766221672296524
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1766221672296524
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1766221672296524
{16572_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19072219729423523"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19072219729423523
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19072219729423523
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19072219729423523
{16587_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.22279994189739227"
{16599_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.22279994189739227
{16588_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24430636130273342"
{16589_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3429590743035078"
{16558_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3752826750278473"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3752826750278473
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3752826750278473
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3752826750278473
{16573_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38955608010292053"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38955608010292053
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38955608010292053
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38955608010292053
{16599_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.41190142929553986"
{16599_start} <-> {16599_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml