
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28972_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19716466963291168"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19716466963291168
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19716466963291168
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19716466963291168
{28987_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20604971051216125"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20604971051216125
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20604971051216125
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20604971051216125
{28973_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3905544877052307"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3905544877052307
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3905544877052307
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3905544877052307
{28988_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40533554553985596"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.40533554553985596
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40533554553985596
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40533554553985596
{28974_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5635792165994644"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5635792165994644
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5635792165994644
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5635792165994644
{28989_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6113413125276566"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6113413125276566
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6113413125276566
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6113413125276566
{28975_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7670489698648453"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7670489698648453
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7670489698648453
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7670489698648453
{28990_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8386048972606659"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8386048972606659
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8386048972606659
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8386048972606659
{29002_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9175844192504883"
{29012_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9175844192504883
{28976_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9740868657827377"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9740868657827377
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9740868657827377
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9740868657827377
{28991_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0547257959842682"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0547257959842682
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0547257959842682
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0547257959842682
{28977_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2004268020391464"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2004268020391464
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.2004268020391464
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.2004268020391464
{28992_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.244370013475418"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.244370013475418
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.244370013475418
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.244370013475418
{29012_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.331102579832077"
{29012_start} <-> {29012_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml