
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{37698_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17441868782043457"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17441868782043457
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17441868782043457
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17441868782043457
{37683_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1859162151813507"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1859162151813507
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1859162151813507
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1859162151813507
{37715_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21862667798995972"
{37723_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.21862667798995972
{37699_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.34834322333335876"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.34834322333335876
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.34834322333335876
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.34834322333335876
{37684_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.366605669260025"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.366605669260025
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.366605669260025
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.366605669260025
{37716_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.47614845633506775"
{37700_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5537290275096893"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5537290275096893
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5537290275096893
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5537290275096893
{37685_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5984761565923691"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5984761565923691
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5984761565923691
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5984761565923691
{37723_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6448906064033508"
{37723_start} <-> {37723_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml