
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{30334_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18510505557060242"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18510505557060242
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18510505557060242
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18510505557060242
{30350_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1964213252067566"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1964213252067566
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1964213252067566
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1964213252067566
{30365_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3584817945957184"
{30372_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.3584817945957184
{30335_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.377814844250679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.377814844250679
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.377814844250679
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.377814844250679
{30351_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41928933560848236"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41928933560848236
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41928933560848236
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41928933560848236
{30336_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5947175323963165"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5947175323963165
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5947175323963165
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5947175323963165
{30352_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6203093379735947"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6203093379735947
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6203093379735947
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6203093379735947
{30366_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6669085919857025"
{30372_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7443988621234894"
{30372_start} <-> {30372_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml