
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31281_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.12579110264778137"
{31295_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.12579110264778137
{31282_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1381498510017991"
{31266_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2007293403148651"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2007293403148651
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2007293403148651
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2007293403148651
{31251_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22386550903320312"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22386550903320312
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.22386550903320312
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.22386550903320312
{31252_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4246036857366562"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4246036857366562
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4246036857366562
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4246036857366562
{31267_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43070006370544434"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.43070006370544434
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43070006370544434
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43070006370544434
{31283_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.47049852553755045"
{31253_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6024470776319504"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6024470776319504
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6024470776319504
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6024470776319504
{31268_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6694792360067368"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6694792360067368
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6694792360067368
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6694792360067368
{31295_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6994878351688385"
{31295_start} <-> {31295_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml