
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28254_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20480011403560638"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20480011403560638
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20480011403560638
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20480011403560638
{28269_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2109111100435257"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2109111100435257
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2109111100435257
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2109111100435257
{28285_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.22442473471164703"
{28294_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.22442473471164703
{28255_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41229698061943054"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41229698061943054
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41229698061943054
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41229698061943054
{28270_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4225102514028549"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4225102514028549
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4225102514028549
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4225102514028549
{28256_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6068559288978577"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6068559288978577
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6068559288978577
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6068559288978577
{28271_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6241397559642792"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6241397559642792
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6241397559642792
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6241397559642792
{28294_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7748929411172867"
{28294_start} <-> {28294_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml