
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9696_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2071155607700348"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2071155607700348
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2071155607700348
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2071155607700348
{9712_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2126545011997223"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2126545011997223
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2126545011997223
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2126545011997223
{9713_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4110551178455353"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4110551178455353
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4110551178455353
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4110551178455353
{9697_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41783973574638367"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.41783973574638367
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41783973574638367
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41783973574638367
{9714_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5921397805213928"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5921397805213928
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5921397805213928
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5921397805213928
{9698_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6453577876091003"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6453577876091003
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6453577876091003
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6453577876091003
{9715_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8117706924676895"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8117706924676895
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8117706924676895
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8117706924676895
{9699_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8488844931125641"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8488844931125641
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8488844931125641
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8488844931125641
{9728_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9093216061592102"
{9734_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9093216061592102
{9716_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.010213702917099"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.010213702917099
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.010213702917099
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.010213702917099
{9700_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0268565565347672"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0268565565347672
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0268565565347672
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0268565565347672
{9701_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1953569501638412"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1953569501638412
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1953569501638412
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1953569501638412
{9717_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2149422019720078"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2149422019720078
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2149422019720078
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2149422019720078
{9702_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3805987983942032"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3805987983942032
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3805987983942032
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3805987983942032
{9718_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4165346175432205"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4165346175432205
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4165346175432205
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4165346175432205
{9734_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.4430193305015564"
{9734_start} <-> {9734_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml