
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17794_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08920670300722122"
{17804_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08920670300722122
{17763_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1798510104417801"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1798510104417801
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1798510104417801
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1798510104417801
{17778_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19392600655555725"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19392600655555725
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19392600655555725
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19392600655555725
{17795_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.35425297170877457"
{17779_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3735261559486389"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3735261559486389
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3735261559486389
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3735261559486389
{17764_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39199309051036835"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39199309051036835
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39199309051036835
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39199309051036835
{17804_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.570445217192173"
{17804_start} <-> {17804_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.570445217192173"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml