
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13340_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16070404648780823"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.16070404648780823
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16070404648780823
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16070404648780823
{13356_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2268034666776657"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2268034666776657
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2268034666776657
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2268034666776657
{13371_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2503196597099304"
{13379_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2503196597099304
{13341_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.34763242304325104"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.34763242304325104
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34763242304325104
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34763242304325104
{13357_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4515944570302963"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4515944570302963
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4515944570302963
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4515944570302963
{13342_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5528827607631683"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5528827607631683
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5528827607631683
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5528827607631683
{13358_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6551398783922195"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6551398783922195
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6551398783922195
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6551398783922195
{13343_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7373053878545761"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7373053878545761
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7373053878545761
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7373053878545761
{13379_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8695303797721863"
{13379_start} <-> {13379_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml