
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{20856_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1748914122581482"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1748914122581482
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1748914122581482
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1748914122581482
{20872_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22178982198238373"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22178982198238373
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22178982198238373
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22178982198238373
{20887_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.28709322214126587"
{20897_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.28709322214126587
{20888_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3235247880220413"
{20857_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.35880063474178314"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.35880063474178314
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.35880063474178314
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.35880063474178314
{20873_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.45697762072086334"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.45697762072086334
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.45697762072086334
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.45697762072086334
{20858_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5531357377767563"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5531357377767563
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5531357377767563
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5531357377767563
{20874_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6656574159860611"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6656574159860611
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6656574159860611
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6656574159860611
{20859_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7431217730045319"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7431217730045319
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7431217730045319
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7431217730045319
{20897_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8170921206474304"
{20897_start} <-> {20897_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml