
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10612_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19131527841091156"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19131527841091156
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19131527841091156
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19131527841091156
{10627_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20618601143360138"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20618601143360138
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20618601143360138
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20618601143360138
{10613_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4053681194782257"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4053681194782257
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4053681194782257
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4053681194782257
{10628_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4101157486438751"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4101157486438751
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4101157486438751
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4101157486438751
{10629_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5808582007884979"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5808582007884979
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5808582007884979
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5808582007884979
{10643_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6042887568473816"
{10654_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6042887568473816
{10614_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.637431725859642"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.637431725859642
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.637431725859642
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.637431725859642
{10630_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7894462645053864"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7894462645053864
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7894462645053864
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7894462645053864
{10615_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8264748007059097"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8264748007059097
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8264748007059097
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8264748007059097
{10644_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8538113385438919"
{10631_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9506497383117676"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9506497383117676
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9506497383117676
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9506497383117676
{10616_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0052087157964706"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0052087157964706
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.0052087157964706
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.0052087157964706
{10654_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.091264545917511"
{10654_start} <-> {10654_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml