
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{5602_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20099668204784393"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20099668204784393
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20099668204784393
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20099668204784393
{5618_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20465075969696045"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20465075969696045
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20465075969696045
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20465075969696045
{5603_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39175643026828766"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39175643026828766
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39175643026828766
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39175643026828766
{5619_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4304763376712799"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4304763376712799
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4304763376712799
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4304763376712799
{5604_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.580004021525383"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.580004021525383
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.580004021525383
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.580004021525383
{5620_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6376924961805344"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6376924961805344
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6376924961805344
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6376924961805344
{5605_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7949724048376083"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7949724048376083
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7949724048376083
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7949724048376083
{5621_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8573395758867264"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8573395758867264
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8573395758867264
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8573395758867264
{5606_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9974935501813889"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9974935501813889
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9974935501813889
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9974935501813889
{5622_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0514252930879593"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.0514252930879593
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0514252930879593
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0514252930879593
{5607_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2259216904640198"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.2259216904640198
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2259216904640198
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2259216904640198
{5623_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2621646374464035"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.2621646374464035
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2621646374464035
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2621646374464035
{5608_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.409681186079979"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.409681186079979
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.409681186079979
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.409681186079979
{5624_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4893155694007874"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.4893155694007874
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.4893155694007874
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.4893155694007874
{5609_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.623915120959282"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.623915120959282
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.623915120959282
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.623915120959282
{5625_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6939925104379654"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.6939925104379654
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6939925104379654
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6939925104379654
{5610_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.8241990357637405"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.8241990357637405
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.8241990357637405
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.8241990357637405
{5626_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.865050658583641"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.865050658583641
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.865050658583641
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.865050658583641
{5611_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 2.000986024737358"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 2.000986024737358
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 2.000986024737358
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 2.000986024737358
{5633_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 2.037081718444824"
{5637_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 2.037081718444824
{5627_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 2.074871748685837"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 2.074871748685837
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 2.074871748685837
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 2.074871748685837
{5612_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 2.1725943237543106"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 2.1725943237543106
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 2.1725943237543106
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 2.1725943237543106
{5628_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 2.278714209794998"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 2.278714209794998
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 2.278714209794998
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 2.278714209794998
{5613_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 2.347985655069351"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 2.347985655069351
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 2.347985655069351
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 2.347985655069351
{5634_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 2.4279834926128387"
{5629_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 2.4798452854156494"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 2.4798452854156494
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 2.4798452854156494
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 2.4798452854156494
{5637_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 2.5623435974121094"
{5637_start} <-> {5637_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml