
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17250_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18333202600479126"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18333202600479126
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18333202600479126
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18333202600479126
{17266_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19188164174556732"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19188164174556732
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19188164174556732
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19188164174556732
{17251_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3816972076892853"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3816972076892853
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3816972076892853
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3816972076892853
{17267_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43506841361522675"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.43506841361522675
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43506841361522675
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43506841361522675
{17252_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.587949126958847"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.587949126958847
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.587949126958847
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.587949126958847
{17268_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6481381803750992"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6481381803750992
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6481381803750992
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6481381803750992
{17253_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7786190807819366"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7786190807819366
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7786190807819366
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7786190807819366
{17269_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.820018008351326"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.820018008351326
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.820018008351326
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.820018008351326
{17254_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0026740431785583"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.0026740431785583
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0026740431785583
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0026740431785583
{17270_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0341365337371826"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.0341365337371826
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0341365337371826
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0341365337371826
{17281_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1305770874023438"
{17289_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1305770874023438
{17282_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.177902340888977"
{17255_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2187695801258087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2187695801258087
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2187695801258087
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2187695801258087
{17271_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2245226502418518"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2245226502418518
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.2245226502418518
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.2245226502418518
{17283_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2641797363758087"
{17284_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4114157855510712"
{17256_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4118985831737518"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4118985831737518
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.4118985831737518
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.4118985831737518
{17272_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4413629472255707"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4413629472255707
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4413629472255707
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4413629472255707
{17257_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.5783567875623703"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.5783567875623703
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.5783567875623703
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.5783567875623703
{17273_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6201587319374084"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6201587319374084
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.6201587319374084
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.6201587319374084
{17289_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.696418821811676"
{17289_start} <-> {17289_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 1.696418821811676"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml