
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38295_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20187684893608093"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20187684893608093
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20187684893608093
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20187684893608093
{38280_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20197702944278717"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20197702944278717
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20197702944278717
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20197702944278717
{38296_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3598490506410599"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3598490506410599
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3598490506410599
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3598490506410599
{38281_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39184655249118805"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39184655249118805
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39184655249118805
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39184655249118805
{38297_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.55274598300457"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.55274598300457
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.55274598300457
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.55274598300457
{38282_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6161343306303024"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6161343306303024
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6161343306303024
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6161343306303024
{38311_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6636627912521362"
{38318_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6636627912521362
{38298_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7451736181974411"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7451736181974411
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7451736181974411
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7451736181974411
{38283_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8346506953239441"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8346506953239441
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8346506953239441
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8346506953239441
{38299_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9516046941280365"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9516046941280365
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9516046941280365
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9516046941280365
{38318_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9690665602684021"
{38318_start} <-> {38318_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml