
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23899_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17099228501319885"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17099228501319885
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17099228501319885
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17099228501319885
{23884_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2266530692577362"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2266530692577362
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2266530692577362
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2266530692577362
{23915_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.26992377638816833"
{23926_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.26992377638816833
{23900_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39177487790584564"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39177487790584564
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39177487790584564
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39177487790584564
{23885_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43595854938030243"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43595854938030243
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43595854938030243
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43595854938030243
{23916_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5377753376960754"
{23917_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5397174999816343"
{23901_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5877970159053802"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5877970159053802
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5877970159053802
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5877970159053802
{23918_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6244053513510153"
{23886_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6482096314430237"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6482096314430237
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6482096314430237
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6482096314430237
{23902_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7725820541381836"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7725820541381836
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7725820541381836
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7725820541381836
{23919_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8198704541428015"
{23887_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8671560734510422"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8671560734510422
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8671560734510422
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8671560734510422
{23926_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.915544182062149"
{23926_start} <-> {23926_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml