
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{37160_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21913889050483704"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21913889050483704
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21913889050483704
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21913889050483704
{37145_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23674382269382477"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.23674382269382477
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23674382269382477
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23674382269382477
{37161_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42794081568717957"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.42794081568717957
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42794081568717957
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42794081568717957
{37146_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4352928698062897"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4352928698062897
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4352928698062897
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4352928698062897
{37162_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6187242716550827"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6187242716550827
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6187242716550827
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6187242716550827
{37147_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6504755467176437"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6504755467176437
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6504755467176437
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6504755467176437
{37175_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6640458106994629"
{37183_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6640458106994629
{37176_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7235609851777554"
{37163_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.810819685459137"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.810819685459137
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.810819685459137
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.810819685459137
{37148_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8372303545475006"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8372303545475006
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8372303545475006
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8372303545475006
{37164_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0017202645540237"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0017202645540237
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0017202645540237
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0017202645540237
{37149_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0376399755477905"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0376399755477905
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0376399755477905
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0376399755477905
{37183_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0733178853988647"
{37183_start} <-> {37183_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml