
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{36117_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17142710089683533"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17142710089683533
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17142710089683533
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17142710089683533
{36133_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2065313756465912"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2065313756465912
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2065313756465912
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2065313756465912
{36118_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3394368588924408"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3394368588924408
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3394368588924408
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3394368588924408
{36134_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39385662972927094"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.39385662972927094
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39385662972927094
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39385662972927094
{36149_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.47206738591194153"
{36161_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.47206738591194153
{36119_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.47600051760673523"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.47600051760673523
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.47600051760673523
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.47600051760673523
{36150_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5382499545812607"
{36135_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.557793915271759"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.557793915271759
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.557793915271759
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.557793915271759
{36120_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6670087724924088"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6670087724924088
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6670087724924088
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6670087724924088
{36151_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7824326455593109"
{36136_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.786242738366127"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.786242738366127
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.786242738366127
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.786242738366127
{36161_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9243132472038269"
{36161_start} <-> {36161_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml