
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{32581_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1702510118484497"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1702510118484497
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1702510118484497
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1702510118484497
{32596_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2410004436969757"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2410004436969757
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2410004436969757
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2410004436969757
{32611_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2643960416316986"
{32618_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2643960416316986
{32582_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3563541769981384"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3563541769981384
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3563541769981384
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3563541769981384
{32597_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4223155528306961"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4223155528306961
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4223155528306961
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4223155528306961
{32583_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5781529545783997"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5781529545783997
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5781529545783997
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5781529545783997
{32598_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6106419861316681"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6106419861316681
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6106419861316681
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6106419861316681
{32612_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7361162602901459"
{32584_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7566903978586197"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7566903978586197
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7566903978586197
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7566903978586197
{32599_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8133324384689331"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8133324384689331
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8133324384689331
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8133324384689331
{32613_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.898420050740242"
{32618_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9322172701358795"
{32618_start} <-> {32618_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml