
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{39324_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1594053953886032"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1594053953886032
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1594053953886032
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1594053953886032
{39340_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20691953599452972"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20691953599452972
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.20691953599452972
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.20691953599452972
{39325_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38834279775619507"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38834279775619507
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38834279775619507
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38834279775619507
{39341_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4093836396932602"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4093836396932602
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4093836396932602
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4093836396932602
{39355_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.43430814146995544"
{39365_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.43430814146995544
{39326_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5779038220643997"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5779038220643997
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5779038220643997
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5779038220643997
{39342_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5827133655548096"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5827133655548096
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5827133655548096
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5827133655548096
{39327_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7544824331998825"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7544824331998825
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7544824331998825
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7544824331998825
{39343_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7849362641572952"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7849362641572952
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7849362641572952
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7849362641572952
{39356_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.898931622505188"
{39357_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9210670944303274"
{39328_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9337575733661652"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9337575733661652
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9337575733661652
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9337575733661652
{39365_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9533697664737701"
{39365_start} <-> {39365_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml