
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27065_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21748463809490204"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21748463809490204
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21748463809490204
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21748463809490204
{27080_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22269058227539062"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22269058227539062
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22269058227539062
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22269058227539062
{27081_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39584632217884064"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39584632217884064
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39584632217884064
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39584632217884064
{27066_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41881439089775085"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41881439089775085
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41881439089775085
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41881439089775085
{27082_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6006923317909241"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6006923317909241
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6006923317909241
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6006923317909241
{27067_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6116403788328171"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6116403788328171
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6116403788328171
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6116403788328171
{27096_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7332746386528015"
{27107_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7332746386528015
{27068_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8053621053695679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8053621053695679
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8053621053695679
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8053621053695679
{27083_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8154236972332001"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8154236972332001
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8154236972332001
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8154236972332001
{27097_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8384452387690544"
{27098_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.844347299542278"
{27084_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0168011486530304"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0168011486530304
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0168011486530304
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0168011486530304
{27069_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.018702656030655"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.018702656030655
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.018702656030655
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.018702656030655
{27085_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2096110433340073"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2096110433340073
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2096110433340073
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2096110433340073
{27070_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2172912806272507"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2172912806272507
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2172912806272507
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2172912806272507
{27107_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2299286425113678"
{27107_start} <-> {27107_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml