
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27984_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1291044056415558"
{27997_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1291044056415558
{27969_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1794501692056656"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1794501692056656
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1794501692056656
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1794501692056656
{27953_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20248527824878693"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20248527824878693
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20248527824878693
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20248527824878693
{27985_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2990758568048477"
{27970_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3962753117084503"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3962753117084503
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3962753117084503
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3962753117084503
{27954_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3978510946035385"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3978510946035385
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3978510946035385
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3978510946035385
{27955_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5842979401350021"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5842979401350021
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5842979401350021
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5842979401350021
{27971_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6145993769168854"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6145993769168854
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6145993769168854
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6145993769168854
{27986_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7673016637563705"
{27997_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7712542116641998"
{27997_start} <-> {27997_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml