
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15209_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19033439457416534"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19033439457416534
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19033439457416534
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19033439457416534
{15225_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20288725197315216"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20288725197315216
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20288725197315216
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20288725197315216
{15210_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.34404677152633667"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.34404677152633667
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34404677152633667
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34404677152633667
{15226_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38104383647441864"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.38104383647441864
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38104383647441864
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38104383647441864
{15240_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4245004951953888"
{15246_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4245004951953888
{15241_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5172632336616516"
{15211_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5252981036901474"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5252981036901474
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5252981036901474
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5252981036901474
{15227_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6088344603776932"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6088344603776932
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6088344603776932
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6088344603776932
{15212_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7332294434309006"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7332294434309006
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7332294434309006
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7332294434309006
{15242_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7360957264900208"
{15246_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7826539576053619"
{15246_start} <-> {15246_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml