
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{40437_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.01191419642418623"
{40446_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.01191419642418623
{40406_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1960534006357193"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1960534006357193
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1960534006357193
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1960534006357193
{40421_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19734953343868256"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19734953343868256
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19734953343868256
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19734953343868256
{40438_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.32680109422653913"
{40407_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4225965440273285"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4225965440273285
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4225965440273285
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4225965440273285
{40422_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42587417364120483"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42587417364120483
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42587417364120483
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42587417364120483
{40446_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4956238893792033"
{40446_start} <-> {40446_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml