
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{7369_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17608629167079926"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17608629167079926
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17608629167079926
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17608629167079926
{7401_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.20235158503055573"
{7410_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.20235158503055573
{7385_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20240181684494019"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20240181684494019
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20240181684494019
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20240181684494019
{7386_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3696482628583908"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3696482628583908
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3696482628583908
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3696482628583908
{7370_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.383886381983757"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.383886381983757
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.383886381983757
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.383886381983757
{7387_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5502352267503738"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5502352267503738
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5502352267503738
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5502352267503738
{7410_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5843394845724106"
{7410_start} <-> {7410_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml