
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31632_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17742563784122467"
{31642_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17742563784122467
{31616_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18361882865428925"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18361882865428925
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18361882865428925
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18361882865428925
{31633_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2257452793419361"
{31600_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2348148226737976"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2348148226737976
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2348148226737976
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2348148226737976
{31617_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.34702692925930023"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.34702692925930023
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34702692925930023
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34702692925930023
{31634_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3516486622393131"
{31601_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4041449576616287"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4041449576616287
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4041449576616287
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4041449576616287
{31635_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5028159208595753"
{31618_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5478512197732925"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5478512197732925
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5478512197732925
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5478512197732925
{31602_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6028951555490494"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6028951555490494
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6028951555490494
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6028951555490494
{31642_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7387131601572037"
{31642_start} <-> {31642_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml