
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18353_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.02652818150818348"
{18365_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.02652818150818348
{18354_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.06529705785214901"
{18337_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16795799136161804"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.16795799136161804
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16795799136161804
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16795799136161804
{18321_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20887739956378937"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20887739956378937
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20887739956378937
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20887739956378937
{18338_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3411015421152115"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3411015421152115
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3411015421152115
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3411015421152115
{18322_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3932293802499771"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3932293802499771
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3932293802499771
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3932293802499771
{18339_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5327184051275253"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5327184051275253
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5327184051275253
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5327184051275253
{18355_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5371449794620275"
{18323_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5746241807937622"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5746241807937622
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5746241807937622
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5746241807937622
{18356_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6099061500281096"
{18365_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6225972790271044"
{18365_start} <-> {18365_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml