
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28543_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.09330520778894424"
{28556_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.09330520778894424
{28512_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17873241007328033"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.17873241007328033
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.17873241007328033
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.17873241007328033
{28544_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18649958074092865"
{28528_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22151696681976318"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22151696681976318
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22151696681976318
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22151696681976318
{28513_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.35992899537086487"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.35992899537086487
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.35992899537086487
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.35992899537086487
{28529_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.421803280711174"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.421803280711174
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.421803280711174
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.421803280711174
{28545_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.43314433097839355"
{28514_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5322263240814209"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5322263240814209
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5322263240814209
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5322263240814209
{28556_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6160315051674843"
{28556_start} <-> {28556_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml