
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17556_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21245448291301727"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21245448291301727
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21245448291301727
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21245448291301727
{17572_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2140800803899765"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2140800803899765
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2140800803899765
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2140800803899765
{17573_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4057425409555435"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4057425409555435
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4057425409555435
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4057425409555435
{17557_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42307180166244507"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.42307180166244507
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42307180166244507
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42307180166244507
{17574_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5868973881006241"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5868973881006241
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5868973881006241
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5868973881006241
{17588_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6060315370559692"
{17594_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6060315370559692
{17558_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6496382653713226"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6496382653713226
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6496382653713226
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6496382653713226
{17589_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6957222893834114"
{17575_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7833428084850311"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7833428084850311
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7833428084850311
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7833428084850311
{17559_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.814674898982048"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.814674898982048
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.814674898982048
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.814674898982048
{17576_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9775026440620422"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9775026440620422
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9775026440620422
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9775026440620422
{17560_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0176557153463364"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0176557153463364
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0176557153463364
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0176557153463364
{17577_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1696892082691193"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1696892082691193
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.1696892082691193
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.1696892082691193
{17561_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.203423723578453"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.203423723578453
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.203423723578453
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.203423723578453
{17594_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2432109713554382"
{17594_start} <-> {17594_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml