
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{6596_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.07882872968912125"
{6608_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.07882872968912125
{6580_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21521437168121338"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21521437168121338
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21521437168121338
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21521437168121338
{6564_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23567743599414825"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.23567743599414825
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23567743599414825
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23567743599414825
{6597_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.32572952657938004"
{6581_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38315194845199585"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38315194845199585
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38315194845199585
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38315194845199585
{6565_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4253396838903427"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4253396838903427
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4253396838903427
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4253396838903427
{6608_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5227280035614967"
{6608_start} <-> {6608_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.5227280035614967"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml