
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15684_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20496001839637756"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20496001839637756
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20496001839637756
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20496001839637756
{15668_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.24246835708618164"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.24246835708618164
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24246835708618164
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24246835708618164
{15700_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.26489996910095215"
{15708_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.26489996910095215
{15685_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4060010462999344"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4060010462999344
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4060010462999344
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4060010462999344
{15669_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.44278712570667267"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44278712570667267
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44278712570667267
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44278712570667267
{15686_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6161030977964401"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6161030977964401
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6161030977964401
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6161030977964401
{15670_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6372230798006058"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6372230798006058
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6372230798006058
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6372230798006058
{15687_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8227752447128296"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8227752447128296
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8227752447128296
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8227752447128296
{15708_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8265864849090576"
{15708_start} <-> {15708_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml