
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8619_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21068863570690155"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21068863570690155
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21068863570690155
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21068863570690155
{8604_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2639574110507965"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2639574110507965
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2639574110507965
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2639574110507965
{8620_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3936232179403305"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3936232179403305
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3936232179403305
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3936232179403305
{8605_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5027068704366684"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5027068704366684
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5027068704366684
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5027068704366684
{8635_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5893884301185608"
{8644_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5893884301185608
{8621_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5919469892978668"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5919469892978668
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5919469892978668
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5919469892978668
{8636_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6262421570718288"
{8606_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7068472057580948"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7068472057580948
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.7068472057580948
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.7068472057580948
{8622_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8038860261440277"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8038860261440277
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8038860261440277
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8038860261440277
{8607_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9259779006242752"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9259779006242752
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9259779006242752
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9259779006242752
{8623_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9878520518541336"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9878520518541336
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9878520518541336
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9878520518541336
{8608_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0875928699970245"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0875928699970245
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0875928699970245
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0875928699970245
{8624_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1755020320415497"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1755020320415497
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1755020320415497
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1755020320415497
{8644_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1810988783836365"
{8644_start} <-> {8644_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml