
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9470_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20327714085578918"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20327714085578918
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20327714085578918
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20327714085578918
{9485_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22618302702903748"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.22618302702903748
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22618302702903748
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22618302702903748
{9499_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2453984171152115"
{9506_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2453984171152115
{9471_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4069404900074005"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4069404900074005
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4069404900074005
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4069404900074005
{9486_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.49335429072380066"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.49335429072380066
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.49335429072380066
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.49335429072380066
{9472_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5879119336605072"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5879119336605072
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5879119336605072
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5879119336605072
{9487_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6833741664886475"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6833741664886475
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6833741664886475
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6833741664886475
{9506_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7760808020830154"
{9506_start} <-> {9506_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml