
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34202_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19342370331287384"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19342370331287384
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19342370331287384
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19342370331287384
{34218_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21822938323020935"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21822938323020935
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21822938323020935
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21822938323020935
{34234_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24575714766979218"
{34246_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24575714766979218
{34203_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36542609333992004"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.36542609333992004
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36542609333992004
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36542609333992004
{34219_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41038523614406586"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41038523614406586
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41038523614406586
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41038523614406586
{34204_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5662215650081635"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5662215650081635
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5662215650081635
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5662215650081635
{34220_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5777392834424973"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5777392834424973
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5777392834424973
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5777392834424973
{34246_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6699614375829697"
{34246_start} <-> {34246_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml