
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15187_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18651394546031952"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18651394546031952
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18651394546031952
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18651394546031952
{15172_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2529616355895996"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2529616355895996
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2529616355895996
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2529616355895996
{15202_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.35324540734291077"
{15208_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.35324540734291077
{15188_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40155209600925446"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40155209600925446
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40155209600925446
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40155209600925446
{15173_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4658152163028717"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4658152163028717
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4658152163028717
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4658152163028717
{15189_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5876715332269669"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5876715332269669
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5876715332269669
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5876715332269669
{15174_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6536806523799896"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6536806523799896
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6536806523799896
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6536806523799896
{15203_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7225729823112488"
{15208_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7382118999958038"
{15208_start} <-> {15208_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml