
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15617_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.015400479547679424"
{15627_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.015400479547679424
{15618_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.082496109418571"
{15601_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16946429014205933"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.16946429014205933
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.16946429014205933
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.16946429014205933
{15585_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19852343201637268"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19852343201637268
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19852343201637268
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19852343201637268
{15602_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3955642431974411"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3955642431974411
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3955642431974411
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3955642431974411
{15586_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3984578251838684"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3984578251838684
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3984578251838684
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3984578251838684
{15619_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.44511911552399397"
{15627_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.48737512063235044"
{15627_start} <-> {15627_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml