
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11411_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19900907576084137"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19900907576084137
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19900907576084137
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19900907576084137
{11427_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20197686553001404"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20197686553001404
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20197686553001404
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20197686553001404
{11412_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39896130561828613"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.39896130561828613
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39896130561828613
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39896130561828613
{11443_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.42357000708580017"
{11448_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.42357000708580017
{11428_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4500449001789093"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4500449001789093
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4500449001789093
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4500449001789093
{11444_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.518748052418232"
{11445_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5469624381512403"
{11413_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5989768654108047"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5989768654108047
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5989768654108047
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5989768654108047
{11429_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6460214704275131"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6460214704275131
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6460214704275131
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6460214704275131
{11414_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8075225055217743"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8075225055217743
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8075225055217743
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8075225055217743
{11430_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8222505450248718"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8222505450248718
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8222505450248718
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8222505450248718
{11415_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0345630645751953"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0345630645751953
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0345630645751953
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0345630645751953
{11431_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.040139079093933"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.040139079093933
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.040139079093933
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.040139079093933
{11448_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0509882867336273"
{11448_start} <-> {11448_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml