
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8075_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16767507791519165"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.16767507791519165
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16767507791519165
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16767507791519165
{8059_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1745607852935791"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1745607852935791
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1745607852935791
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1745607852935791
{8076_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3492094725370407"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3492094725370407
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3492094725370407
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3492094725370407
{8060_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3720708191394806"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3720708191394806
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3720708191394806
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3720708191394806
{8077_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5318149477243423"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5318149477243423
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5318149477243423
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5318149477243423
{8061_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5861541777849197"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5861541777849197
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5861541777849197
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5861541777849197
{8062_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7689694762229919"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7689694762229919
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7689694762229919
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7689694762229919
{8078_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7764337360858917"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7764337360858917
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7764337360858917
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7764337360858917
{8079_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9576487243175507"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9576487243175507
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9576487243175507
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9576487243175507
{8063_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9633868932723999"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9633868932723999
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9633868932723999
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9633868932723999
{8090_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1173371076583862"
{8097_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1173371076583862
{8064_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.148331806063652"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.148331806063652
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.148331806063652
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.148331806063652
{8080_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.191685900092125"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.191685900092125
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.191685900092125
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.191685900092125
{8081_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3671305924654007"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3671305924654007
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3671305924654007
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3671305924654007
{8065_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.367672547698021"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.367672547698021
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.367672547698021
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.367672547698021
{8097_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.4214524626731873"
{8097_start} <-> {8097_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 1.4214524626731873"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml