
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4791_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08123566955327988"
{4798_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08123566955327988
{4792_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11373512074351311"
{4775_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19580037891864777"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19580037891864777
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19580037891864777
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19580037891864777
{4760_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21655169129371643"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21655169129371643
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21655169129371643
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21655169129371643
{4776_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4062127023935318"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4062127023935318
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4062127023935318
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4062127023935318
{4761_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41401056945323944"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41401056945323944
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41401056945323944
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41401056945323944
{4798_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5109479054808617"
{4798_start} <-> {4798_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml