
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{1606_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19432716071605682"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19432716071605682
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19432716071605682
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19432716071605682
{1590_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1999346911907196"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1999346911907196
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1999346911907196
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1999346911907196
{1622_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.20424342155456543"
{1633_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.20424342155456543
{1623_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.379011869430542"
{1607_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4023614078760147"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4023614078760147
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4023614078760147
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4023614078760147
{1591_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41121552884578705"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41121552884578705
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41121552884578705
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41121552884578705
{1592_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.605614423751831"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.605614423751831
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.605614423751831
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.605614423751831
{1608_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6217296272516251"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6217296272516251
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6217296272516251
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6217296272516251
{1593_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.803131639957428"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.803131639957428
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.803131639957428
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.803131639957428
{1633_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8138971924781799"
{1633_start} <-> {1633_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml