
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27026_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18909688293933868"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18909688293933868
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18909688293933868
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18909688293933868
{27041_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20414207875728607"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20414207875728607
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20414207875728607
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20414207875728607
{27027_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37749531865119934"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.37749531865119934
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37749531865119934
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37749531865119934
{27042_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4155420511960983"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4155420511960983
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4155420511960983
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4155420511960983
{27057_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5243498086929321"
{27064_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5243498086929321
{27058_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5681707561016083"
{27028_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6197874844074249"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6197874844074249
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6197874844074249
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6197874844074249
{27043_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.624194011092186"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.624194011092186
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.624194011092186
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.624194011092186
{27044_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8270860463380814"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8270860463380814
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8270860463380814
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8270860463380814
{27029_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.83400559425354"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.83400559425354
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.83400559425354
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.83400559425354
{27059_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9673988223075867"
{27045_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0219058841466904"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0219058841466904
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0219058841466904
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0219058841466904
{27030_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0638377815485"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0638377815485
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0638377815485
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0638377815485
{27064_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.068226933479309"
{27064_start} <-> {27064_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml