
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9811_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.06540297716856003"
{9822_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.06540297716856003
{9795_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2014709711074829"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2014709711074829
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2014709711074829
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2014709711074829
{9779_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20523972809314728"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20523972809314728
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20523972809314728
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20523972809314728
{9812_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2592061534523964"
{9813_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3670370727777481"
{9780_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37795697152614594"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.37795697152614594
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.37795697152614594
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.37795697152614594
{9796_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4174061715602875"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4174061715602875
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4174061715602875
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4174061715602875
{9814_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.52098049223423"
{9822_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5398740991950035"
{9822_start} <-> {9822_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml