
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23344_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1986413300037384"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1986413300037384
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1986413300037384
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1986413300037384
{23359_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20269931852817535"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20269931852817535
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20269931852817535
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20269931852817535
{23360_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3884723633527756"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3884723633527756
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3884723633527756
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3884723633527756
{23374_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.40097108483314514"
{23386_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.40097108483314514
{23345_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41365866363048553"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41365866363048553
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41365866363048553
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41365866363048553
{23361_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5798919051885605"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5798919051885605
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5798919051885605
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5798919051885605
{23375_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5912104398012161"
{23346_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6313261985778809"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6313261985778809
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6313261985778809
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6313261985778809
{23362_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8112286031246185"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8112286031246185
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8112286031246185
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8112286031246185
{23347_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8467589765787125"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8467589765787125
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8467589765787125
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8467589765787125
{23376_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0089040845632553"
{23386_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0126566588878632"
{23386_start} <-> {23386_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml