
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18718_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.15266096591949463"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.15266096591949463
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15266096591949463
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15266096591949463
{18703_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20714567601680756"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20714567601680756
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20714567601680756
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20714567601680756
{18719_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.36242254078388214"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.36242254078388214
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36242254078388214
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36242254078388214
{18704_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41861528158187866"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41861528158187866
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41861528158187866
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41861528158187866
{18720_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5786051899194717"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5786051899194717
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5786051899194717
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5786051899194717
{18733_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6498792767524719"
{18744_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6498792767524719
{18705_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6711905300617218"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6711905300617218
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6711905300617218
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6711905300617218
{18721_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7653203755617142"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7653203755617142
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7653203755617142
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7653203755617142
{18706_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8898908644914627"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8898908644914627
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8898908644914627
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8898908644914627
{18722_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9648024439811707"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9648024439811707
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9648024439811707
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9648024439811707
{18707_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0821057260036469"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0821057260036469
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0821057260036469
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0821057260036469
{18723_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1635105609893799"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1635105609893799
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1635105609893799
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1635105609893799
{18744_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2332159280776978"
{18744_start} <-> {18744_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml