
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2924_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16905751824378967"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.16905751824378967
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16905751824378967
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16905751824378967
{2956_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2061009258031845"
{2970_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2061009258031845
{2940_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.23061972856521606"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.23061972856521606
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23061972856521606
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23061972856521606
{2925_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3761777877807617"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3761777877807617
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3761777877807617
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3761777877807617
{2941_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4410760700702667"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4410760700702667
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4410760700702667
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4410760700702667
{2957_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5123388022184372"
{2926_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5847987234592438"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5847987234592438
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5847987234592438
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5847987234592438
{2970_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6400484591722488"
{2970_start} <-> {2970_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml