
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9638_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.09523817896842957"
{9649_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.09523817896842957
{9639_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.10702739004045725"
{9640_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1453593047335744"
{9607_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18682710826396942"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18682710826396942
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18682710826396942
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18682710826396942
{9623_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18839336931705475"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18839336931705475
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18839336931705475
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18839336931705475
{9608_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38640186190605164"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38640186190605164
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38640186190605164
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38640186190605164
{9624_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4134497195482254"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4134497195482254
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134497195482254
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134497195482254
{9649_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5553706586360931"
{9649_start} <-> {9649_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml