
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15740_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.06288918107748032"
{15747_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.06288918107748032
{15741_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1402924358844757"
{15725_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1724732369184494"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1724732369184494
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1724732369184494
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1724732369184494
{15709_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19915279746055603"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19915279746055603
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19915279746055603
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19915279746055603
{15726_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.376368910074234"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.376368910074234
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.376368910074234
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.376368910074234
{15710_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38209448754787445"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38209448754787445
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38209448754787445
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38209448754787445
{15727_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5597968101501465"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5597968101501465
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5597968101501465
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5597968101501465
{15747_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6045058593153954"
{15747_start} <-> {15747_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml