
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{20596_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1531773954629898"
{20602_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1531773954629898
{20580_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1948869228363037"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1948869228363037
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1948869228363037
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1948869228363037
{20564_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2276674509048462"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2276674509048462
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2276674509048462
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2276674509048462
{20581_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3858442157506943"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3858442157506943
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3858442157506943
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3858442157506943
{20565_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.414575532078743"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.414575532078743
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.414575532078743
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.414575532078743
{20597_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4438371807336807"
{20566_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6008540689945221"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6008540689945221
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6008540689945221
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6008540689945221
{20582_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.610677644610405"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.610677644610405
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.610677644610405
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.610677644610405
{20602_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7223210483789444"
{20602_start} <-> {20602_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml