
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38152_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18615840375423431"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18615840375423431
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18615840375423431
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18615840375423431
{38168_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.187168687582016"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.187168687582016
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.187168687582016
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.187168687582016
{38169_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3889763504266739"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3889763504266739
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3889763504266739
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3889763504266739
{38153_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4259383827447891"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4259383827447891
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4259383827447891
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4259383827447891
{38184_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5828176140785217"
{38194_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5828176140785217
{38170_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5873061716556549"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5873061716556549
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5873061716556549
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5873061716556549
{38154_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6133764833211899"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6133764833211899
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6133764833211899
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6133764833211899
{38171_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7733709812164307"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7733709812164307
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7733709812164307
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7733709812164307
{38155_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8016270101070404"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8016270101070404
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8016270101070404
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8016270101070404
{38172_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9752800017595291"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9752800017595291
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9752800017595291
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9752800017595291
{38156_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9855656623840332"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9855656623840332
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9855656623840332
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9855656623840332
{38194_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0243377387523651"
{38194_start} <-> {38194_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml