
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38403_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17403505742549896"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17403505742549896
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17403505742549896
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17403505742549896
{38418_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19357207417488098"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19357207417488098
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19357207417488098
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19357207417488098
{38434_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2542933523654938"
{38444_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2542933523654938
{38404_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37264184653759"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.37264184653759
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37264184653759
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37264184653759
{38419_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3756791353225708"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3756791353225708
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3756791353225708
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3756791353225708
{38435_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.39239297807216644"
{38436_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5352271497249603"
{38420_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5687969326972961"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5687969326972961
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5687969326972961
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5687969326972961
{38405_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5714236497879028"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5714236497879028
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5714236497879028
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5714236497879028
{38444_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7023501694202423"
{38444_start} <-> {38444_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml