
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2082_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17570194602012634"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17570194602012634
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17570194602012634
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17570194602012634
{2097_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19994722306728363"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19994722306728363
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19994722306728363
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19994722306728363
{2083_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3668600916862488"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3668600916862488
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3668600916862488
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3668600916862488
{2098_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4099469482898712"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4099469482898712
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4099469482898712
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4099469482898712
{2084_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5667155086994171"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5667155086994171
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5667155086994171
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5667155086994171
{2099_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5874174982309341"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5874174982309341
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5874174982309341
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5874174982309341
{2085_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7921290993690491"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7921290993690491
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7921290993690491
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7921290993690491
{2100_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7929001301527023"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7929001301527023
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7929001301527023
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7929001301527023
{2086_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9681180715560913"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9681180715560913
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9681180715560913
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9681180715560913
{2101_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9747534096240997"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9747534096240997
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9747534096240997
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9747534096240997
{2102_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1212478131055832"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.1212478131055832
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1212478131055832
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1212478131055832
{2087_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1627212166786194"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.1627212166786194
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1627212166786194
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1627212166786194
{2113_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1703988313674927"
{2119_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1703988313674927
{2103_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3293635100126266"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3293635100126266
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3293635100126266
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3293635100126266
{2088_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3787966072559357"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3787966072559357
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3787966072559357
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3787966072559357
{2114_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5351071059703827"
{2119_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.5398440062999725"
{2119_start} <-> {2119_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml