
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2054_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17696288228034973"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17696288228034973
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17696288228034973
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17696288228034973
{2039_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1866481900215149"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1866481900215149
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1866481900215149
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1866481900215149
{2055_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4056522101163864"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4056522101163864
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4056522101163864
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4056522101163864
{2040_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.424511194229126"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.424511194229126
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.424511194229126
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.424511194229126
{2070_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4600224494934082"
{2081_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4600224494934082
{2071_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5151620171964169"
{2056_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5772756785154343"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5772756785154343
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5772756785154343
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5772756785154343
{2041_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5992255657911301"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5992255657911301
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5992255657911301
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5992255657911301
{2057_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7413892596960068"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7413892596960068
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7413892596960068
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7413892596960068
{2042_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7876410931348801"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7876410931348801
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7876410931348801
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7876410931348801
{2072_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7958011887967587"
{2073_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9083698578178883"
{2058_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9254961311817169"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9254961311817169
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9254961311817169
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9254961311817169
{2043_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9611922204494476"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9611922204494476
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9611922204494476
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9611922204494476
{2081_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0457123517990112"
{2081_start} <-> {2081_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml