
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3307_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2123853862285614"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2123853862285614
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.2123853862285614
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.2123853862285614
{3323_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2360069751739502"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2360069751739502
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2360069751739502
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2360069751739502
{3308_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3809188902378082"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3809188902378082
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3809188902378082
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3809188902378082
{3339_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.39494219422340393"
{3344_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.39494219422340393
{3324_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43462421000003815"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43462421000003815
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43462421000003815
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43462421000003815
{3309_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5950182378292084"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5950182378292084
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5950182378292084
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5950182378292084
{3325_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6039987802505493"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6039987802505493
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6039987802505493
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6039987802505493
{3310_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7807205766439438"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7807205766439438
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7807205766439438
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7807205766439438
{3326_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8007722496986389"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8007722496986389
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8007722496986389
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8007722496986389
{3344_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8046206533908844"
{3344_start} <-> {3344_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml