
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{26515_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17359761893749237"
{26520_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17359761893749237
{26484_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1803165078163147"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1803165078163147
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1803165078163147
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1803165078163147
{26500_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2218470275402069"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2218470275402069
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2218470275402069
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2218470275402069
{26485_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39846716821193695"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39846716821193695
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39846716821193695
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39846716821193695
{26501_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43946903944015503"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43946903944015503
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43946903944015503
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43946903944015503
{26486_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.547989085316658"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.547989085316658
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.547989085316658
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.547989085316658
{26520_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6214990168809891"
{26520_start} <-> {26520_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml