
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31296_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17698125541210175"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17698125541210175
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17698125541210175
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17698125541210175
{31311_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2362270951271057"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2362270951271057
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2362270951271057
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2362270951271057
{31297_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3680165857076645"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3680165857076645
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3680165857076645
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3680165857076645
{31327_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.42660167813301086"
{31337_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.42660167813301086
{31312_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.44193653762340546"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44193653762340546
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.44193653762340546
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.44193653762340546
{31328_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4577403664588928"
{31298_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.538588747382164"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.538588747382164
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.538588747382164
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.538588747382164
{31313_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6356088072061539"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6356088072061539
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6356088072061539
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6356088072061539
{31299_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7444746196269989"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7444746196269989
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7444746196269989
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7444746196269989
{31329_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7529241144657135"
{31337_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8319627940654755"
{31337_start} <-> {31337_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml