
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15438_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.033845074474811554"
{15454_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.033845074474811554
{15439_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.04925606120377779"
{15440_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15620508510619402"
{15422_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19656634330749512"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19656634330749512
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19656634330749512
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19656634330749512
{15407_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20149974524974823"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20149974524974823
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20149974524974823
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20149974524974823
{15423_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3829353451728821"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3829353451728821
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3829353451728821
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3829353451728821
{15408_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4036894738674164"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4036894738674164
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4036894738674164
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4036894738674164
{15454_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5287266448140144"
{15454_start} <-> {15454_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml