
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{16516_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20767533779144287"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20767533779144287
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20767533779144287
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20767533779144287
{16531_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22180895507335663"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22180895507335663
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.22180895507335663
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.22180895507335663
{16532_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4152473360300064"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4152473360300064
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4152473360300064
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4152473360300064
{16517_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4205695539712906"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4205695539712906
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4205695539712906
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4205695539712906
{16533_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6000427603721619"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6000427603721619
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6000427603721619
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6000427603721619
{16518_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6208667755126953"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6208667755126953
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6208667755126953
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6208667755126953
{16547_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7678816318511963"
{16556_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7678816318511963
{16534_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7993858158588409"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7993858158588409
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7993858158588409
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7993858158588409
{16519_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8225872665643692"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8225872665643692
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8225872665643692
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8225872665643692
{16548_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.845790334045887"
{16549_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9486194103956223"
{16535_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.99741992354393"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.99741992354393
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.99741992354393
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.99741992354393
{16520_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0291737616062164"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0291737616062164
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0291737616062164
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0291737616062164
{16556_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1534464657306671"
{16556_start} <-> {16556_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml