
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34528_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17726613581180573"
{34541_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17726613581180573
{34512_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19337742030620575"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19337742030620575
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19337742030620575
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19337742030620575
{34497_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20484523475170135"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20484523475170135
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.20484523475170135
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.20484523475170135
{34513_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4033190608024597"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4033190608024597
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4033190608024597
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4033190608024597
{34498_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40349356830120087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40349356830120087
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.40349356830120087
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.40349356830120087
{34514_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5773411989212036"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5773411989212036
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5773411989212036
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5773411989212036
{34499_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6007308810949326"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6007308810949326
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6007308810949326
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6007308810949326
{34541_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6740817576646805"
{34541_start} <-> {34541_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml