
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{19146_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19244182109832764"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19244182109832764
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19244182109832764
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19244182109832764
{19131_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21904243528842926"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21904243528842926
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21904243528842926
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21904243528842926
{19147_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38393332064151764"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38393332064151764
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38393332064151764
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38393332064151764
{19132_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4349333494901657"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4349333494901657
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4349333494901657
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4349333494901657
{19162_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5820344090461731"
{19170_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5820344090461731
{19133_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6095733791589737"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6095733791589737
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6095733791589737
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6095733791589737
{19148_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6171691417694092"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6171691417694092
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6171691417694092
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6171691417694092
{19163_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6631059423089027"
{19134_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7959250807762146"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7959250807762146
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7959250807762146
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7959250807762146
{19149_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8267667442560196"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8267667442560196
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8267667442560196
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8267667442560196
{19164_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9383531287312508"
{19135_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0257913172245026"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0257913172245026
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0257913172245026
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0257913172245026
{19150_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0339686572551727"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0339686572551727
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0339686572551727
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0339686572551727
{19170_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1483188271522522"
{19170_start} <-> {19170_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml