
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{6921_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.176425501704216"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.176425501704216
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.176425501704216
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.176425501704216
{6905_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19882367551326752"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19882367551326752
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19882367551326752
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19882367551326752
{6922_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.34928108751773834"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.34928108751773834
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34928108751773834
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34928108751773834
{6906_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38035444915294647"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.38035444915294647
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38035444915294647
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38035444915294647
{6923_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5419409722089767"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5419409722089767
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5419409722089767
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5419409722089767
{6907_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5835831016302109"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5835831016302109
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5835831016302109
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5835831016302109
{6937_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7337594032287598"
{6943_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7337594032287598
{6924_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.768811509013176"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.768811509013176
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.768811509013176
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.768811509013176
{6908_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7968129366636276"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7968129366636276
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7968129366636276
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7968129366636276
{6925_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9370061457157135"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9370061457157135
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9370061457157135
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9370061457157135
{6909_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0015053898096085"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0015053898096085
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.0015053898096085
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.0015053898096085
{6926_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1696112602949142"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1696112602949142
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1696112602949142
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1696112602949142
{6910_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2097638547420502"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2097638547420502
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2097638547420502
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2097638547420502
{6943_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2288209795951843"
{6943_start} <-> {6943_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml