
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{30653_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18632161617279053"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18632161617279053
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18632161617279053
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18632161617279053
{30638_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18886497616767883"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18886497616767883
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18886497616767883
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18886497616767883
{30654_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3761938065290451"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3761938065290451
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3761938065290451
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3761938065290451
{30639_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4046694189310074"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4046694189310074
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4046694189310074
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4046694189310074
{30655_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5640767961740494"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5640767961740494
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5640767961740494
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5640767961740494
{30640_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6033750176429749"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6033750176429749
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6033750176429749
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6033750176429749
{30656_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.78099225461483"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.78099225461483
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.78099225461483
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.78099225461483
{30641_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7811628729104996"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7811628729104996
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7811628729104996
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7811628729104996
{30642_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9479383230209351"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9479383230209351
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9479383230209351
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9479383230209351
{30657_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9894132763147354"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9894132763147354
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9894132763147354
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9894132763147354
{30643_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1977044641971588"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.1977044641971588
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1977044641971588
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1977044641971588
{30658_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2049790173768997"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.2049790173768997
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2049790173768997
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2049790173768997
{30669_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.3874610662460327"
{30679_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.3874610662460327
{30659_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4141189008951187"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.4141189008951187
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4141189008951187
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4141189008951187
{30644_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4201650768518448"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4201650768518448
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4201650768518448
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4201650768518448
{30670_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5494713485240936"
{30671_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.574733255431056"
{30660_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6074380725622177"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6074380725622177
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6074380725622177
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6074380725622177
{30645_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.6229167729616165"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6229167729616165
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.6229167729616165
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.6229167729616165
{30661_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.787691906094551"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.787691906094551
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.787691906094551
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.787691906094551
{30646_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.8559879809617996"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.8559879809617996
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.8559879809617996
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.8559879809617996
{30672_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.864670841023326"
{30673_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.874387290328741"
{30674_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.9104759506881237"
{30679_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.9898661375045776"
{30679_start} <-> {30679_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml