
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{40915_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1941908299922943"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1941908299922943
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1941908299922943
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1941908299922943
{40900_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21106305718421936"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21106305718421936
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21106305718421936
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21106305718421936
{40901_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4110688418149948"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4110688418149948
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4110688418149948
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4110688418149948
{40916_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4370149075984955"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4370149075984955
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4370149075984955
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4370149075984955
{40902_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6334574818611145"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6334574818611145
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6334574818611145
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6334574818611145
{40917_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6570898145437241"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6570898145437241
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6570898145437241
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6570898145437241
{40903_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.826124981045723"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.826124981045723
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.826124981045723
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.826124981045723
{40918_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8448745757341385"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8448745757341385
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8448745757341385
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8448745757341385
{40930_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9754630923271179"
{40939_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9754630923271179
{40904_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0206572115421295"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0206572115421295
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0206572115421295
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0206572115421295
{40919_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0857677310705185"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0857677310705185
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.0857677310705185
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.0857677310705185
{40905_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2270550727844238"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2270550727844238
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2270550727844238
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2270550727844238
{40920_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2848231345415115"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2848231345415115
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2848231345415115
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2848231345415115
{40931_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.332903116941452"
{40906_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4303714483976364"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.4303714483976364
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4303714483976364
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4303714483976364
{40939_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.4793469309806824"
{40939_start} <-> {40939_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml