
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8484_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18200722336769104"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18200722336769104
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18200722336769104
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18200722336769104
{8469_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19343173503875732"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19343173503875732
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19343173503875732
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19343173503875732
{8485_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.367220863699913"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.367220863699913
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.367220863699913
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.367220863699913
{8470_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3926076591014862"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3926076591014862
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3926076591014862
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3926076591014862
{8486_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5513083785772324"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5513083785772324
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5513083785772324
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5513083785772324
{8471_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5996400266885757"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5996400266885757
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5996400266885757
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5996400266885757
{8472_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7526302486658096"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7526302486658096
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7526302486658096
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7526302486658096
{8487_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7541092485189438"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7541092485189438
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7541092485189438
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7541092485189438
{8500_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8197508454322815"
{8506_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.8197508454322815
{8488_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9574730545282364"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9574730545282364
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9574730545282364
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9574730545282364
{8473_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9582495391368866"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9582495391368866
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9582495391368866
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9582495391368866
{8501_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9853988140821457"
{8489_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1204399913549423"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1204399913549423
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1204399913549423
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1204399913549423
{8474_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1497118771076202"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1497118771076202
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1497118771076202
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1497118771076202
{8490_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3048361986875534"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3048361986875534
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3048361986875534
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3048361986875534
{8475_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3626565635204315"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3626565635204315
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3626565635204315
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3626565635204315
{8506_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.3893969655036926"
{8506_start} <-> {8506_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml