
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41701_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21180972456932068"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21180972456932068
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21180972456932068
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21180972456932068
{41716_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2261393964290619"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2261393964290619
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2261393964290619
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2261393964290619
{41732_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.370527058839798"
{41748_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.370527058839798
{41702_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42117930948734283"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42117930948734283
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42117930948734283
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42117930948734283
{41717_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4518078863620758"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4518078863620758
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4518078863620758
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4518078863620758
{41703_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6052860617637634"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6052860617637634
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6052860617637634
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6052860617637634
{41718_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6569628268480301"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6569628268480301
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6569628268480301
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6569628268480301
{41704_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7841190248727798"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7841190248727798
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7841190248727798
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7841190248727798
{41733_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8230651021003723"
{41719_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8287782818078995"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8287782818078995
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8287782818078995
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8287782818078995
{41748_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9727406203746796"
{41748_start} <-> {41748_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml