
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38001_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21643222868442535"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21643222868442535
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21643222868442535
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21643222868442535
{37985_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2190706431865692"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2190706431865692
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2190706431865692
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2190706431865692
{37986_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3953716307878494"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3953716307878494
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3953716307878494
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3953716307878494
{38002_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42728592455387115"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.42728592455387115
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42728592455387115
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42728592455387115
{37987_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.574074923992157"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.574074923992157
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.574074923992157
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.574074923992157
{38003_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6058619618415833"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6058619618415833
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6058619618415833
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6058619618415833
{38016_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6113298535346985"
{38032_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6113298535346985
{38017_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7213235199451447"
{38018_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7973497435450554"
{38004_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.800879493355751"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.800879493355751
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.800879493355751
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.800879493355751
{37988_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8039281815290451"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8039281815290451
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8039281815290451
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8039281815290451
{38005_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9946424067020416"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9946424067020416
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9946424067020416
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9946424067020416
{37989_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0068923234939575"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0068923234939575
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.0068923234939575
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.0068923234939575
{38019_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1170316562056541"
{38020_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1212213202379644"
{38032_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.190225064754486"
{38032_start} <-> {38032_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml