
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29642_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18280135095119476"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18280135095119476
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18280135095119476
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18280135095119476
{29658_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20165026187896729"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20165026187896729
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20165026187896729
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20165026187896729
{29643_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38741399347782135"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38741399347782135
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38741399347782135
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38741399347782135
{29659_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.394960418343544"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.394960418343544
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.394960418343544
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.394960418343544
{29644_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5942218899726868"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5942218899726868
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5942218899726868
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5942218899726868
{29660_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6127395033836365"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6127395033836365
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6127395033836365
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6127395033836365
{29673_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6739251613616943"
{29683_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6739251613616943
{29645_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7823494076728821"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7823494076728821
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7823494076728821
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7823494076728821
{29661_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7828541696071625"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7828541696071625
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7828541696071625
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7828541696071625
{29674_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9252417385578156"
{29675_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9604262746870518"
{29646_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9771036207675934"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9771036207675934
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9771036207675934
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9771036207675934
{29662_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9832842200994492"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9832842200994492
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9832842200994492
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9832842200994492
{29683_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1095888018608093"
{29683_start} <-> {29683_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml