
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3836_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15681540966033936"
{3847_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.15681540966033936
{3821_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19817101955413818"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19817101955413818
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19817101955413818
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19817101955413818
{3805_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21154463291168213"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21154463291168213
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21154463291168213
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21154463291168213
{3837_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.27426353096961975"
{3838_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.28491762559860945"
{3839_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2973384000360966"
{3840_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3812721185386181"
{3822_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40208807587623596"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40208807587623596
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40208807587623596
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40208807587623596
{3806_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42081815004348755"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42081815004348755
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42081815004348755
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42081815004348755
{3841_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.431740365922451"
{3823_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6042296439409256"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6042296439409256
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6042296439409256
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6042296439409256
{3807_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6252803355455399"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6252803355455399
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6252803355455399
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6252803355455399
{3847_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6606160402297974"
{3847_start} <-> {3847_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml