
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{960_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.011680897325277328"
{969_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.011680897325277328
{945_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1784079372882843"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1784079372882843
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1784079372882843
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1784079372882843
{961_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18965835496783257"
{930_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.203875333070755"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.203875333070755
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.203875333070755
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.203875333070755
{946_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3684244006872177"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3684244006872177
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3684244006872177
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3684244006872177
{969_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.38665687665343285"
{969_start} <-> {969_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml