
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18595_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19134917855262756"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19134917855262756
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19134917855262756
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19134917855262756
{18579_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21029506623744965"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21029506623744965
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21029506623744965
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21029506623744965
{18596_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3982721120119095"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3982721120119095
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3982721120119095
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3982721120119095
{18580_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4213947057723999"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4213947057723999
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4213947057723999
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4213947057723999
{18597_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5800541788339615"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5800541788339615
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5800541788339615
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5800541788339615
{18581_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6053303778171539"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6053303778171539
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6053303778171539
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6053303778171539
{18598_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7974642217159271"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7974642217159271
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7974642217159271
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7974642217159271
{18582_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8410083055496216"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8410083055496216
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8410083055496216
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8410083055496216
{18599_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9724759310483932"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9724759310483932
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9724759310483932
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9724759310483932
{18583_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9962324500083923"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9962324500083923
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9962324500083923
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9962324500083923
{18600_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1451334357261658"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.1451334357261658
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1451334357261658
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1451334357261658
{18584_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.174606055021286"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.174606055021286
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.174606055021286
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.174606055021286
{18610_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2396490573883057"
{18618_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.2396490573883057
{18601_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3396042436361313"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3396042436361313
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3396042436361313
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3396042436361313
{18585_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3489443510770798"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3489443510770798
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3489443510770798
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3489443510770798
{18611_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5185264647006989"
{18586_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.5701917111873627"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.5701917111873627
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.5701917111873627
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.5701917111873627
{18602_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.5735361278057098"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.5735361278057098
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.5735361278057098
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.5735361278057098
{18612_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5923819169402122"
{18618_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.6633118689060211"
{18618_start} <-> {18618_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml