
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35301_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2100553661584854"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2100553661584854
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2100553661584854
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2100553661584854
{35286_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21542201936244965"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21542201936244965
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21542201936244965
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21542201936244965
{35287_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.407867968082428"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.407867968082428
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.407867968082428
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.407867968082428
{35302_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4249601811170578"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4249601811170578
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4249601811170578
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4249601811170578
{35288_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5798332840204239"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5798332840204239
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5798332840204239
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5798332840204239
{35303_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6197117120027542"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6197117120027542
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6197117120027542
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6197117120027542
{35289_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7720272392034531"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7720272392034531
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7720272392034531
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7720272392034531
{35304_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8304405063390732"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8304405063390732
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8304405063390732
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8304405063390732
{35290_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9420272260904312"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9420272260904312
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9420272260904312
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9420272260904312
{35316_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9576390385627747"
{35322_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9576390385627747
{35305_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0081513226032257"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0081513226032257
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0081513226032257
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0081513226032257
{35291_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1597318798303604"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1597318798303604
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1597318798303604
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1597318798303604
{35306_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1962292790412903"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1962292790412903
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.1962292790412903
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.1962292790412903
{35292_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.371682271361351"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.371682271361351
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.371682271361351
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.371682271361351
{35322_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.424778401851654"
{35322_start} <-> {35322_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml