
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13266_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1810675412416458"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1810675412416458
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1810675412416458
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1810675412416458
{13251_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19941911101341248"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19941911101341248
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19941911101341248
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19941911101341248
{13281_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2418614625930786"
{13293_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2418614625930786
{13252_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39035530388355255"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39035530388355255
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39035530388355255
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39035530388355255
{13267_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.416742205619812"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.416742205619812
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.416742205619812
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.416742205619812
{13282_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4539042264223099"
{13253_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6067906022071838"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6067906022071838
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6067906022071838
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6067906022071838
{13268_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6244615763425827"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6244615763425827
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6244615763425827
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6244615763425827
{13283_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7405218333005905"
{13254_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7779930830001831"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7779930830001831
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7779930830001831
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7779930830001831
{13269_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8367910534143448"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8367910534143448
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8367910534143448
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8367910534143448
{13284_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.857523150742054"
{13255_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9961578547954559"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9961578547954559
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9961578547954559
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9961578547954559
{13293_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.006697416305542"
{13293_start} <-> {13293_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml