
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3626_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.020786741748452187"
{3638_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.020786741748452187
{3627_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.058624641969799995"
{3628_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.16150290705263615"
{3610_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20315596461296082"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20315596461296082
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20315596461296082
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20315596461296082
{3595_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21319378912448883"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21319378912448883
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21319378912448883
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21319378912448883
{3629_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.38294326700270176"
{3611_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39603377878665924"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39603377878665924
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39603377878665924
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39603377878665924
{3596_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43507273495197296"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.43507273495197296
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43507273495197296
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43507273495197296
{3638_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5927271042019129"
{3638_start} <-> {3638_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml