
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17837_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.04182567819952965"
{17846_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.04182567819952965
{17821_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16670985519886017"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.16670985519886017
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16670985519886017
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16670985519886017
{17805_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18498525023460388"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18498525023460388
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18498525023460388
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18498525023460388
{17838_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21820267662405968"
{17806_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3515200614929199"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3515200614929199
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3515200614929199
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3515200614929199
{17822_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.377313494682312"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.377313494682312
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.377313494682312
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.377313494682312
{17846_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.41805165633559227"
{17846_start} <-> {17846_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml