
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15921_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19843736290931702"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19843736290931702
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19843736290931702
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19843736290931702
{15952_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2102280706167221"
{15967_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2102280706167221
{15937_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21891161799430847"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21891161799430847
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21891161799430847
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21891161799430847
{15953_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.22161382157355547"
{15922_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3896771967411041"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3896771967411041
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3896771967411041
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3896771967411041
{15938_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4165436774492264"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4165436774492264
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4165436774492264
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4165436774492264
{15954_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4800106259062886"
{15967_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.531756266951561"
{15967_start} <-> {15967_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml