
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11993_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.170516699552536"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.170516699552536
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.170516699552536
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.170516699552536
{12009_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.201309472322464"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.201309472322464
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.201309472322464
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.201309472322464
{12010_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37269720435142517"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.37269720435142517
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37269720435142517
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37269720435142517
{11994_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3875361979007721"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3875361979007721
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3875361979007721
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3875361979007721
{12025_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.40657687187194824"
{12031_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.40657687187194824
{12026_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4778095558285713"
{11995_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5708404332399368"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5708404332399368
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5708404332399368
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5708404332399368
{12011_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5768566131591797"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5768566131591797
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5768566131591797
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5768566131591797
{12027_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.62822475284338"
{11996_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.747528076171875"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.747528076171875
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.747528076171875
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.747528076171875
{12012_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7780322581529617"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7780322581529617
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7780322581529617
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7780322581529617
{12028_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8647769168019295"
{12031_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9241877198219299"
{12031_start} <-> {12031_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml