
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{12245_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18105365335941315"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18105365335941315
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18105365335941315
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18105365335941315
{12229_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1928059160709381"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1928059160709381
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1928059160709381
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1928059160709381
{12260_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2757636606693268"
{12270_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2757636606693268
{12246_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3957584798336029"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3957584798336029
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3957584798336029
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3957584798336029
{12230_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39844200015068054"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39844200015068054
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39844200015068054
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39844200015068054
{12231_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5690884441137314"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5690884441137314
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5690884441137314
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5690884441137314
{12247_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.581293985247612"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.581293985247612
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.581293985247612
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.581293985247612
{12270_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6180890500545502"
{12270_start} <-> {12270_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml