
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{26288_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18038618564605713"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18038618564605713
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18038618564605713
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18038618564605713
{26273_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1964176893234253"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1964176893234253
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.1964176893234253
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.1964176893234253
{26289_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.378922700881958"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.378922700881958
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.378922700881958
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.378922700881958
{26274_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42247456312179565"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.42247456312179565
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42247456312179565
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42247456312179565
{26304_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5537275671958923"
{26315_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5537275671958923
{26290_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5566285401582718"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5566285401582718
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5566285401582718
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5566285401582718
{26275_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6343345940113068"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6343345940113068
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6343345940113068
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6343345940113068
{26291_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.749060645699501"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.749060645699501
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.749060645699501
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.749060645699501
{26276_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8332701325416565"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8332701325416565
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8332701325416565
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8332701325416565
{26305_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9123759567737579"
{26292_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9275236278772354"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9275236278772354
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.9275236278772354
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.9275236278772354
{26315_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.998045027256012"
{26315_start} <-> {26315_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml