
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22972_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1658126264810562"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1658126264810562
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1658126264810562
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1658126264810562
{22987_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17924778163433075"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17924778163433075
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17924778163433075
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17924778163433075
{23003_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18568460643291473"
{23012_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.18568460643291473
{22988_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3405672609806061"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3405672609806061
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3405672609806061
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3405672609806061
{22973_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3969711512327194"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3969711512327194
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3969711512327194
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3969711512327194
{22989_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5695140063762665"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5695140063762665
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5695140063762665
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5695140063762665
{22974_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6214853674173355"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6214853674173355
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6214853674173355
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6214853674173355
{23012_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6997870653867722"
{23012_start} <-> {23012_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.6997870653867722"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml