
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{40570_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17862901091575623"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17862901091575623
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17862901091575623
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17862901091575623
{40586_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19893679022789001"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19893679022789001
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19893679022789001
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19893679022789001
{40571_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3609923869371414"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3609923869371414
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3609923869371414
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3609923869371414
{40587_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3809715360403061"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3809715360403061
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3809715360403061
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3809715360403061
{40572_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5589806884527206"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5589806884527206
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5589806884527206
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5589806884527206
{40588_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5961133390665054"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5961133390665054
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5961133390665054
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5961133390665054
{40573_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7488757818937302"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7488757818937302
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7488757818937302
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7488757818937302
{40589_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7778704315423965"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7778704315423965
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7778704315423965
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7778704315423965
{40601_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.814993679523468"
{40604_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.814993679523468
{40574_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9518583714962006"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9518583714962006
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9518583714962006
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9518583714962006
{40590_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9859774708747864"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9859774708747864
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9859774708747864
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9859774708747864
{40602_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0261073857545853"
{40575_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1526892930269241"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1526892930269241
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1526892930269241
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1526892930269241
{40604_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2082234025001526"
{40604_start} <-> {40604_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml