
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{20019_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0815482959151268"
{20030_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.0815482959151268
{20004_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18790201842784882"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18790201842784882
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18790201842784882
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18790201842784882
{19989_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2091820389032364"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2091820389032364
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2091820389032364
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2091820389032364
{20020_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.31942179054021835"
{20005_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40405145287513733"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40405145287513733
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40405145287513733
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40405145287513733
{19990_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41951654851436615"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41951654851436615
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.41951654851436615
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.41951654851436615
{20030_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4465414509177208"
{20030_start} <-> {20030_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.4465414509177208"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml