
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15091_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18196211755275726"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18196211755275726
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18196211755275726
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18196211755275726
{15107_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19011655449867249"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19011655449867249
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19011655449867249
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19011655449867249
{15123_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2967541515827179"
{15131_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2967541515827179
{15092_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3502831906080246"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3502831906080246
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3502831906080246
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3502831906080246
{15108_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.407159224152565"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.407159224152565
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.407159224152565
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.407159224152565
{15124_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5237947255373001"
{15093_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5418023765087128"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5418023765087128
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5418023765087128
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5418023765087128
{15109_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5743898153305054"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5743898153305054
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5743898153305054
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5743898153305054
{15110_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.76700060069561"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.76700060069561
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.76700060069561
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.76700060069561
{15094_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.777541846036911"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.777541846036911
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.777541846036911
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.777541846036911
{15131_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8056708872318268"
{15131_start} <-> {15131_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml