
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23317_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1968238353729248"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1968238353729248
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1968238353729248
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1968238353729248
{23302_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2012857049703598"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2012857049703598
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2012857049703598
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2012857049703598
{23318_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41582779586315155"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41582779586315155
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41582779586315155
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41582779586315155
{23303_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4309946149587631"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4309946149587631
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4309946149587631
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4309946149587631
{23331_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4601370096206665"
{23343_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4601370096206665
{23304_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.610603466629982"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.610603466629982
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.610603466629982
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.610603466629982
{23319_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6478280425071716"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6478280425071716
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6478280425071716
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6478280425071716
{23305_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8639532178640366"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8639532178640366
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8639532178640366
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8639532178640366
{23320_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8857671469449997"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8857671469449997
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8857671469449997
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8857671469449997
{23343_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9120371341705322"
{23343_start} <-> {23343_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml