
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11276_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15220089256763458"
{11288_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.15220089256763458
{11260_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18597321212291718"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18597321212291718
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18597321212291718
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18597321212291718
{11244_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.24156689643859863"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.24156689643859863
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24156689643859863
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24156689643859863
{11261_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40034031867980957"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40034031867980957
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40034031867980957
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40034031867980957
{11245_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.46156109869480133"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.46156109869480133
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.46156109869480133
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.46156109869480133
{11277_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5704164355993271"
{11278_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6277591735124588"
{11246_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6381489187479019"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6381489187479019
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6381489187479019
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6381489187479019
{11262_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6498582512140274"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6498582512140274
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6498582512140274
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6498582512140274
{11288_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6896705776453018"
{11288_start} <-> {11288_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml