
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13152_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.05728834494948387"
{13164_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.05728834494948387
{13153_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15369656309485435"
{13136_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20892491936683655"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20892491936683655
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20892491936683655
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20892491936683655
{13121_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21809688210487366"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21809688210487366
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21809688210487366
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21809688210487366
{13137_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4006282836198807"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4006282836198807
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4006282836198807
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4006282836198807
{13122_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4404356777667999"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4404356777667999
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4404356777667999
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4404356777667999
{13138_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.588493138551712"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.588493138551712
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.588493138551712
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.588493138551712
{13164_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6190557442605495"
{13164_start} <-> {13164_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml