
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33036_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.02434331364929676"
{33045_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.02434331364929676
{33006_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19249656796455383"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19249656796455383
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.19249656796455383
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.19249656796455383
{33021_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19628265500068665"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19628265500068665
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19628265500068665
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19628265500068665
{33007_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37922629714012146"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.37922629714012146
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37922629714012146
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37922629714012146
{33022_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40202346444129944"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40202346444129944
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40202346444129944
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40202346444129944
{33045_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4424798507243395"
{33045_start} <-> {33045_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.4424798507243395"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml