
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35037_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.007108225021511316"
{35047_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.007108225021511316
{35038_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.16569666424766183"
{35022_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.168402761220932"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.168402761220932
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.168402761220932
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.168402761220932
{35006_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1970757246017456"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1970757246017456
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1970757246017456
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1970757246017456
{35023_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.31798556447029114"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.31798556447029114
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.31798556447029114
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.31798556447029114
{35039_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.34348553279414773"
{35040_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3847620435990393"
{35007_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39549481868743896"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39549481868743896
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39549481868743896
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39549481868743896
{35024_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5482946187257767"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5482946187257767
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5482946187257767
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5482946187257767
{35008_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5983617454767227"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5983617454767227
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5983617454767227
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5983617454767227
{35047_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6640996471978724"
{35047_start} <-> {35047_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml