
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28830_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.14684493839740753"
{28841_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.14684493839740753
{28815_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18758167326450348"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18758167326450348
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18758167326450348
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18758167326450348
{28831_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21135138720273972"
{28799_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2144913673400879"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2144913673400879
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2144913673400879
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2144913673400879
{28816_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.34326261281967163"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.34326261281967163
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34326261281967163
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34326261281967163
{28800_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3834398686885834"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3834398686885834
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3834398686885834
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3834398686885834
{28801_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5609621405601501"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5609621405601501
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5609621405601501
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5609621405601501
{28817_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5749322921037674"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5749322921037674
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5749322921037674
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5749322921037674
{28841_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5969058126211166"
{28841_start} <-> {28841_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml