
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10115_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.060085371136665344"
{10124_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.060085371136665344
{10099_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1728530079126358"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1728530079126358
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1728530079126358
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1728530079126358
{10084_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23035649955272675"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.23035649955272675
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23035649955272675
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23035649955272675
{10100_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3963511139154434"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3963511139154434
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3963511139154434
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3963511139154434
{10085_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40647223591804504"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40647223591804504
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40647223591804504
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40647223591804504
{10124_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5168562978506088"
{10124_start} <-> {10124_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml