
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23756_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.19462771713733673"
{23764_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.19462771713733673
{23741_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21554313600063324"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21554313600063324
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21554313600063324
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21554313600063324
{23726_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22286053001880646"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22286053001880646
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22286053001880646
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22286053001880646
{23727_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4285837411880493"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4285837411880493
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4285837411880493
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4285837411880493
{23742_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4389830380678177"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4389830380678177
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4389830380678177
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4389830380678177
{23728_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6461290270090103"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6461290270090103
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6461290270090103
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6461290270090103
{23743_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6698970198631287"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6698970198631287
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6698970198631287
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6698970198631287
{23764_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7587224394083023"
{23764_start} <-> {23764_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml