
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2654_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0022346610203385353"
{2663_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.0022346610203385353
{2638_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1909121721982956"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1909121721982956
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1909121721982956
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1909121721982956
{2623_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20498031377792358"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20498031377792358
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20498031377792358
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20498031377792358
{2639_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.35728634893894196"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.35728634893894196
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35728634893894196
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35728634893894196
{2624_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4310128539800644"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4310128539800644
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4310128539800644
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4310128539800644
{2640_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5604464709758759"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5604464709758759
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5604464709758759
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5604464709758759
{2663_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6091056102886796"
{2663_start} <-> {2663_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml