
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31170_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2045094221830368"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2045094221830368
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2045094221830368
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2045094221830368
{31186_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21107308566570282"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21107308566570282
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21107308566570282
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21107308566570282
{31187_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4123155027627945"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4123155027627945
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4123155027627945
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4123155027627945
{31171_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43366341292858124"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.43366341292858124
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43366341292858124
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43366341292858124
{31201_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6168616414070129"
{31208_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6168616414070129
{31188_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6352803111076355"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6352803111076355
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6352803111076355
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6352803111076355
{31172_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6456965059041977"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6456965059041977
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6456965059041977
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6456965059041977
{31189_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7990205883979797"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7990205883979797
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7990205883979797
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7990205883979797
{31173_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.837684378027916"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.837684378027916
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.837684378027916
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.837684378027916
{31190_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9826174080371857"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9826174080371857
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9826174080371857
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9826174080371857
{31174_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0366867780685425"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0366867780685425
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0366867780685425
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0366867780685425
{31202_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1510545015335083"
{31191_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1842596530914307"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1842596530914307
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1842596530914307
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1842596530914307
{31208_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1951544284820557"
{31208_start} <-> {31208_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml