
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27779_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.13589617609977722"
{27787_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.13589617609977722
{27763_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21723169088363647"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21723169088363647
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21723169088363647
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21723169088363647
{27747_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22431138157844543"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22431138157844543
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22431138157844543
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22431138157844543
{27764_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4082489609718323"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4082489609718323
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4082489609718323
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4082489609718323
{27748_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42200492322444916"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42200492322444916
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42200492322444916
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42200492322444916
{27765_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.603898748755455"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.603898748755455
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.603898748755455
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.603898748755455
{27749_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6318590342998505"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6318590342998505
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6318590342998505
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6318590342998505
{27787_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7060010731220245"
{27787_start} <-> {27787_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml