
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41780_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.03865029662847519"
{41794_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.03865029662847519
{41781_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.05848664604127407"
{41749_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19375593960285187"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19375593960285187
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19375593960285187
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19375593960285187
{41765_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20640020072460175"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20640020072460175
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20640020072460175
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20640020072460175
{41750_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36825285851955414"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.36825285851955414
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36825285851955414
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36825285851955414
{41766_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42345544695854187"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42345544695854187
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42345544695854187
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42345544695854187
{41751_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5588774234056473"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5588774234056473
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5588774234056473
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5588774234056473
{41782_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5845793541520834"
{41767_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5877519100904465"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5877519100904465
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5877519100904465
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5877519100904465
{41794_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6201758608222008"
{41794_start} <-> {41794_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml