
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4085_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.01646687090396881"
{4096_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.01646687090396881
{4086_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.027513619512319565"
{4055_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20852960646152496"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20852960646152496
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20852960646152496
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20852960646152496
{4070_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2376372516155243"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2376372516155243
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2376372516155243
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2376372516155243
{4087_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3406631015241146"
{4056_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.408513143658638"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.408513143658638
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.408513143658638
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.408513143658638
{4071_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.44889912009239197"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.44889912009239197
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.44889912009239197
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.44889912009239197
{4096_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5225044637918472"
{4096_start} <-> {4096_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml