
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27659_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22068046033382416"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.22068046033382416
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22068046033382416
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22068046033382416
{27674_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22209271788597107"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22209271788597107
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22209271788597107
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22209271788597107
{27660_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42724068462848663"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.42724068462848663
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42724068462848663
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42724068462848663
{27675_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42724592983722687"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.42724592983722687
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42724592983722687
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42724592983722687
{27689_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5775951743125916"
{27700_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5775951743125916
{27661_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6473940461874008"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6473940461874008
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6473940461874008
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6473940461874008
{27676_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6476959735155106"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6476959735155106
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6476959735155106
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6476959735155106
{27690_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7259438633918762"
{27691_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8306319490075111"
{27662_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8416852951049805"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8416852951049805
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8416852951049805
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8416852951049805
{27677_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8516559600830078"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8516559600830078
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8516559600830078
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8516559600830078
{27663_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0200486779212952"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0200486779212952
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0200486779212952
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0200486779212952
{27700_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0236422717571259"
{27700_start} <-> {27700_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml