
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17150_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2018444538116455"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2018444538116455
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2018444538116455
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2018444538116455
{17135_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20204980671405792"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20204980671405792
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20204980671405792
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20204980671405792
{17151_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3889535367488861"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3889535367488861
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3889535367488861
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3889535367488861
{17136_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.410913422703743"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.410913422703743
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.410913422703743
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.410913422703743
{17152_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5971841067075729"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5971841067075729
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5971841067075729
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5971841067075729
{17137_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6175616085529327"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6175616085529327
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6175616085529327
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6175616085529327
{17153_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8135578334331512"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8135578334331512
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8135578334331512
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8135578334331512
{17138_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8230405002832413"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8230405002832413
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8230405002832413
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8230405002832413
{17165_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8437666296958923"
{17172_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.8437666296958923
{17166_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9311461225152016"
{17154_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0190745294094086"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0190745294094086
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0190745294094086
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0190745294094086
{17139_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0560522675514221"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0560522675514221
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0560522675514221
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0560522675514221
{17155_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2182939797639847"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2182939797639847
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2182939797639847
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2182939797639847
{17140_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2736477553844452"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2736477553844452
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2736477553844452
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2736477553844452
{17167_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.3846712186932564"
{17172_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.395995557308197"
{17172_start} <-> {17172_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml