
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10702_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1704004555940628"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1704004555940628
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1704004555940628
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1704004555940628
{10718_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21353116631507874"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21353116631507874
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21353116631507874
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21353116631507874
{10703_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3439025729894638"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3439025729894638
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3439025729894638
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3439025729894638
{10719_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41462695598602295"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.41462695598602295
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41462695598602295
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41462695598602295
{10704_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5356742292642593"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5356742292642593
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5356742292642593
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5356742292642593
{10720_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6423733681440353"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6423733681440353
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6423733681440353
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6423733681440353
{10734_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6618451476097107"
{10745_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6618451476097107
{10705_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7159876078367233"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7159876078367233
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7159876078367233
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7159876078367233
{10735_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8097508102655411"
{10721_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8194642663002014"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8194642663002014
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8194642663002014
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8194642663002014
{10706_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9180405288934708"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9180405288934708
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9180405288934708
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9180405288934708
{10722_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0402931421995163"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0402931421995163
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0402931421995163
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0402931421995163
{10736_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.086937054991722"
{10707_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1130310595035553"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1130310595035553
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1130310595035553
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1130310595035553
{10745_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.142782211303711"
{10745_start} <-> {10745_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml