
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13457_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.14545390009880066"
{13469_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.14545390009880066
{13442_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1927749067544937"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1927749067544937
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1927749067544937
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1927749067544937
{13426_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1961371749639511"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1961371749639511
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.1961371749639511
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.1961371749639511
{13458_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2701462209224701"
{13427_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3693291246891022"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3693291246891022
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3693291246891022
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3693291246891022
{13443_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4177868962287903"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4177868962287903
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4177868962287903
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4177868962287903
{13428_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.54495570063591"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.54495570063591
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.54495570063591
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.54495570063591
{13459_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5999182760715485"
{13444_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.615141823887825"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.615141823887825
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.615141823887825
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.615141823887825
{13460_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6182637792080641"
{13429_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7399455904960632"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7399455904960632
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7399455904960632
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7399455904960632
{13469_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7476607263088226"
{13469_start} <-> {13469_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml