
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29858_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18161341547966003"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18161341547966003
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18161341547966003
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18161341547966003
{29842_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21483007073402405"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21483007073402405
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21483007073402405
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21483007073402405
{29859_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42026805877685547"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.42026805877685547
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42026805877685547
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42026805877685547
{29843_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4232839047908783"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4232839047908783
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4232839047908783
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4232839047908783
{29844_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6057558208703995"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6057558208703995
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6057558208703995
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6057558208703995
{29860_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6289853751659393"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6289853751659393
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6289853751659393
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6289853751659393
{29845_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8090730309486389"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8090730309486389
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8090730309486389
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8090730309486389
{29861_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8311113715171814"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8311113715171814
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8311113715171814
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8311113715171814
{29846_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0286610573530197"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.0286610573530197
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0286610573530197
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0286610573530197
{29862_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.040595903992653"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.040595903992653
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.040595903992653
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.040595903992653
{29874_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0794869661331177"
{29883_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.0794869661331177
{29847_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2196835577487946"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2196835577487946
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2196835577487946
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2196835577487946
{29863_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2399124652147293"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2399124652147293
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2399124652147293
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2399124652147293
{29875_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2505192011594772"
{29848_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3934931457042694"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3934931457042694
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3934931457042694
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3934931457042694
{29864_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3955169469118118"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3955169469118118
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3955169469118118
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3955169469118118
{29876_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5414838939905167"
{29849_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.5887355655431747"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.5887355655431747
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.5887355655431747
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.5887355655431747
{29865_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6028051674365997"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6028051674365997
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.6028051674365997
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.6028051674365997
{29883_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.620432436466217"
{29883_start} <-> {29883_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml