
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17711_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11778578162193298"
{17721_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.11778578162193298
{17695_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1892857551574707"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1892857551574707
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1892857551574707
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1892857551574707
{17679_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21624086797237396"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21624086797237396
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21624086797237396
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21624086797237396
{17712_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3034531772136688"
{17696_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3939781188964844"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3939781188964844
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3939781188964844
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3939781188964844
{17680_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.44190147519111633"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44190147519111633
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44190147519111633
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44190147519111633
{17697_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6179869472980499"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6179869472980499
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6179869472980499
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6179869472980499
{17713_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.61912602186203"
{17681_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6562837660312653"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6562837660312653
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6562837660312653
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6562837660312653
{17698_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7830424606800079"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7830424606800079
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7830424606800079
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7830424606800079
{17721_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8129700124263763"
{17721_start} <-> {17721_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml