
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2367_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08961111307144165"
{2373_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08961111307144165
{2336_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19704163074493408"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19704163074493408
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19704163074493408
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19704163074493408
{2352_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20751745998859406"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20751745998859406
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20751745998859406
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20751745998859406
{2368_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.25562359392642975"
{2353_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38217951357364655"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38217951357364655
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38217951357364655
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38217951357364655
{2337_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41380801796913147"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41380801796913147
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41380801796913147
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41380801796913147
{2354_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5947255045175552"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5947255045175552
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5947255045175552
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5947255045175552
{2338_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6358838379383087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6358838379383087
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6358838379383087
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6358838379383087
{2373_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6819590926170349"
{2373_start} <-> {2373_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml