
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34702_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.029571637511253357"
{34710_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.029571637511253357
{34672_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18335162103176117"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18335162103176117
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18335162103176117
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18335162103176117
{34703_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18710848689079285"
{34687_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21263298392295837"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21263298392295837
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21263298392295837
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21263298392295837
{34704_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.26166174560785294"
{34673_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3714383840560913"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3714383840560913
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3714383840560913
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3714383840560913
{34705_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.39286062866449356"
{34688_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43766528367996216"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.43766528367996216
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43766528367996216
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43766528367996216
{34706_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.519720159471035"
{34710_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5822858065366745"
{34710_start} <-> {34710_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml