
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{5258_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1896844208240509"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1896844208240509
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1896844208240509
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1896844208240509
{5243_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21990206837654114"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21990206837654114
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21990206837654114
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21990206837654114
{5259_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37386323511600494"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.37386323511600494
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37386323511600494
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37386323511600494
{5244_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4411635547876358"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4411635547876358
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4411635547876358
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4411635547876358
{5260_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6135987490415573"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6135987490415573
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6135987490415573
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6135987490415573
{5273_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6138507723808289"
{5284_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6138507723808289
{5245_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6390479356050491"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6390479356050491
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6390479356050491
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6390479356050491
{5274_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8174214512109756"
{5246_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8196487426757812"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8196487426757812
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8196487426757812
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8196487426757812
{5261_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8427608907222748"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8427608907222748
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8427608907222748
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8427608907222748
{5247_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.007171019911766"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.007171019911766
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.007171019911766
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.007171019911766
{5262_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.073944792151451"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.073944792151451
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.073944792151451
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.073944792151451
{5284_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0816418528556824"
{5284_start} <-> {5284_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml