
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35208_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19999109208583832"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19999109208583832
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19999109208583832
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19999109208583832
{35239_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.20714910328388214"
{35244_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.20714910328388214
{35224_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22455385327339172"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22455385327339172
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22455385327339172
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22455385327339172
{35225_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38329651951789856"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38329651951789856
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38329651951789856
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38329651951789856
{35209_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41128064692020416"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41128064692020416
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41128064692020416
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41128064692020416
{35210_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5988999009132385"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5988999009132385
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5988999009132385
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5988999009132385
{35226_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6027861982584"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6027861982584
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6027861982584
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6027861982584
{35227_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.802353173494339"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.802353173494339
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.802353173494339
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.802353173494339
{35244_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8143246322870255"
{35244_start} <-> {35244_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml