
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29699_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2163517028093338"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2163517028093338
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2163517028093338
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2163517028093338
{29684_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22121763229370117"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.22121763229370117
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.22121763229370117
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.22121763229370117
{29714_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.29105713963508606"
{29724_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.29105713963508606
{29685_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42795322835445404"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42795322835445404
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42795322835445404
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42795322835445404
{29700_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4370075762271881"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4370075762271881
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4370075762271881
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4370075762271881
{29715_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.614576518535614"
{29686_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6275438219308853"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6275438219308853
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6275438219308853
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6275438219308853
{29701_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6297049522399902"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6297049522399902
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6297049522399902
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6297049522399902
{29724_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7954905331134796"
{29724_start} <-> {29724_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml