
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{37023_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2086358517408371"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2086358517408371
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2086358517408371
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2086358517408371
{37039_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2099868506193161"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2099868506193161
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2099868506193161
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2099868506193161
{37024_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3733515292406082"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3733515292406082
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3733515292406082
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3733515292406082
{37040_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4327038377523422"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4327038377523422
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4327038377523422
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4327038377523422
{37054_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.44099095463752747"
{37060_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.44099095463752747
{37025_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5884758681058884"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5884758681058884
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5884758681058884
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5884758681058884
{37041_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6175009459257126"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6175009459257126
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6175009459257126
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6175009459257126
{37026_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7942901104688644"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7942901104688644
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7942901104688644
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7942901104688644
{37042_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8374627083539963"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8374627083539963
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8374627083539963
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8374627083539963
{37027_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9963731914758682"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9963731914758682
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9963731914758682
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9963731914758682
{37043_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.026150956749916"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.026150956749916
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.026150956749916
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.026150956749916
{37060_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0335123240947723"
{37060_start} <-> {37060_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml