
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22525_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19256074726581573"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19256074726581573
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19256074726581573
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19256074726581573
{22509_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20126812160015106"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20126812160015106
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20126812160015106
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20126812160015106
{22541_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24771378934383392"
{22556_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24771378934383392
{22542_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.272151842713356"
{22526_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3692895919084549"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3692895919084549
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3692895919084549
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3692895919084549
{22510_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3857681155204773"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3857681155204773
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3857681155204773
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3857681155204773
{22543_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4542049765586853"
{22511_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.58321912586689"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.58321912586689
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.58321912586689
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.58321912586689
{22527_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5850291550159454"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5850291550159454
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5850291550159454
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5850291550159454
{22512_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7802236080169678"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7802236080169678
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7802236080169678
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7802236080169678
{22528_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7856073379516602"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7856073379516602
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7856073379516602
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7856073379516602
{22556_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8370468467473984"
{22556_start} <-> {22556_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml