
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{293_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18215860426425934"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18215860426425934
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18215860426425934
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18215860426425934
{309_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.185806542634964"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.185806542634964
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.185806542634964
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.185806542634964
{325_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.33864328265190125"
{339_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.33864328265190125
{310_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.35424594581127167"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.35424594581127167
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35424594581127167
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35424594581127167
{294_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3667537719011307"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3667537719011307
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3667537719011307
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3667537719011307
{326_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49628373980522156"
{295_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5258430391550064"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5258430391550064
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5258430391550064
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5258430391550064
{311_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5378403812646866"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5378403812646866
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5378403812646866
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5378403812646866
{296_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7101183980703354"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7101183980703354
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7101183980703354
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7101183980703354
{327_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7341430932283401"
{312_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7475752681493759"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7475752681493759
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7475752681493759
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7475752681493759
{339_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8496892750263214"
{339_start} <-> {339_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml