
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{30754_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.031136026605963707"
{30769_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.031136026605963707
{30755_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1336523126810789"
{30723_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21233175694942474"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21233175694942474
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21233175694942474
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21233175694942474
{30739_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21854937076568604"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21854937076568604
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21854937076568604
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21854937076568604
{30769_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.37962990067899227"
{30769_start} <-> {30769_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml