
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33669_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19460010528564453"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19460010528564453
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19460010528564453
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19460010528564453
{33654_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22304537892341614"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22304537892341614
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22304537892341614
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22304537892341614
{33670_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37624259293079376"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.37624259293079376
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.37624259293079376
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.37624259293079376
{33655_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4247591346502304"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4247591346502304
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4247591346502304
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4247591346502304
{33671_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5952600389719009"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5952600389719009
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5952600389719009
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5952600389719009
{33656_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6192274689674377"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6192274689674377
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6192274689674377
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6192274689674377
{33684_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6262710690498352"
{33691_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6262710690498352
{33672_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.787774458527565"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.787774458527565
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.787774458527565
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.787774458527565
{33657_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7982683330774307"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7982683330774307
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7982683330774307
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7982683330774307
{33685_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8237966746091843"
{33686_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8705416657030582"
{33658_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9812570512294769"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9812570512294769
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9812570512294769
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9812570512294769
{33673_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9922707974910736"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9922707974910736
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.9922707974910736
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.9922707974910736
{33687_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1215049661695957"
{33688_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1583555825054646"
{33659_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1761319637298584"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1761319637298584
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1761319637298584
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1761319637298584
{33674_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1854247450828552"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1854247450828552
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1854247450828552
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1854247450828552
{33691_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1890224814414978"
{33691_start} <-> {33691_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml