
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35353_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08548558503389359"
{35366_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08548558503389359
{35338_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19854871928691864"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19854871928691864
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19854871928691864
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19854871928691864
{35323_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2247752547264099"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2247752547264099
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2247752547264099
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2247752547264099
{35354_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24180562049150467"
{35339_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37966373562812805"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.37966373562812805
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.37966373562812805
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.37966373562812805
{35324_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.45036643743515015"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.45036643743515015
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.45036643743515015
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.45036643743515015
{35366_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4934590831398964"
{35366_start} <-> {35366_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml