
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17173_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17090149223804474"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17090149223804474
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17090149223804474
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17090149223804474
{17188_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1784714013338089"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1784714013338089
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1784714013338089
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1784714013338089
{17174_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.33653347194194794"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.33653347194194794
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.33653347194194794
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.33653347194194794
{17203_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4011603593826294"
{17211_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4011603593826294
{17189_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4282880574464798"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4282880574464798
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4282880574464798
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4282880574464798
{17204_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5086391940712929"
{17175_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5324394106864929"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5324394106864929
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5324394106864929
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5324394106864929
{17205_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5525973476469517"
{17190_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5971355587244034"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5971355587244034
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5971355587244034
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5971355587244034
{17176_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7423362135887146"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7423362135887146
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7423362135887146
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7423362135887146
{17191_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7696446627378464"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7696446627378464
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7696446627378464
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7696446627378464
{17211_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.883280485868454"
{17211_start} <-> {17211_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.883280485868454"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml