
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38951_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21672150492668152"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21672150492668152
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21672150492668152
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21672150492668152
{38967_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22284255921840668"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22284255921840668
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22284255921840668
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22284255921840668
{38952_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43342404067516327"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.43342404067516327
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43342404067516327
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43342404067516327
{38968_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4629122167825699"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4629122167825699
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4629122167825699
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4629122167825699
{38953_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6232830435037613"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6232830435037613
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6232830435037613
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6232830435037613
{38969_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6583568602800369"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6583568602800369
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6583568602800369
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6583568602800369
{38954_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8119411766529083"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8119411766529083
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8119411766529083
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8119411766529083
{38970_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8583247810602188"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8583247810602188
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8583247810602188
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8583247810602188
{38955_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0116623938083649"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.0116623938083649
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0116623938083649
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0116623938083649
{38971_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0437812507152557"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.0437812507152557
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0437812507152557
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0437812507152557
{38982_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.161382794380188"
{38989_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.161382794380188
{38956_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2002499103546143"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2002499103546143
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2002499103546143
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2002499103546143
{38983_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2299095839262009"
{38972_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2573213875293732"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2573213875293732
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2573213875293732
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2573213875293732
{38957_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.40028914809227"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.40028914809227
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.40028914809227
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.40028914809227
{38973_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4343036264181137"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4343036264181137
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4343036264181137
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4343036264181137
{38958_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.568509966135025"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.568509966135025
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.568509966135025
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.568509966135025
{38989_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.6130157113075256"
{38989_start} <-> {38989_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml