
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33980_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.14078639447689056"
{33995_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.14078639447689056
{33964_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18911898136138916"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18911898136138916
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18911898136138916
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18911898136138916
{33949_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2072429358959198"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2072429358959198
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2072429358959198
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2072429358959198
{33981_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21670416742563248"
{33950_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3777202069759369"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3777202069759369
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3777202069759369
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3777202069759369
{33965_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3918951451778412"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3918951451778412
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3918951451778412
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3918951451778412
{33951_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5540896207094193"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5540896207094193
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5540896207094193
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5540896207094193
{33966_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5749438256025314"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5749438256025314
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5749438256025314
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5749438256025314
{33982_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7165811732411385"
{33995_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7451503127813339"
{33995_start} <-> {33995_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml