
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10601_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.09774318337440491"
{10611_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.09774318337440491
{10586_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1983252912759781"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1983252912759781
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1983252912759781
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1983252912759781
{10570_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.24825990200042725"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.24825990200042725
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24825990200042725
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24825990200042725
{10602_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3911243975162506"
{10587_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40896351635456085"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40896351635456085
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40896351635456085
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40896351635456085
{10571_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.44987285137176514"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44987285137176514
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44987285137176514
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44987285137176514
{10611_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5662516057491302"
{10611_start} <-> {10611_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml