
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{7411_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17377330362796783"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17377330362796783
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17377330362796783
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17377330362796783
{7441_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18768805265426636"
{7452_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.18768805265426636
{7426_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19160515069961548"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19160515069961548
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19160515069961548
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19160515069961548
{7412_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38530924916267395"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38530924916267395
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38530924916267395
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38530924916267395
{7427_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.421242356300354"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.421242356300354
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.421242356300354
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.421242356300354
{7452_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5580285787582397"
{7452_start} <-> {7452_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml