
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17095_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.184681698679924"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.184681698679924
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.184681698679924
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.184681698679924
{17111_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21049118041992188"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21049118041992188
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21049118041992188
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21049118041992188
{17096_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.389946386218071"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.389946386218071
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.389946386218071
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.389946386218071
{17112_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4282943159341812"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4282943159341812
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4282943159341812
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4282943159341812
{17127_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49448487162590027"
{17134_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.49448487162590027
{17097_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5833635926246643"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5833635926246643
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5833635926246643
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5833635926246643
{17113_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6120857894420624"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6120857894420624
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6120857894420624
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6120857894420624
{17098_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7853943258523941"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7853943258523941
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7853943258523941
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7853943258523941
{17128_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8140697479248047"
{17114_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8241946846246719"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8241946846246719
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8241946846246719
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8241946846246719
{17099_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.998202383518219"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.998202383518219
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.998202383518219
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.998202383518219
{17115_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0038177967071533"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0038177967071533
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0038177967071533
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0038177967071533
{17134_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0459738671779633"
{17134_start} <-> {17134_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml