
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{24266_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16354505717754364"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.16354505717754364
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.16354505717754364
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.16354505717754364
{24282_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2267681211233139"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2267681211233139
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2267681211233139
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2267681211233139
{24267_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3708270639181137"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3708270639181137
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3708270639181137
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3708270639181137
{24297_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4306546747684479"
{24302_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4306546747684479
{24283_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4331151396036148"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4331151396036148
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4331151396036148
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4331151396036148
{24268_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5297394543886185"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5297394543886185
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5297394543886185
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5297394543886185
{24284_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.662431538105011"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.662431538105011
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.662431538105011
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.662431538105011
{24269_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7555915862321854"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7555915862321854
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7555915862321854
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7555915862321854
{24298_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7655326426029205"
{24285_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8534903675317764"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8534903675317764
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8534903675317764
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8534903675317764
{24270_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9364335983991623"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9364335983991623
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9364335983991623
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9364335983991623
{24302_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9594691693782806"
{24302_start} <-> {24302_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml