
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{21718_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.205907940864563"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.205907940864563
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.205907940864563
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.205907940864563
{21733_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.23401972651481628"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.23401972651481628
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23401972651481628
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23401972651481628
{21748_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24857650697231293"
{21757_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24857650697231293
{21719_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4237858057022095"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4237858057022095
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4237858057022095
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4237858057022095
{21734_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.46065375208854675"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.46065375208854675
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.46065375208854675
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.46065375208854675
{21749_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49016088247299194"
{21735_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6311982870101929"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6311982870101929
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6311982870101929
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6311982870101929
{21720_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6404192894697189"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6404192894697189
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6404192894697189
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6404192894697189
{21721_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8416542261838913"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8416542261838913
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8416542261838913
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8416542261838913
{21757_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8488511294126511"
{21757_start} <-> {21757_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml