
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10071_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0626448467373848"
{10083_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.0626448467373848
{10039_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.192543625831604"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.192543625831604
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.192543625831604
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.192543625831604
{10055_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19686344265937805"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19686344265937805
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19686344265937805
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19686344265937805
{10040_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4063554108142853"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4063554108142853
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4063554108142853
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4063554108142853
{10056_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4098194092512131"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4098194092512131
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4098194092512131
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4098194092512131
{10072_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5159419849514961"
{10083_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5573764815926552"
{10083_start} <-> {10083_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.5573764815926552"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml