
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14691_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16269661486148834"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.16269661486148834
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16269661486148834
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16269661486148834
{14707_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18367905914783478"
{14716_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.18367905914783478
{14675_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20506331324577332"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20506331324577332
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20506331324577332
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20506331324577332
{14692_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.369041383266449"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.369041383266449
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.369041383266449
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.369041383266449
{14676_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.424322709441185"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.424322709441185
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.424322709441185
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.424322709441185
{14693_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5550419837236404"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5550419837236404
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5550419837236404
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5550419837236404
{14708_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5826889127492905"
{14677_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6303481608629227"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6303481608629227
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6303481608629227
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6303481608629227
{14716_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7018887549638748"
{14716_start} <-> {14716_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml