
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{12739_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21457721292972565"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21457721292972565
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21457721292972565
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21457721292972565
{12754_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22646886110305786"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22646886110305786
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22646886110305786
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22646886110305786
{12755_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4022603929042816"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4022603929042816
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4022603929042816
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4022603929042816
{12740_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40388305485248566"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.40388305485248566
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40388305485248566
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40388305485248566
{12756_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6048834919929504"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6048834919929504
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6048834919929504
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6048834919929504
{12741_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6098478883504868"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6098478883504868
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6098478883504868
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6098478883504868
{12757_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7819710224866867"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7819710224866867
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7819710224866867
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7819710224866867
{12742_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.836435005068779"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.836435005068779
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.836435005068779
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.836435005068779
{12770_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9141976237297058"
{12778_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9141976237297058
{12743_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.017902985215187"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.017902985215187
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.017902985215187
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.017902985215187
{12758_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0229010879993439"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0229010879993439
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0229010879993439
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0229010879993439
{12744_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.206203654408455"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.206203654408455
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.206203654408455
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.206203654408455
{12759_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2242077887058258"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2242077887058258
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2242077887058258
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2242077887058258
{12771_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.3220620453357697"
{12745_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4010568410158157"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4010568410158157
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4010568410158157
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4010568410158157
{12778_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.4295921921730042"
{12778_start} <-> {12778_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml