
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4410_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19536669552326202"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19536669552326202
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19536669552326202
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19536669552326202
{4395_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21414561569690704"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21414561569690704
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21414561569690704
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21414561569690704
{4411_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39173783361911774"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39173783361911774
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39173783361911774
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39173783361911774
{4396_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4244566112756729"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4244566112756729
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4244566112756729
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4244566112756729
{4412_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.625339686870575"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.625339686870575
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.625339686870575
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.625339686870575
{4397_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6501252502202988"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6501252502202988
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6501252502202988
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6501252502202988
{4425_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7085890173912048"
{4435_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7085890173912048
{4426_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7955649420619011"
{4413_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8221994489431381"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8221994489431381
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8221994489431381
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8221994489431381
{4398_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8350009024143219"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8350009024143219
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8350009024143219
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8350009024143219
{4399_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0102157294750214"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0102157294750214
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0102157294750214
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0102157294750214
{4427_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.015158586204052"
{4414_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0267993211746216"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0267993211746216
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0267993211746216
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0267993211746216
{4435_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1761859059333801"
{4435_start} <-> {4435_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml