
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{26716_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.06184201315045357"
{26726_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.06184201315045357
{26717_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11075492575764656"
{26685_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1657242476940155"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1657242476940155
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1657242476940155
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1657242476940155
{26701_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19935369491577148"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19935369491577148
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19935369491577148
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19935369491577148
{26686_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3641761243343353"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3641761243343353
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3641761243343353
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3641761243343353
{26702_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38506561517715454"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38506561517715454
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38506561517715454
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38506561517715454
{26718_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5199695415794849"
{26719_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5318764494732022"
{26687_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5532771646976471"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5532771646976471
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5532771646976471
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5532771646976471
{26703_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5781146287918091"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5781146287918091
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5781146287918091
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5781146287918091
{26726_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5842829830944538"
{26726_start} <-> {26726_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml