
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{37302_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18444576859474182"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18444576859474182
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18444576859474182
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18444576859474182
{37317_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1938440054655075"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1938440054655075
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1938440054655075
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1938440054655075
{37318_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37074805796146393"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.37074805796146393
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37074805796146393
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37074805796146393
{37303_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39668890833854675"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.39668890833854675
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39668890833854675
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39668890833854675
{37333_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5133827328681946"
{37345_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5133827328681946
{37319_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5338511765003204"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5338511765003204
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5338511765003204
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5338511765003204
{37304_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5997523665428162"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5997523665428162
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5997523665428162
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5997523665428162
{37334_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6080983802676201"
{37320_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.721762090921402"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.721762090921402
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.721762090921402
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.721762090921402
{37305_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8089321702718735"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8089321702718735
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8089321702718735
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8089321702718735
{37321_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9239645600318909"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9239645600318909
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9239645600318909
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9239645600318909
{37345_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9930230379104614"
{37345_start} <-> {37345_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml