
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{36561_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20261983573436737"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20261983573436737
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20261983573436737
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20261983573436737
{36545_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20628197491168976"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20628197491168976
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20628197491168976
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20628197491168976
{36546_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4098663032054901"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4098663032054901
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4098663032054901
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4098663032054901
{36562_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4466041177511215"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4466041177511215
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4466041177511215
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4466041177511215
{36547_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6109218895435333"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6109218895435333
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6109218895435333
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6109218895435333
{36563_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6478939354419708"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6478939354419708
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6478939354419708
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6478939354419708
{36548_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8232696503400803"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8232696503400803
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8232696503400803
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8232696503400803
{36564_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.849391296505928"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.849391296505928
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.849391296505928
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.849391296505928
{36576_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.998559296131134"
{36586_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.998559296131134
{36549_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0199059844017029"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0199059844017029
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0199059844017029
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0199059844017029
{36565_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0713999420404434"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0713999420404434
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0713999420404434
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0713999420404434
{36550_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1977102607488632"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1977102607488632
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1977102607488632
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1977102607488632
{36566_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2698780745267868"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2698780745267868
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2698780745267868
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2698780745267868
{36551_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4017591774463654"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.4017591774463654
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4017591774463654
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4017591774463654
{36567_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4710151851177216"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4710151851177216
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4710151851177216
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4710151851177216
{36586_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.5662285685539246"
{36586_start} <-> {36586_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml