
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{25645_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18225423991680145"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18225423991680145
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18225423991680145
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18225423991680145
{25660_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18941058218479156"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18941058218479156
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18941058218479156
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18941058218479156
{25676_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2789267301559448"
{25686_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2789267301559448
{25661_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3713848143815994"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3713848143815994
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3713848143815994
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3713848143815994
{25646_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3924233019351959"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3924233019351959
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3924233019351959
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3924233019351959
{25662_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5711089074611664"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5711089074611664
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5711089074611664
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5711089074611664
{25677_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6091257035732269"
{25647_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6133905798196793"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6133905798196793
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6133905798196793
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6133905798196793
{25686_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7083714306354523"
{25686_start} <-> {25686_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml