
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14402_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.017473826184868813"
{14414_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.017473826184868813
{14386_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1983812302350998"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1983812302350998
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1983812302350998
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1983812302350998
{14371_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23140180110931396"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.23140180110931396
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23140180110931396
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23140180110931396
{14387_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3884464204311371"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3884464204311371
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3884464204311371
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3884464204311371
{14372_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43345923721790314"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.43345923721790314
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43345923721790314
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43345923721790314
{14414_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.44526625610888004"
{14414_start} <-> {14414_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml