
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{25899_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18319298326969147"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18319298326969147
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18319298326969147
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18319298326969147
{25915_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20624171197414398"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20624171197414398
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20624171197414398
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20624171197414398
{25900_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3663610965013504"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3663610965013504
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3663610965013504
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3663610965013504
{25931_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3907604515552521"
{25940_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.3907604515552521
{25916_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41743554174900055"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41743554174900055
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41743554174900055
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41743554174900055
{25901_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5566913187503815"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5566913187503815
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5566913187503815
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5566913187503815
{25917_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5949606448411942"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5949606448411942
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5949606448411942
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5949606448411942
{25902_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7582671791315079"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7582671791315079
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7582671791315079
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7582671791315079
{25918_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7771156430244446"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7771156430244446
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7771156430244446
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7771156430244446
{25940_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8986432254314423"
{25940_start} <-> {25940_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml