
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13031_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.045497044920921326"
{13040_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.045497044920921326
{13015_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19853146374225616"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19853146374225616
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19853146374225616
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19853146374225616
{12999_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20527376234531403"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20527376234531403
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20527376234531403
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20527376234531403
{13032_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.28383132815361023"
{13033_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.32967353239655495"
{13016_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38712434470653534"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38712434470653534
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38712434470653534
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38712434470653534
{13000_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.44618135690689087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44618135690689087
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44618135690689087
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44618135690689087
{13017_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5979718714952469"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5979718714952469
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5979718714952469
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5979718714952469
{13040_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6220105737447739"
{13040_start} <-> {13040_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml