
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13667_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.006891651079058647"
{13684_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.006891651079058647
{13668_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.008868547854945064"
{13635_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16438178718090057"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.16438178718090057
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16438178718090057
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16438178718090057
{13651_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2292531430721283"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2292531430721283
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2292531430721283
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2292531430721283
{13636_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3557681441307068"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3557681441307068
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3557681441307068
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3557681441307068
{13684_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4244119059294462"
{13684_start} <-> {13684_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml