
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41564_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.13223250210285187"
{41573_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.13223250210285187
{41532_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16575853526592255"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.16575853526592255
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16575853526592255
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16575853526592255
{41548_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.169691801071167"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.169691801071167
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.169691801071167
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.169691801071167
{41533_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.34987030923366547"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.34987030923366547
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34987030923366547
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34987030923366547
{41549_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3778345286846161"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3778345286846161
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3778345286846161
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3778345286846161
{41534_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5487042665481567"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5487042665481567
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5487042665481567
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5487042665481567
{41550_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5605017691850662"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5605017691850662
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5605017691850662
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5605017691850662
{41565_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6501908451318741"
{41573_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6718180328607559"
{41573_start} <-> {41573_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml