
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14193_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.04476882889866829"
{14205_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.04476882889866829
{14161_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20432929694652557"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20432929694652557
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20432929694652557
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20432929694652557
{14177_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20795723795890808"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20795723795890808
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20795723795890808
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20795723795890808
{14194_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.272558007389307"
{14178_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40840549767017365"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40840549767017365
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40840549767017365
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40840549767017365
{14162_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4304446280002594"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4304446280002594
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4304446280002594
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4304446280002594
{14205_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.46716080978512764"
{14205_start} <-> {14205_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml