
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33199_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.09927651286125183"
{33211_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.09927651286125183
{33183_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21456506848335266"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21456506848335266
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21456506848335266
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21456506848335266
{33200_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21503248810768127"
{33168_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21906280517578125"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21906280517578125
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21906280517578125
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21906280517578125
{33184_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3718900680541992"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3718900680541992
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3718900680541992
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3718900680541992
{33169_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4451756775379181"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4451756775379181
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4451756775379181
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4451756775379181
{33211_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5125909149646759"
{33211_start} <-> {33211_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml