
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33898_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.07059580087661743"
{33907_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.07059580087661743
{33899_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15437442809343338"
{33882_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2240525484085083"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2240525484085083
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2240525484085083
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2240525484085083
{33867_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2294810563325882"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2294810563325882
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2294810563325882
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2294810563325882
{33883_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.419340118765831"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.419340118765831
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.419340118765831
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.419340118765831
{33868_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43441760540008545"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43441760540008545
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43441760540008545
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43441760540008545
{33900_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.45537275820970535"
{33907_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5488457977771759"
{33907_start} <-> {33907_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.5488457977771759"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml