
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38942_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.034679949283599854"
{38950_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.034679949283599854
{38943_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.042656042613089085"
{38910_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20612365007400513"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20612365007400513
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20612365007400513
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20612365007400513
{38926_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22103363275527954"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22103363275527954
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22103363275527954
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22103363275527954
{38944_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3466365123167634"
{38911_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42053157091140747"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42053157091140747
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42053157091140747
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42053157091140747
{38927_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4216150790452957"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4216150790452957
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4216150790452957
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4216150790452957
{38945_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.43437539134174585"
{38950_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5655027031898499"
{38950_start} <-> {38950_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml