
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14490_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.028094440698623657"
{14502_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.028094440698623657
{14491_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.034983718767762184"
{14474_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.15597058832645416"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.15597058832645416
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15597058832645416
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15597058832645416
{14458_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19525548815727234"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19525548815727234
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19525548815727234
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19525548815727234
{14475_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.346488356590271"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.346488356590271
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.346488356590271
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.346488356590271
{14459_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3803129345178604"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3803129345178604
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3803129345178604
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3803129345178604
{14502_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5124648213386536"
{14502_start} <-> {14502_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml