
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35260_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17050272226333618"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17050272226333618
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17050272226333618
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17050272226333618
{35245_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.24419766664505005"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.24419766664505005
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24419766664505005
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24419766664505005
{35276_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2581946551799774"
{35285_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2581946551799774
{35277_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.29949260130524635"
{35261_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.36090196669101715"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.36090196669101715
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36090196669101715
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36090196669101715
{35246_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4356981962919235"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4356981962919235
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4356981962919235
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4356981962919235
{35278_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4907041974365711"
{35262_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5372065901756287"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5372065901756287
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5372065901756287
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5372065901756287
{35247_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6561404466629028"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6561404466629028
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6561404466629028
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6561404466629028
{35285_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.663894534111023"
{35285_start} <-> {35285_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml