
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{7898_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.028837712481617928"
{7906_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.028837712481617928
{7882_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18186801671981812"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18186801671981812
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18186801671981812
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18186801671981812
{7867_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2189663052558899"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2189663052558899
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2189663052558899
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2189663052558899
{7883_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4028150141239166"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4028150141239166
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4028150141239166
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4028150141239166
{7868_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42122918367385864"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42122918367385864
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42122918367385864
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42122918367385864
{7906_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.473228158429265"
{7906_start} <-> {7906_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml