
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{24209_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.008102934807538986"
{24223_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.008102934807538986
{24210_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0164394062012434"
{24179_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2126864492893219"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2126864492893219
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2126864492893219
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2126864492893219
{24194_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22213444113731384"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22213444113731384
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22213444113731384
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22213444113731384
{24211_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3774665277451277"
{24180_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3931398391723633"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3931398391723633
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3931398391723633
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3931398391723633
{24195_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4150692820549011"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4150692820549011
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4150692820549011
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4150692820549011
{24223_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4781732074916363"
{24223_start} <-> {24223_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml