
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{5709_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08327830582857132"
{5723_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08327830582857132
{5694_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18097679316997528"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18097679316997528
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18097679316997528
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18097679316997528
{5679_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20308712124824524"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20308712124824524
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20308712124824524
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20308712124824524
{5695_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3807591199874878"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3807591199874878
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3807591199874878
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3807591199874878
{5680_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4133327156305313"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4133327156305313
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4133327156305313
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4133327156305313
{5710_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49276671558618546"
{5723_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5373195484280586"
{5723_start} <-> {5723_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml