
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{5378_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20456290245056152"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20456290245056152
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20456290245056152
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20456290245056152
{5363_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20658165216445923"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20658165216445923
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20658165216445923
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20658165216445923
{5393_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.29289132356643677"
{5401_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.29289132356643677
{5364_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42173194885253906"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42173194885253906
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42173194885253906
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42173194885253906
{5379_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42667272686958313"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42667272686958313
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42667272686958313
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42667272686958313
{5380_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6252063363790512"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6252063363790512
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6252063363790512
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6252063363790512
{5365_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6408541798591614"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6408541798591614
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6408541798591614
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6408541798591614
{5394_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7208949029445648"
{5401_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7416443228721619"
{5401_start} <-> {5401_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml