
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28777_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.15339645743370056"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.15339645743370056
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15339645743370056
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15339645743370056
{28761_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18418064713478088"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18418064713478088
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18418064713478088
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18418064713478088
{28793_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.19865866005420685"
{28798_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.19865866005420685
{28778_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.34462589025497437"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.34462589025497437
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34462589025497437
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34462589025497437
{28762_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3643180727958679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3643180727958679
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3643180727958679
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3643180727958679
{28779_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5273397713899612"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5273397713899612
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5273397713899612
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5273397713899612
{28763_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5927146673202515"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5927146673202515
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5927146673202515
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5927146673202515
{28798_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6158058792352676"
{28798_start} <-> {28798_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml