
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23987_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21657583117485046"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21657583117485046
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21657583117485046
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21657583117485046
{23971_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22195416688919067"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22195416688919067
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22195416688919067
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22195416688919067
{23988_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38500335812568665"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38500335812568665
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38500335812568665
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38500335812568665
{23972_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4617808759212494"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4617808759212494
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4617808759212494
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4617808759212494
{23989_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5445746630430222"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5445746630430222
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5445746630430222
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5445746630430222
{23973_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6603815108537674"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6603815108537674
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6603815108537674
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6603815108537674
{24003_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.753690779209137"
{24011_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.753690779209137
{23990_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7553873658180237"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7553873658180237
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7553873658180237
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7553873658180237
{23974_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8705482184886932"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8705482184886932
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8705482184886932
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8705482184886932
{24004_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9206167459487915"
{23991_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9297806024551392"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9297806024551392
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9297806024551392
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9297806024551392
{24011_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0021460354328156"
{24011_start} <-> {24011_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml