
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{36505_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2157420516014099"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2157420516014099
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2157420516014099
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2157420516014099
{36520_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22325856983661652"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22325856983661652
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.22325856983661652
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.22325856983661652
{36521_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4135187417268753"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4135187417268753
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4135187417268753
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4135187417268753
{36506_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4360866844654083"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4360866844654083
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4360866844654083
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4360866844654083
{36536_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.576738178730011"
{36544_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.576738178730011
{36522_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6075398325920105"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6075398325920105
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6075398325920105
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6075398325920105
{36507_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6262668073177338"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6262668073177338
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6262668073177338
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6262668073177338
{36523_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.782802164554596"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.782802164554596
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.782802164554596
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.782802164554596
{36508_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8279540538787842"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8279540538787842
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8279540538787842
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8279540538787842
{36524_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.004653200507164"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.004653200507164
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.004653200507164
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.004653200507164
{36509_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.009480506181717"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.009480506181717
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.009480506181717
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.009480506181717
{36544_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1866881847381592"
{36544_start} <-> {36544_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml