
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11537_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17216432094573975"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17216432094573975
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17216432094573975
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17216432094573975
{11553_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2035093605518341"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2035093605518341
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2035093605518341
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2035093605518341
{11538_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36345188319683075"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.36345188319683075
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36345188319683075
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36345188319683075
{11568_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.38309815526008606"
{11583_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.38309815526008606
{11554_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3921509236097336"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3921509236097336
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3921509236097336
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3921509236097336
{11539_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5667604506015778"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5667604506015778
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5667604506015778
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5667604506015778
{11555_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5856907665729523"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5856907665729523
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5856907665729523
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5856907665729523
{11569_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7025083005428314"
{11556_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7675152719020844"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7675152719020844
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7675152719020844
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7675152719020844
{11540_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7768248319625854"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7768248319625854
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7768248319625854
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7768248319625854
{11570_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9210496842861176"
{11583_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.965072900056839"
{11583_start} <-> {11583_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml