
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29989_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08178500086069107"
{30001_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08178500086069107
{29974_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19964894652366638"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19964894652366638
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19964894652366638
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19964894652366638
{29959_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2021336555480957"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2021336555480957
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2021336555480957
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2021336555480957
{29990_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2434229478240013"
{29991_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2883426509797573"
{29992_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.31582688353955746"
{29960_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4255146384239197"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4255146384239197
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4255146384239197
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4255146384239197
{29993_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4262384455651045"
{29975_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43993866443634033"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43993866443634033
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43993866443634033
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43993866443634033
{30001_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.551001138985157"
{30001_start} <-> {30001_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml