
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18491_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17663583159446716"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17663583159446716
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17663583159446716
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17663583159446716
{18507_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21119914948940277"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21119914948940277
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21119914948940277
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21119914948940277
{18523_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3201168179512024"
{18536_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.3201168179512024
{18492_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3680761754512787"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3680761754512787
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3680761754512787
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3680761754512787
{18508_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4178278148174286"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4178278148174286
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4178278148174286
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4178278148174286
{18493_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5426921397447586"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5426921397447586
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5426921397447586
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5426921397447586
{18509_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6151815354824066"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6151815354824066
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6151815354824066
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6151815354824066
{18524_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6899856626987457"
{18494_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7205546349287033"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7205546349287033
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7205546349287033
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7205546349287033
{18510_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7972619235515594"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7972619235515594
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7972619235515594
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7972619235515594
{18536_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8716524243354797"
{18536_start} <-> {18536_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml