
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{20404_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1865493804216385"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1865493804216385
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1865493804216385
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1865493804216385
{20420_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2370288074016571"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2370288074016571
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2370288074016571
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2370288074016571
{20435_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.29955175518989563"
{20441_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.29955175518989563
{20436_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3412010036408901"
{20405_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37108534574508667"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.37108534574508667
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.37108534574508667
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.37108534574508667
{20421_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.45231227576732635"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.45231227576732635
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.45231227576732635
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.45231227576732635
{20406_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5535285770893097"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5535285770893097
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5535285770893097
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5535285770893097
{20437_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.592677678912878"
{20422_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6430616825819016"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6430616825819016
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6430616825819016
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6430616825819016
{20407_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7382586002349854"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7382586002349854
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7382586002349854
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7382586002349854
{20441_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7639501392841339"
{20441_start} <-> {20441_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml