
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29777_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20593714714050293"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20593714714050293
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20593714714050293
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20593714714050293
{29762_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21412837505340576"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21412837505340576
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21412837505340576
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21412837505340576
{29778_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3844739645719528"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3844739645719528
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3844739645719528
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3844739645719528
{29763_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40684984624385834"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.40684984624385834
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40684984624385834
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40684984624385834
{29779_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5687197595834732"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5687197595834732
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5687197595834732
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5687197595834732
{29764_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6333993077278137"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6333993077278137
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6333993077278137
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6333993077278137
{29780_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7951785773038864"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7951785773038864
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7951785773038864
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7951785773038864
{29793_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8287293314933777"
{29798_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.8287293314933777
{29765_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8359014540910721"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8359014540910721
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8359014540910721
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8359014540910721
{29781_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9627808332443237"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9627808332443237
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9627808332443237
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9627808332443237
{29766_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.005271539092064"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.005271539092064
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.005271539092064
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.005271539092064
{29782_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1449566334486008"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1449566334486008
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.1449566334486008
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.1449566334486008
{29767_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.203316330909729"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.203316330909729
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.203316330909729
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.203316330909729
{29783_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3773140013217926"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3773140013217926
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3773140013217926
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3773140013217926
{29768_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3941789269447327"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3941789269447327
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3941789269447327
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3941789269447327
{29798_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.465309739112854"
{29798_start} <-> {29798_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml