
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22752_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.03503915295004845"
{22761_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.03503915295004845
{22737_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1889951527118683"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1889951527118683
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1889951527118683
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1889951527118683
{22722_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20677341520786285"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20677341520786285
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20677341520786285
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20677341520786285
{22753_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2590772919356823"
{22738_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3919700086116791"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3919700086116791
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3919700086116791
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3919700086116791
{22723_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3992524892091751"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3992524892091751
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3992524892091751
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3992524892091751
{22754_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.41301434859633446"
{22739_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5640659332275391"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5640659332275391
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5640659332275391
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5640659332275391
{22724_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.58936707675457"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.58936707675457
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.58936707675457
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.58936707675457
{22761_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6493501923978329"
{22761_start} <-> {22761_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml