
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{20744_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19990693032741547"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19990693032741547
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19990693032741547
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19990693032741547
{20729_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23827026784420013"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.23827026784420013
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23827026784420013
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23827026784420013
{20745_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.36456748843193054"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.36456748843193054
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36456748843193054
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36456748843193054
{20730_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4543472081422806"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4543472081422806
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4543472081422806
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4543472081422806
{20760_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49331584572792053"
{20771_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.49331584572792053
{20746_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5709071755409241"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5709071755409241
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5709071755409241
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5709071755409241
{20731_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6273819506168365"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6273819506168365
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6273819506168365
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6273819506168365
{20747_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7758028507232666"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7758028507232666
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7758028507232666
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7758028507232666
{20732_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8493374884128571"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8493374884128571
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8493374884128571
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8493374884128571
{20748_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9555645883083344"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9555645883083344
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9555645883083344
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9555645883083344
{20733_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0579216331243515"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0579216331243515
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0579216331243515
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0579216331243515
{20761_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0605336725711823"
{20771_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0962985455989838"
{20771_start} <-> {20771_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml