
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{16021_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1813870370388031"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1813870370388031
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1813870370388031
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1813870370388031
{16006_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.193557471036911"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.193557471036911
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.193557471036911
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.193557471036911
{16036_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24841202795505524"
{16046_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24841202795505524
{16007_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39622287452220917"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39622287452220917
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39622287452220917
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39622287452220917
{16022_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4097039997577667"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4097039997577667
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4097039997577667
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4097039997577667
{16037_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5461771339178085"
{16008_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6102093309164047"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6102093309164047
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6102093309164047
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6102093309164047
{16023_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6192114055156708"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6192114055156708
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6192114055156708
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6192114055156708
{16038_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7298708558082581"
{16046_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7736963778734207"
{16046_start} <-> {16046_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.7736963778734207"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml