
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18933_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.200328066945076"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.200328066945076
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.200328066945076
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.200328066945076
{18917_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21373781561851501"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21373781561851501
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21373781561851501
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21373781561851501
{18934_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3782535046339035"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3782535046339035
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3782535046339035
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3782535046339035
{18918_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41069701313972473"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41069701313972473
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41069701313972473
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41069701313972473
{18935_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5846984684467316"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5846984684467316
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5846984684467316
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5846984684467316
{18919_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.626378521323204"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.626378521323204
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.626378521323204
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.626378521323204
{18949_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6689279675483704"
{18956_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6689279675483704
{18936_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7422661185264587"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7422661185264587
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7422661185264587
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7422661185264587
{18920_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8094528466463089"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8094528466463089
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8094528466463089
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8094528466463089
{18950_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8533405512571335"
{18937_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9586500078439713"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9586500078439713
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9586500078439713
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9586500078439713
{18921_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9864343851804733"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9864343851804733
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9864343851804733
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9864343851804733
{18956_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.113721251487732"
{18956_start} <-> {18956_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml