
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23171_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.12764175236225128"
{23181_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.12764175236225128
{23155_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16784536838531494"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.16784536838531494
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16784536838531494
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16784536838531494
{23140_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1985226571559906"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1985226571559906
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1985226571559906
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1985226571559906
{23156_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3581503629684448"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3581503629684448
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3581503629684448
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3581503629684448
{23141_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39165519177913666"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39165519177913666
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39165519177913666
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39165519177913666
{23157_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5368814915418625"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5368814915418625
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5368814915418625
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5368814915418625
{23142_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6467051953077316"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6467051953077316
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6467051953077316
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6467051953077316
{23181_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6491845399141312"
{23181_start} <-> {23181_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml