
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18019_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18457502126693726"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18457502126693726
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18457502126693726
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18457502126693726
{18003_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21971158683300018"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21971158683300018
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21971158683300018
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21971158683300018
{18020_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.36935874819755554"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.36935874819755554
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36935874819755554
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36935874819755554
{18004_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38066214323043823"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.38066214323043823
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38066214323043823
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38066214323043823
{18005_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5686151832342148"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5686151832342148
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5686151832342148
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5686151832342148
{18021_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5793123990297318"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5793123990297318
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5793123990297318
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5793123990297318
{18006_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7565875053405762"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7565875053405762
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7565875053405762
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7565875053405762
{18022_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7685374021530151"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7685374021530151
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7685374021530151
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7685374021530151
{18035_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8335099816322327"
{18042_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.8335099816322327
{18023_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9562353789806366"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9562353789806366
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9562353789806366
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9562353789806366
{18007_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9650874435901642"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9650874435901642
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9650874435901642
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9650874435901642
{18036_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0593549460172653"
{18037_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1118563748896122"
{18024_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1336592137813568"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1336592137813568
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1336592137813568
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1336592137813568
{18008_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.162697434425354"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.162697434425354
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.162697434425354
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.162697434425354
{18025_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3108868449926376"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3108868449926376
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3108868449926376
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3108868449926376
{18009_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.355347752571106"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.355347752571106
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.355347752571106
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.355347752571106
{18042_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.394339382648468"
{18042_start} <-> {18042_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml