
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8294_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.01071738451719284"
{8300_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.01071738451719284
{8263_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18227896094322205"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18227896094322205
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18227896094322205
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18227896094322205
{8278_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19009694457054138"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19009694457054138
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19009694457054138
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19009694457054138
{8279_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3985382914543152"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3985382914543152
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3985382914543152
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3985382914543152
{8264_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4322603791952133"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4322603791952133
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4322603791952133
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4322603791952133
{8300_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.434052012860775"
{8300_start} <-> {8300_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml