
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{18396_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1352996677160263"
{18404_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1352996677160263
{18381_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19126340746879578"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19126340746879578
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19126340746879578
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19126340746879578
{18366_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20472244918346405"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20472244918346405
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20472244918346405
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20472244918346405
{18382_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3819337636232376"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3819337636232376
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3819337636232376
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3819337636232376
{18367_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4156639724969864"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4156639724969864
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4156639724969864
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4156639724969864
{18383_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5822938531637192"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5822938531637192
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5822938531637192
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5822938531637192
{18368_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6307678371667862"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6307678371667862
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6307678371667862
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6307678371667862
{18404_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7351478189229965"
{18404_start} <-> {18404_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml