
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17408_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.12655499577522278"
{17419_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.12655499577522278
{17378_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21285121142864227"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21285121142864227
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21285121142864227
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21285121142864227
{17393_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2346426248550415"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2346426248550415
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2346426248550415
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2346426248550415
{17409_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2757621556520462"
{17379_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4143698960542679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4143698960542679
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4143698960542679
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4143698960542679
{17394_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41832028329372406"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41832028329372406
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41832028329372406
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41832028329372406
{17410_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.45077449083328247"
{17380_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6117998510599136"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6117998510599136
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6117998510599136
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6117998510599136
{17395_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6297899484634399"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6297899484634399
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6297899484634399
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6297899484634399
{17419_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7206458151340485"
{17419_start} <-> {17419_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml