
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35432_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.06350650638341904"
{35445_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.06350650638341904
{35402_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17084051668643951"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.17084051668643951
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.17084051668643951
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.17084051668643951
{35417_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2027718424797058"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2027718424797058
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2027718424797058
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2027718424797058
{35433_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.30418654531240463"
{35434_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3228096626698971"
{35418_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3761128932237625"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3761128932237625
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3761128932237625
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3761128932237625
{35435_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.37780463695526123"
{35403_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38321688771247864"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38321688771247864
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38321688771247864
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38321688771247864
{35436_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4979007840156555"
{35419_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5520619004964828"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5520619004964828
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5520619004964828
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5520619004964828
{35404_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5661414265632629"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5661414265632629
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5661414265632629
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5661414265632629
{35445_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6626335009932518"
{35445_start} <-> {35445_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml