
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14110_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.008297565393149853"
{14119_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.008297565393149853
{14111_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11151776742190123"
{14080_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19064152240753174"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19064152240753174
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19064152240753174
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19064152240753174
{14095_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21583488583564758"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21583488583564758
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21583488583564758
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21583488583564758
{14081_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41116665303707123"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41116665303707123
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41116665303707123
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41116665303707123
{14096_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4340984374284744"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4340984374284744
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4340984374284744
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4340984374284744
{14119_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6108175544068217"
{14119_start} <-> {14119_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml