
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8870_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1577434539794922"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1577434539794922
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1577434539794922
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1577434539794922
{8855_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19566825032234192"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19566825032234192
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19566825032234192
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19566825032234192
{8886_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.30672627687454224"
{8893_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.30672627687454224
{8856_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3809371888637543"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3809371888637543
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3809371888637543
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3809371888637543
{8871_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3840335011482239"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3840335011482239
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3840335011482239
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3840335011482239
{8872_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5626971125602722"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5626971125602722
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5626971125602722
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5626971125602722
{8857_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5990299433469772"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5990299433469772
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5990299433469772
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5990299433469772
{8893_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6436046957969666"
{8893_start} <-> {8893_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml