
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35652_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.12035343796014786"
{35663_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.12035343796014786
{35653_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.153759453445673"
{35622_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19000287353992462"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19000287353992462
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19000287353992462
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19000287353992462
{35637_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19989213347434998"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19989213347434998
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19989213347434998
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19989213347434998
{35654_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.30928297713398933"
{35623_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3754815608263016"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3754815608263016
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3754815608263016
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3754815608263016
{35638_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3875590115785599"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3875590115785599
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3875590115785599
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3875590115785599
{35655_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.41578593477606773"
{35656_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.472384050488472"
{35624_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5797179341316223"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5797179341316223
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5797179341316223
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5797179341316223
{35639_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6241090595722198"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6241090595722198
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6241090595722198
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6241090595722198
{35663_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6276492848992348"
{35663_start} <-> {35663_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml