
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17737_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18383556604385376"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18383556604385376
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18383556604385376
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18383556604385376
{17722_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18832425773143768"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18832425773143768
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18832425773143768
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18832425773143768
{17753_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.23087768256664276"
{17762_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.23087768256664276
{17738_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.34676393866539"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.34676393866539
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34676393866539
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.34676393866539
{17723_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41700100898742676"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41700100898742676
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41700100898742676
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41700100898742676
{17754_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4955787807703018"
{17739_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.503891721367836"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.503891721367836
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.503891721367836
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.503891721367836
{17724_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6277422606945038"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6277422606945038
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6277422606945038
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6277422606945038
{17740_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7177393883466721"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7177393883466721
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7177393883466721
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7177393883466721
{17762_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.722278967499733"
{17762_start} <-> {17762_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml