
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38048_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1712925285100937"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1712925285100937
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1712925285100937
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1712925285100937
{38033_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22476603090763092"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22476603090763092
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22476603090763092
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22476603090763092
{38049_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37545713782310486"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.37545713782310486
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37545713782310486
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37545713782310486
{38034_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4675370901823044"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4675370901823044
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4675370901823044
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4675370901823044
{38050_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5837886184453964"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5837886184453964
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5837886184453964
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5837886184453964
{38035_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6430554687976837"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6430554687976837
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6430554687976837
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6430554687976837
{38063_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7261824011802673"
{38068_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7261824011802673
{38051_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7771037369966507"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7771037369966507
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7771037369966507
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7771037369966507
{38036_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8456774055957794"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8456774055957794
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8456774055957794
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8456774055957794
{38064_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.892162099480629"
{38052_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0092817544937134"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0092817544937134
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0092817544937134
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0092817544937134
{38037_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0731976330280304"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0731976330280304
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0731976330280304
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0731976330280304
{38068_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2002931833267212"
{38068_start} <-> {38068_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 1.2002931833267212"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml