
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33129_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19242477416992188"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19242477416992188
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.19242477416992188
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.19242477416992188
{33144_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2064308524131775"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2064308524131775
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2064308524131775
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2064308524131775
{33145_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39065365493297577"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39065365493297577
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39065365493297577
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39065365493297577
{33130_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41750696301460266"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.41750696301460266
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41750696301460266
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41750696301460266
{33160_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.45853397250175476"
{33167_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.45853397250175476
{33161_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.47348501812666655"
{33146_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5785611420869827"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5785611420869827
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5785611420869827
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5785611420869827
{33131_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6155968457460403"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6155968457460403
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6155968457460403
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6155968457460403
{33147_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7500023543834686"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7500023543834686
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7500023543834686
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7500023543834686
{33162_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.790603275410831"
{33132_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8247007131576538"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8247007131576538
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8247007131576538
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8247007131576538
{33167_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9681129157543182"
{33167_start} <-> {33167_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml