
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{6664_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1592637300491333"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1592637300491333
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1592637300491333
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1592637300491333
{6648_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22279158234596252"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.22279158234596252
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22279158234596252
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22279158234596252
{6665_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3418574631214142"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3418574631214142
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3418574631214142
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3418574631214142
{6649_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4259023517370224"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4259023517370224
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4259023517370224
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4259023517370224
{6666_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5652939081192017"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5652939081192017
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5652939081192017
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5652939081192017
{6650_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6050741970539093"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6050741970539093
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6050741970539093
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6050741970539093
{6667_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7633254528045654"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7633254528045654
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7633254528045654
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7633254528045654
{6651_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8418341279029846"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8418341279029846
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8418341279029846
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8418341279029846
{6668_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9567438364028931"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9567438364028931
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9567438364028931
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9567438364028931
{6652_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0288445502519608"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.0288445502519608
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0288445502519608
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0288445502519608
{6680_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1080256700515747"
{6686_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1080256700515747
{6669_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1532782167196274"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1532782167196274
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1532782167196274
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1532782167196274
{6681_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2123823389410973"
{6653_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2146802842617035"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2146802842617035
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2146802842617035
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2146802842617035
{6670_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3464238941669464"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3464238941669464
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3464238941669464
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3464238941669464
{6682_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.3944498971104622"
{6654_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4412166476249695"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4412166476249695
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4412166476249695
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4412166476249695
{6686_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.5056065618991852"
{6686_start} <-> {6686_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml