
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2783_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1314568817615509"
{2795_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1314568817615509
{2751_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16477154195308685"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.16477154195308685
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.16477154195308685
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.16477154195308685
{2767_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18061277270317078"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18061277270317078
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18061277270317078
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18061277270317078
{2784_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.23089855164289474"
{2752_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3556457906961441"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3556457906961441
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3556457906961441
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3556457906961441
{2768_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3735792189836502"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3735792189836502
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3735792189836502
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3735792189836502
{2769_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.548633947968483"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.548633947968483
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.548633947968483
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.548633947968483
{2753_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5548402369022369"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5548402369022369
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5548402369022369
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5548402369022369
{2795_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5998871922492981"
{2795_start} <-> {2795_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml