
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34542_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1974407583475113"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1974407583475113
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1974407583475113
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1974407583475113
{34557_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22342172265052795"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22342172265052795
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22342172265052795
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22342172265052795
{34573_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.29554229974746704"
{34586_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.29554229974746704
{34543_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3962772339582443"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3962772339582443
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3962772339582443
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3962772339582443
{34558_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4134005308151245"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4134005308151245
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134005308151245
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134005308151245
{34574_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4960159659385681"
{34575_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5813811048865318"
{34544_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5973504781723022"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5973504781723022
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5973504781723022
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5973504781723022
{34559_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6142637133598328"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6142637133598328
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6142637133598328
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6142637133598328
{34586_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6921365559101105"
{34586_start} <-> {34586_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml