
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{19288_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17352361977100372"
{19296_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17352361977100372
{19273_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20801371335983276"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20801371335983276
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20801371335983276
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20801371335983276
{19259_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20847374200820923"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20847374200820923
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20847374200820923
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20847374200820923
{19274_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38754086196422577"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38754086196422577
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38754086196422577
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38754086196422577
{19260_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43186554312705994"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43186554312705994
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43186554312705994
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43186554312705994
{19275_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5941155850887299"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5941155850887299
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5941155850887299
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5941155850887299
{19296_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6387101262807846"
{19296_start} <-> {19296_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml