
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35078_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.12817804515361786"
{35088_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.12817804515361786
{35063_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18044117093086243"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18044117093086243
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18044117093086243
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18044117093086243
{35048_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2094200998544693"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2094200998544693
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2094200998544693
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2094200998544693
{35049_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37172484397888184"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.37172484397888184
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37172484397888184
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37172484397888184
{35064_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.389082133769989"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.389082133769989
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.389082133769989
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.389082133769989
{35079_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49707306921482086"
{35050_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5669219642877579"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5669219642877579
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5669219642877579
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5669219642877579
{35065_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5942317545413971"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5942317545413971
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5942317545413971
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5942317545413971
{35088_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7670197933912277"
{35088_start} <-> {35088_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml