
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{36358_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.174310103058815"
{36365_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.174310103058815
{36327_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21827536821365356"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21827536821365356
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21827536821365356
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21827536821365356
{36342_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22154207527637482"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22154207527637482
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22154207527637482
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22154207527637482
{36328_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41549190878868103"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41549190878868103
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41549190878868103
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41549190878868103
{36343_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43325696885585785"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.43325696885585785
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43325696885585785
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43325696885585785
{36344_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6075929999351501"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6075929999351501
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6075929999351501
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6075929999351501
{36329_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6178430467844009"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6178430467844009
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6178430467844009
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6178430467844009
{36365_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6209373325109482"
{36365_start} <-> {36365_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml