
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{1147_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22207856178283691"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.22207856178283691
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22207856178283691
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22207856178283691
{1132_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2295815497636795"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2295815497636795
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.2295815497636795
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.2295815497636795
{1148_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4300142675638199"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4300142675638199
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4300142675638199
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4300142675638199
{1133_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43785038590431213"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.43785038590431213
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43785038590431213
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43785038590431213
{1134_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6338695734739304"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6338695734739304
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6338695734739304
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6338695734739304
{1149_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.648272305727005"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.648272305727005
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.648272305727005
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.648272305727005
{1162_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6865912079811096"
{1173_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6865912079811096
{1163_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7448824346065521"
{1150_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8501468598842621"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8501468598842621
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8501468598842621
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8501468598842621
{1135_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8516082465648651"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8516082465648651
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8516082465648651
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8516082465648651
{1164_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8714721947908401"
{1136_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0519915223121643"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0519915223121643
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0519915223121643
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0519915223121643
{1151_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.063482090830803"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.063482090830803
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.063482090830803
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.063482090830803
{1173_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1476750075817108"
{1173_start} <-> {1173_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml