
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9895_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.005636394023895264"
{9908_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.005636394023895264
{9864_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16654859483242035"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.16654859483242035
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16654859483242035
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16654859483242035
{9879_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17209365963935852"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.17209365963935852
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17209365963935852
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17209365963935852
{9880_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.35958926379680634"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.35958926379680634
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35958926379680634
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35958926379680634
{9865_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39442773163318634"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39442773163318634
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39442773163318634
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39442773163318634
{9908_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4382261633872986"
{9908_start} <-> {9908_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml