
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{24669_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.07998256385326385"
{24678_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.07998256385326385
{24670_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11080656200647354"
{24671_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1695520356297493"
{24653_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18274818360805511"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18274818360805511
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18274818360805511
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18274818360805511
{24638_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21715480089187622"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21715480089187622
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21715480089187622
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21715480089187622
{24654_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3969486504793167"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3969486504793167
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3969486504793167
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3969486504793167
{24639_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4039231240749359"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4039231240749359
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4039231240749359
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4039231240749359
{24678_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4703793376684189"
{24678_start} <-> {24678_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml