
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3113_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1922903209924698"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1922903209924698
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1922903209924698
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1922903209924698
{3097_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19370511174201965"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19370511174201965
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19370511174201965
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19370511174201965
{3114_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3753953278064728"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3753953278064728
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3753953278064728
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3753953278064728
{3098_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41575801372528076"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41575801372528076
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41575801372528076
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41575801372528076
{3115_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5883863419294357"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5883863419294357
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5883863419294357
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5883863419294357
{3099_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.591372936964035"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.591372936964035
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.591372936964035
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.591372936964035
{3128_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7934938073158264"
{3134_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7934938073158264
{3116_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7962850630283356"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7962850630283356
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7962850630283356
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7962850630283356
{3100_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8091367930173874"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8091367930173874
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8091367930173874
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8091367930173874
{3117_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9785986095666885"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9785986095666885
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9785986095666885
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9785986095666885
{3101_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0089052766561508"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0089052766561508
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0089052766561508
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0089052766561508
{3118_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1790857762098312"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1790857762098312
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1790857762098312
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1790857762098312
{3102_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2121665477752686"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2121665477752686
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2121665477752686
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2121665477752686
{3134_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.3577642440795898"
{3134_start} <-> {3134_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml