
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10507_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18001842498779297"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18001842498779297
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18001842498779297
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18001842498779297
{10492_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2114945948123932"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2114945948123932
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2114945948123932
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2114945948123932
{10508_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40380340814590454"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.40380340814590454
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40380340814590454
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40380340814590454
{10493_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4135564714670181"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4135564714670181
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4135564714670181
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4135564714670181
{10494_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.568531796336174"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.568531796336174
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.568531796336174
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.568531796336174
{10509_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6320287585258484"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6320287585258484
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6320287585258484
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6320287585258484
{10522_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7091121077537537"
{10529_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7091121077537537
{10495_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7750757187604904"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7750757187604904
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7750757187604904
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7750757187604904
{10510_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.838998943567276"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.838998943567276
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.838998943567276
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.838998943567276
{10523_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.846687451004982"
{10529_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9487985968589783"
{10529_start} <-> {10529_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml