
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{40057_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1997365802526474"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1997365802526474
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1997365802526474
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1997365802526474
{40042_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21132659912109375"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21132659912109375
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21132659912109375
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21132659912109375
{40072_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.41390809416770935"
{40081_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.41390809416770935
{40058_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41508154571056366"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41508154571056366
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41508154571056366
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41508154571056366
{40043_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4252443462610245"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4252443462610245
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4252443462610245
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4252443462610245
{40059_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5911084413528442"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5911084413528442
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5911084413528442
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5911084413528442
{40044_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6456305384635925"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6456305384635925
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6456305384635925
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6456305384635925
{40045_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8281234353780746"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8281234353780746
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8281234353780746
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.8281234353780746
{40060_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8343871235847473"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8343871235847473
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8343871235847473
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8343871235847473
{40081_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8869392573833466"
{40081_start} <-> {40081_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml