
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{25444_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.163210928440094"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.163210928440094
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.163210928440094
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.163210928440094
{25459_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.20783255994319916"
{25467_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.20783255994319916
{25460_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21244578761979938"
{25429_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2192704677581787"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2192704677581787
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2192704677581787
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2192704677581787
{25445_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40420882403850555"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40420882403850555
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40420882403850555
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40420882403850555
{25430_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.44133391976356506"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44133391976356506
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44133391976356506
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44133391976356506
{25446_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6271132975816727"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6271132975816727
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6271132975816727
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6271132975816727
{25431_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6451134532690048"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6451134532690048
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6451134532690048
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6451134532690048
{25461_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6588455657474697"
{25467_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.724935457110405"
{25467_start} <-> {25467_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml