
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13612_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18635880947113037"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18635880947113037
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18635880947113037
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18635880947113037
{13596_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19812364876270294"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19812364876270294
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19812364876270294
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19812364876270294
{13613_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3719480484724045"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3719480484724045
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3719480484724045
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3719480484724045
{13597_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43907491862773895"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.43907491862773895
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43907491862773895
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43907491862773895
{13614_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5564806461334229"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5564806461334229
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5564806461334229
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5564806461334229
{13598_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6439439207315445"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6439439207315445
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6439439207315445
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6439439207315445
{13615_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7457834929227829"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7457834929227829
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7457834929227829
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7457834929227829
{13628_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8301515579223633"
{13634_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.8301515579223633
{13599_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8370435386896133"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8370435386896133
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8370435386896133
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8370435386896133
{13616_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9404276013374329"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9404276013374329
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9404276013374329
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9404276013374329
{13600_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.042298674583435"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.042298674583435
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.042298674583435
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.042298674583435
{13617_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1250655800104141"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1250655800104141
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1250655800104141
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1250655800104141
{13601_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.218607559800148"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.218607559800148
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.218607559800148
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.218607559800148
{13629_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2569381892681122"
{13618_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3114580363035202"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3114580363035202
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3114580363035202
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3114580363035202
{13602_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.378043383359909"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.378043383359909
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.378043383359909
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.378043383359909
{13634_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.4222703576087952"
{13634_start} <-> {13634_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml