
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{1328_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.05344177782535553"
{1342_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.05344177782535553
{1312_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18759281933307648"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18759281933307648
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18759281933307648
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18759281933307648
{1297_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20627151429653168"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20627151429653168
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20627151429653168
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20627151429653168
{1329_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.23524464666843414"
{1313_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3594082295894623"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3594082295894623
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3594082295894623
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3594082295894623
{1298_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4097919166088104"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4097919166088104
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4097919166088104
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4097919166088104
{1314_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5294661968946457"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5294661968946457
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5294661968946457
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5294661968946457
{1299_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5813475549221039"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5813475549221039
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5813475549221039
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5813475549221039
{1342_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6242839246988297"
{1342_start} <-> {1342_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml