
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28842_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18016065657138824"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18016065657138824
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18016065657138824
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18016065657138824
{28858_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21329067647457123"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21329067647457123
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21329067647457123
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21329067647457123
{28843_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39525963366031647"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39525963366031647
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39525963366031647
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39525963366031647
{28859_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43911440670490265"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.43911440670490265
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.43911440670490265
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.43911440670490265
{28873_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5877104997634888"
{28882_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5877104997634888
{28844_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6132426559925079"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6132426559925079
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6132426559925079
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6132426559925079
{28860_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6289088279008865"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6289088279008865
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6289088279008865
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6289088279008865
{28874_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7244956642389297"
{28845_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8029581308364868"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8029581308364868
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8029581308364868
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8029581308364868
{28861_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8083367794752121"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8083367794752121
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8083367794752121
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8083367794752121
{28846_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0008480697870255"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0008480697870255
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0008480697870255
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0008480697870255
{28875_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0041452497243881"
{28862_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0115021616220474"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0115021616220474
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0115021616220474
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0115021616220474
{28882_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1964261531829834"
{28882_start} <-> {28882_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml