
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22244_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.020175402984023094"
{22255_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.020175402984023094
{22245_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.051339833065867424"
{22228_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19958540797233582"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19958540797233582
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19958540797233582
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19958540797233582
{22214_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2169800102710724"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2169800102710724
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2169800102710724
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2169800102710724
{22229_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4224417358636856"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4224417358636856
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4224417358636856
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4224417358636856
{22246_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.42732187919318676"
{22215_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4522571861743927"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4522571861743927
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4522571861743927
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4522571861743927
{22247_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4671368431299925"
{22230_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6240185350179672"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6240185350179672
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6240185350179672
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6240185350179672
{22255_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6897482331842184"
{22255_start} <-> {22255_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml