
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{2853_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16822990775108337"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.16822990775108337
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16822990775108337
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16822990775108337
{2838_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19761338829994202"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19761338829994202
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19761338829994202
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19761338829994202
{2854_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3978275656700134"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3978275656700134
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3978275656700134
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3978275656700134
{2839_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4231363832950592"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4231363832950592
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4231363832950592
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4231363832950592
{2869_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5507702231407166"
{2878_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5507702231407166
{2855_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6064857542514801"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6064857542514801
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6064857542514801
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6064857542514801
{2840_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6177162826061249"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6177162826061249
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6177162826061249
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6177162826061249
{2870_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6555405482649803"
{2856_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7886154800653458"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7886154800653458
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7886154800653458
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7886154800653458
{2841_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8159529566764832"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8159529566764832
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8159529566764832
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8159529566764832
{2871_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9239909574389458"
{2878_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9665673971176147"
{2878_start} <-> {2878_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml