
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{24901_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.019539522007107735"
{24911_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.019539522007107735
{24902_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11396876908838749"
{24903_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.11828335840255022"
{24886_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17516770958900452"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.17516770958900452
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17516770958900452
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17516770958900452
{24871_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20844659209251404"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20844659209251404
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20844659209251404
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20844659209251404
{24887_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3718715161085129"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3718715161085129
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3718715161085129
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3718715161085129
{24872_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39284226298332214"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39284226298332214
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39284226298332214
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39284226298332214
{24911_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.44820971973240376"
{24911_start} <-> {24911_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.44820971973240376"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml