
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{5040_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16886283457279205"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.16886283457279205
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.16886283457279205
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.16886283457279205
{5056_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1979668289422989"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1979668289422989
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1979668289422989
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.1979668289422989
{5041_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.342207670211792"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.342207670211792
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.342207670211792
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.342207670211792
{5057_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38530533015727997"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.38530533015727997
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38530533015727997
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38530533015727997
{5071_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5043361783027649"
{5077_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5043361783027649
{5042_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5612938404083252"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5612938404083252
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5612938404083252
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5612938404083252
{5058_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6136009395122528"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6136009395122528
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6136009395122528
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6136009395122528
{5043_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8028425425291061"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8028425425291061
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8028425425291061
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8028425425291061
{5059_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8031478077173233"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8031478077173233
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8031478077173233
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8031478077173233
{5060_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0066322088241577"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0066322088241577
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0066322088241577
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0066322088241577
{5044_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0137372314929962"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0137372314929962
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0137372314929962
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0137372314929962
{5077_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.094183087348938"
{5077_start} <-> {5077_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml