
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{37132_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17178402841091156"
{37144_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17178402841091156
{37117_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19365960359573364"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19365960359573364
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19365960359573364
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19365960359573364
{37101_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22570057213306427"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22570057213306427
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.22570057213306427
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.22570057213306427
{37133_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.30874456465244293"
{37118_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42009755969047546"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42009755969047546
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.42009755969047546
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.42009755969047546
{37102_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4222181588411331"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4222181588411331
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4222181588411331
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4222181588411331
{37103_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6009336858987808"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6009336858987808
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6009336858987808
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6009336858987808
{37144_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6083910316228867"
{37144_start} <-> {37144_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml