
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8372_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.03640049323439598"
{8385_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.03640049323439598
{8357_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2067447453737259"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2067447453737259
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2067447453737259
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2067447453737259
{8341_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21386069059371948"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21386069059371948
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21386069059371948
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21386069059371948
{8373_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.23465682193636894"
{8358_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3970187157392502"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3970187157392502
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3970187157392502
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3970187157392502
{8342_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40402305126190186"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40402305126190186
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.40402305126190186
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.40402305126190186
{8374_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5278871469199657"
{8343_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.599128395318985"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.599128395318985
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.599128395318985
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.599128395318985
{8359_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6187407672405243"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6187407672405243
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6187407672405243
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6187407672405243
{8385_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6668068133294582"
{8385_start} <-> {8385_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml