
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{21554_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16517393290996552"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.16517393290996552
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16517393290996552
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16517393290996552
{21570_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2190539389848709"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2190539389848709
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2190539389848709
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2190539389848709
{21555_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3759322911500931"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3759322911500931
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3759322911500931
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3759322911500931
{21571_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4224342107772827"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4224342107772827
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4224342107772827
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4224342107772827
{21556_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6029183715581894"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6029183715581894
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6029183715581894
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6029183715581894
{21572_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6314922124147415"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6314922124147415
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6314922124147415
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6314922124147415
{21585_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.672105610370636"
{21594_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.672105610370636
{21557_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7972391098737717"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7972391098737717
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7972391098737717
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7972391098737717
{21573_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8456814736127853"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8456814736127853
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8456814736127853
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8456814736127853
{21586_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0130296051502228"
{21558_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0242888778448105"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0242888778448105
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0242888778448105
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0242888778448105
{21574_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.067405790090561"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.067405790090561
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.067405790090561
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.067405790090561
{21559_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1800890415906906"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1800890415906906
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1800890415906906
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1800890415906906
{21575_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.263711392879486"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.263711392879486
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.263711392879486
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.263711392879486
{21594_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.3152706027030945"
{21594_start} <-> {21594_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml