
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22357_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1817757487297058"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1817757487297058
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1817757487297058
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1817757487297058
{22341_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18795336782932281"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18795336782932281
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18795336782932281
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18795336782932281
{22373_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.27154672145843506"
{22384_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.27154672145843506
{22358_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.35566794872283936"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.35566794872283936
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35566794872283936
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.35566794872283936
{22342_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39945201575756073"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39945201575756073
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39945201575756073
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39945201575756073
{22359_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5564017593860626"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5564017593860626
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5564017593860626
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5564017593860626
{22343_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6470099240541458"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6470099240541458
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6470099240541458
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6470099240541458
{22384_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7206366062164307"
{22384_start} <-> {22384_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml