
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13208_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19008193910121918"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19008193910121918
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19008193910121918
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19008193910121918
{13224_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2110641747713089"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2110641747713089
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2110641747713089
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.2110641747713089
{13209_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3942398577928543"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3942398577928543
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3942398577928543
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3942398577928543
{13225_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4270545244216919"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4270545244216919
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4270545244216919
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4270545244216919
{13210_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5808884799480438"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5808884799480438
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5808884799480438
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5808884799480438
{13226_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6083459854125977"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6083459854125977
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6083459854125977
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6083459854125977
{13211_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7700953185558319"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7700953185558319
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7700953185558319
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7700953185558319
{13227_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8073568791151047"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8073568791151047
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8073568791151047
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8073568791151047
{13228_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9710653871297836"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9710653871297836
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9710653871297836
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9710653871297836
{13212_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.004520058631897"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.004520058631897
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.004520058631897
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.004520058631897
{13213_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1552585065364838"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.1552585065364838
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1552585065364838
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1552585065364838
{13229_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1639549434185028"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.1639549434185028
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1639549434185028
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1639549434185028
{13240_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.213598608970642"
{13250_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.213598608970642
{13241_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2549201659858227"
{13230_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3403863906860352"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3403863906860352
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3403863906860352
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3403863906860352
{13214_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3585090786218643"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3585090786218643
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3585090786218643
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3585090786218643
{13242_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4876220636069775"
{13231_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.5615313798189163"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.5615313798189163
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.5615313798189163
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.5615313798189163
{13215_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.591880902647972"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.591880902647972
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.591880902647972
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.591880902647972
{13250_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.7265455722808838"
{13250_start} <-> {13250_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml