
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4544_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.002658630022779107"
{4554_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.002658630022779107
{4513_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18961815536022186"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18961815536022186
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18961815536022186
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18961815536022186
{4529_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22110432386398315"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22110432386398315
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22110432386398315
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22110432386398315
{4545_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3644660657737404"
{4514_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3925118148326874"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3925118148326874
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3925118148326874
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3925118148326874
{4530_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41820622980594635"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41820622980594635
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41820622980594635
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41820622980594635
{4546_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.45603376091457903"
{4515_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5808974206447601"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5808974206447601
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5808974206447601
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5808974206447601
{4554_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5858966356609017"
{4554_start} <-> {4554_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml