
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29421_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1523779034614563"
{29430_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1523779034614563
{29391_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18929271399974823"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18929271399974823
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18929271399974823
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18929271399974823
{29406_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21371512115001678"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21371512115001678
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21371512115001678
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21371512115001678
{29422_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2641271650791168"
{29392_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3990626484155655"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3990626484155655
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3990626484155655
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3990626484155655
{29407_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40519005060195923"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40519005060195923
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40519005060195923
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40519005060195923
{29430_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5189987123012543"
{29430_start} <-> {29430_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml