
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{32897_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1596975028514862"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1596975028514862
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1596975028514862
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1596975028514862
{32882_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21347756683826447"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21347756683826447
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21347756683826447
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21347756683826447
{32898_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3443044424057007"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3443044424057007
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3443044424057007
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3443044424057007
{32883_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41719411313533783"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41719411313533783
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41719411313533783
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41719411313533783
{32913_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5166313052177429"
{32920_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5166313052177429
{32899_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5206350982189178"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5206350982189178
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5206350982189178
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5206350982189178
{32884_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6225522607564926"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6225522607564926
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6225522607564926
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6225522607564926
{32900_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6872667819261551"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6872667819261551
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6872667819261551
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6872667819261551
{32885_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8654994815587997"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8654994815587997
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8654994815587997
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8654994815587997
{32901_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8743084371089935"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8743084371089935
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8743084371089935
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8743084371089935
{32920_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9667472243309021"
{32920_start} <-> {32920_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml