
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{26812_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19434848427772522"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19434848427772522
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19434848427772522
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19434848427772522
{26827_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.23122380673885345"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.23122380673885345
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23122380673885345
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23122380673885345
{26813_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3979528695344925"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3979528695344925
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3979528695344925
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3979528695344925
{26828_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4339762479066849"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4339762479066849
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4339762479066849
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4339762479066849
{26843_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5478578805923462"
{26860_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5478578805923462
{26814_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5878853499889374"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5878853499889374
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5878853499889374
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5878853499889374
{26829_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6378184854984283"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6378184854984283
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6378184854984283
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6378184854984283
{26815_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8111504912376404"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8111504912376404
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8111504912376404
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8111504912376404
{26830_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8551226705312729"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8551226705312729
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8551226705312729
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8551226705312729
{26860_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9570793509483337"
{26860_start} <-> {26860_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml