
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22888_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17597290873527527"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17597290873527527
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17597290873527527
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17597290873527527
{22904_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19439730048179626"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19439730048179626
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19439730048179626
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19439730048179626
{22889_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3622595816850662"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3622595816850662
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3622595816850662
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3622595816850662
{22905_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3978435695171356"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3978435695171356
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3978435695171356
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3978435695171356
{22890_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5750760436058044"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5750760436058044
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5750760436058044
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5750760436058044
{22906_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6055387109518051"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6055387109518051
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6055387109518051
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6055387109518051
{22891_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.760325089097023"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.760325089097023
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.760325089097023
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.760325089097023
{22919_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7657995223999023"
{22928_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7657995223999023
{22907_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8294543474912643"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8294543474912643
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8294543474912643
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8294543474912643
{22920_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8804214596748352"
{22921_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9055066388100386"
{22892_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9398741573095322"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9398741573095322
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9398741573095322
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9398741573095322
{22908_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.030212938785553"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.030212938785553
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.030212938785553
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.030212938785553
{22928_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0491893887519836"
{22928_start} <-> {22928_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml