
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{12988_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.011546578258275986"
{12998_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.011546578258275986
{12989_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.024027968756854534"
{12990_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0391294090077281"
{12991_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.10157691594213247"
{12956_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20417408645153046"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20417408645153046
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20417408645153046
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20417408645153046
{12972_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21663035452365875"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21663035452365875
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21663035452365875
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21663035452365875
{12998_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.3534495495259762"
{12998_start} <-> {12998_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.3534495495259762"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml