
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{16837_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17419229447841644"
{16844_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17419229447841644
{16822_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18675193190574646"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18675193190574646
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18675193190574646
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18675193190574646
{16807_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20218192040920258"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20218192040920258
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20218192040920258
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20218192040920258
{16808_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40449805557727814"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40449805557727814
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40449805557727814
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40449805557727814
{16823_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4137507677078247"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4137507677078247
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4137507677078247
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4137507677078247
{16824_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5980083048343658"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5980083048343658
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5980083048343658
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5980083048343658
{16809_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.646989569067955"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.646989569067955
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.646989569067955
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.646989569067955
{16844_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.781352087855339"
{16844_start} <-> {16844_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml