
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10167_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2031841278076172"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2031841278076172
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2031841278076172
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2031841278076172
{10183_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20491325855255127"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20491325855255127
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20491325855255127
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20491325855255127
{10199_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.26142454147338867"
{10210_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.26142454147338867
{10168_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3673589825630188"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3673589825630188
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3673589825630188
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3673589825630188
{10184_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4149446040391922"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4149446040391922
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4149446040391922
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4149446040391922
{10200_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5307789146900177"
{10201_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5371679197996855"
{10169_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5747250020503998"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5747250020503998
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5747250020503998
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5747250020503998
{10185_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5870302617549896"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5870302617549896
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5870302617549896
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5870302617549896
{10202_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.758947966620326"
{10186_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.769730269908905"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.769730269908905
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.769730269908905
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.769730269908905
{10203_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7811033986508846"
{10210_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.786013126373291"
{10210_start} <-> {10210_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml