
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10860_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15239855647087097"
{10868_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.15239855647087097
{10829_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19089670479297638"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19089670479297638
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19089670479297638
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19089670479297638
{10845_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21155473589897156"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21155473589897156
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21155473589897156
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21155473589897156
{10861_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3380562365055084"
{10830_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.34316882491111755"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.34316882491111755
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.34316882491111755
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.34316882491111755
{10846_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4027263671159744"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4027263671159744
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4027263671159744
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4027263671159744
{10831_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5751494020223618"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5751494020223618
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5751494020223618
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5751494020223618
{10847_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5921832770109177"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5921832770109177
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5921832770109177
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5921832770109177
{10868_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6277058720588684"
{10868_start} <-> {10868_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml