
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10404_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.13828356564044952"
{10413_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.13828356564044952
{10405_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17180204764008522"
{10372_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1784878373146057"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.1784878373146057
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1784878373146057
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1784878373146057
{10388_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22641131281852722"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22641131281852722
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.22641131281852722
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.22641131281852722
{10373_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3809642791748047"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3809642791748047
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3809642791748047
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3809642791748047
{10389_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4355953186750412"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4355953186750412
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4355953186750412
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4355953186750412
{10374_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5721547156572342"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5721547156572342
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5721547156572342
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5721547156572342
{10390_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6347255259752274"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6347255259752274
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6347255259752274
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6347255259752274
{10413_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6618011146783829"
{10413_start} <-> {10413_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml