
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35694_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.035155437886714935"
{35701_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.035155437886714935
{35664_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1811400204896927"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.1811400204896927
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1811400204896927
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1811400204896927
{35679_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21087737381458282"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21087737381458282
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21087737381458282
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21087737381458282
{35665_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3620768189430237"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3620768189430237
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3620768189430237
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3620768189430237
{35680_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39972835779190063"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39972835779190063
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39972835779190063
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39972835779190063
{35701_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5562874302268028"
{35701_start} <-> {35701_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml