
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31043_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0351269356906414"
{31051_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.0351269356906414
{31044_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1688961498439312"
{31028_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20133042335510254"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20133042335510254
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20133042335510254
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20133042335510254
{31012_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20595639944076538"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20595639944076538
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20595639944076538
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20595639944076538
{31029_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4055692255496979"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4055692255496979
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4055692255496979
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4055692255496979
{31013_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40665803849697113"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40665803849697113
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40665803849697113
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40665803849697113
{31051_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4900407902896404"
{31051_start} <-> {31051_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml