
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10993_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20293477177619934"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20293477177619934
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20293477177619934
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20293477177619934
{11009_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.23308049142360687"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.23308049142360687
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23308049142360687
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23308049142360687
{10994_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.399095356464386"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.399095356464386
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.399095356464386
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.399095356464386
{11010_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4047529101371765"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4047529101371765
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4047529101371765
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4047529101371765
{10995_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5891012251377106"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5891012251377106
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5891012251377106
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5891012251377106
{11011_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5932529419660568"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5932529419660568
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5932529419660568
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5932529419660568
{10996_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7871243357658386"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7871243357658386
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.7871243357658386
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.7871243357658386
{11012_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8168730288743973"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8168730288743973
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8168730288743973
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8168730288743973
{10997_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9596013873815536"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9596013873815536
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9596013873815536
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9596013873815536
{11013_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9757402390241623"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9757402390241623
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9757402390241623
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9757402390241623
{11025_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1004118919372559"
{11033_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1004118919372559
{10998_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1455331146717072"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1455331146717072
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1455331146717072
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1455331146717072
{11014_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1751444339752197"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1751444339752197
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1751444339752197
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1751444339752197
{10999_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3326540291309357"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3326540291309357
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3326540291309357
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3326540291309357
{11015_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3665609657764435"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3665609657764435
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3665609657764435
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3665609657764435
{11026_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.442107915878296"
{11000_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.5275080353021622"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.5275080353021622
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.5275080353021622
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.5275080353021622
{11016_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6052555441856384"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6052555441856384
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6052555441856384
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6052555441856384
{11033_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.7028602957725525"
{11033_start} <-> {11033_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml