
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28224_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2479816973209381"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2479816973209381
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2479816973209381
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2479816973209381
{28209_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2531365156173706"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2531365156173706
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2531365156173706
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2531365156173706
{28239_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.31899645924568176"
{28253_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.31899645924568176
{28210_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.44039854407310486"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.44039854407310486
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44039854407310486
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.44039854407310486
{28240_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4429612159729004"
{28225_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4431050568819046"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4431050568819046
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4431050568819046
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4431050568819046
{28241_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.44914364675059915"
{28253_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5891273319721222"
{28253_start} <-> {28253_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml