
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10125_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18014809489250183"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18014809489250183
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18014809489250183
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18014809489250183
{10141_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19986529648303986"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19986529648303986
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19986529648303986
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19986529648303986
{10126_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4153696596622467"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4153696596622467
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4153696596622467
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4153696596622467
{10142_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4222087562084198"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4222087562084198
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4222087562084198
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4222087562084198
{10157_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4720996618270874"
{10166_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4720996618270874
{10143_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5988332182168961"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5988332182168961
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5988332182168961
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5988332182168961
{10127_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6092054843902588"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6092054843902588
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6092054843902588
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6092054843902588
{10128_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7822205722332001"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7822205722332001
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7822205722332001
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7822205722332001
{10144_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7992711365222931"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7992711365222931
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7992711365222931
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7992711365222931
{10158_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.817955881357193"
{10166_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9446560144424438"
{10166_start} <-> {10166_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml