
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{32098_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18873341381549835"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18873341381549835
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18873341381549835
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18873341381549835
{32114_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21245241165161133"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21245241165161133
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21245241165161133
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21245241165161133
{32099_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37589432299137115"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.37589432299137115
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37589432299137115
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37589432299137115
{32115_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4008983373641968"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4008983373641968
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4008983373641968
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4008983373641968
{32116_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5720006823539734"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5720006823539734
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5720006823539734
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5720006823539734
{32100_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5809459537267685"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5809459537267685
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5809459537267685
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5809459537267685
{32101_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7800049781799316"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7800049781799316
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7800049781799316
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7800049781799316
{32117_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7998258769512177"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7998258769512177
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7998258769512177
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7998258769512177
{32118_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9492650330066681"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9492650330066681
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9492650330066681
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9492650330066681
{32102_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0000486075878143"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.0000486075878143
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0000486075878143
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0000486075878143
{32130_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0839648246765137"
{32139_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.0839648246765137
{32103_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1456079632043839"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1456079632043839
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1456079632043839
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1456079632043839
{32119_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1667372435331345"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1667372435331345
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1667372435331345
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1667372435331345
{32104_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3658635914325714"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3658635914325714
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3658635914325714
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3658635914325714
{32120_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.386501133441925"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.386501133441925
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.386501133441925
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.386501133441925
{32105_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.557859867811203"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.557859867811203
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.557859867811203
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.557859867811203
{32139_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.580838531255722"
{32139_start} <-> {32139_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml