
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17464_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18606294691562653"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18606294691562653
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18606294691562653
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.18606294691562653
{17495_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2014717310667038"
{17507_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2014717310667038
{17479_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20628266036510468"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20628266036510468
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20628266036510468
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20628266036510468
{17480_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4074273854494095"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4074273854494095
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4074273854494095
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4074273854494095
{17465_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4180256128311157"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4180256128311157
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4180256128311157
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4180256128311157
{17507_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5733269900083542"
{17507_start} <-> {17507_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml