
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{970_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1886717528104782"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1886717528104782
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1886717528104782
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1886717528104782
{985_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21882125735282898"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21882125735282898
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21882125735282898
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21882125735282898
{971_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40240806341171265"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.40240806341171265
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40240806341171265
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40240806341171265
{986_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4283686578273773"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4283686578273773
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4283686578273773
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4283686578273773
{1001_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.43051573634147644"
{1009_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.43051573634147644
{972_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.598301112651825"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.598301112651825
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.598301112651825
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.598301112651825
{987_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.620306134223938"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.620306134223938
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.620306134223938
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.620306134223938
{973_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7966150194406509"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7966150194406509
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7966150194406509
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7966150194406509
{988_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8093366771936417"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8093366771936417
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8093366771936417
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8093366771936417
{974_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.002675086259842"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.002675086259842
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.002675086259842
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.002675086259842
{989_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0040419846773148"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0040419846773148
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0040419846773148
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0040419846773148
{1009_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0721838772296906"
{1009_start} <-> {1009_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml