
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11887_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19424955546855927"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19424955546855927
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19424955546855927
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19424955546855927
{11872_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2270488142967224"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2270488142967224
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2270488142967224
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2270488142967224
{11903_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.33084747195243835"
{11911_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.33084747195243835
{11888_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4101719558238983"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4101719558238983
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4101719558238983
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4101719558238983
{11873_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4382142126560211"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4382142126560211
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4382142126560211
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4382142126560211
{11904_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5216531306505203"
{11905_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5414352286607027"
{11874_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6012157797813416"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6012157797813416
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6012157797813416
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6012157797813416
{11889_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6045253276824951"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6045253276824951
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6045253276824951
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6045253276824951
{11890_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8043677359819412"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8043677359819412
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8043677359819412
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8043677359819412
{11875_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8309628069400787"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8309628069400787
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8309628069400787
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8309628069400787
{11906_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9096843767911196"
{11891_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9972580969333649"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9972580969333649
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9972580969333649
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9972580969333649
{11911_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0032928884029388"
{11911_start} <-> {11911_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml