
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{21611_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.15397992730140686"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.15397992730140686
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15397992730140686
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.15397992730140686
{21595_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19605544209480286"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19605544209480286
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19605544209480286
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19605544209480286
{21626_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24403761327266693"
{21631_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24403761327266693
{21596_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36708128452301025"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.36708128452301025
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36708128452301025
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36708128452301025
{21612_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3831497132778168"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3831497132778168
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3831497132778168
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3831497132778168
{21613_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5827313363552094"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5827313363552094
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5827313363552094
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5827313363552094
{21627_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5832874625921249"
{21597_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6009896993637085"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6009896993637085
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6009896993637085
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6009896993637085
{21631_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.709677442908287"
{21631_start} <-> {21631_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml