
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31209_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18455266952514648"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18455266952514648
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18455266952514648
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18455266952514648
{31225_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20033131539821625"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20033131539821625
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20033131539821625
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20033131539821625
{31241_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24669641256332397"
{31250_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24669641256332397
{31242_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.30228017270565033"
{31210_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36872774362564087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.36872774362564087
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36872774362564087
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36872774362564087
{31226_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3950912803411484"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3950912803411484
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3950912803411484
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3950912803411484
{31211_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5934656858444214"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5934656858444214
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5934656858444214
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5934656858444214
{31227_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6216434389352798"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6216434389352798
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6216434389352798
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6216434389352798
{31243_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6805511564016342"
{31250_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7434350848197937"
{31250_start} <-> {31250_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml