
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8741_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20694664120674133"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20694664120674133
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.20694664120674133
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.20694664120674133
{8726_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22561685740947723"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.22561685740947723
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22561685740947723
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22561685740947723
{8742_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4134156107902527"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4134156107902527
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134156107902527
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134156107902527
{8727_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4266715794801712"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4266715794801712
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4266715794801712
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4266715794801712
{8756_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.42973563075065613"
{8769_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.42973563075065613
{8743_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6287699043750763"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6287699043750763
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6287699043750763
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6287699043750763
{8728_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6347890049219131"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6347890049219131
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6347890049219131
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6347890049219131
{8757_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7187008857727051"
{8769_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7618460357189178"
{8769_start} <-> {8769_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.7618460357189178"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml