
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{35492_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.16896681487560272"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.16896681487560272
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16896681487560272
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.16896681487560272
{35508_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20731820166110992"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20731820166110992
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20731820166110992
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20731820166110992
{35493_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3625762164592743"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3625762164592743
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3625762164592743
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3625762164592743
{35509_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42064768075942993"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.42064768075942993
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42064768075942993
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42064768075942993
{35524_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5585737824440002"
{35536_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5585737824440002
{35494_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.573864758014679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.573864758014679
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.573864758014679
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.573864758014679
{35510_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.615434005856514"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.615434005856514
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.615434005856514
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.615434005856514
{35511_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8020922690629959"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8020922690629959
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8020922690629959
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8020922690629959
{35495_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.810272678732872"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.810272678732872
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.810272678732872
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.810272678732872
{35512_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9759194999933243"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9759194999933243
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9759194999933243
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9759194999933243
{35496_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9941531866788864"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.9941531866788864
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9941531866788864
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9941531866788864
{35536_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0561791956424713"
{35536_start} <-> {35536_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml