
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{16436_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17190110683441162"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.17190110683441162
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17190110683441162
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17190110683441162
{16421_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2180509865283966"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2180509865283966
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2180509865283966
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2180509865283966
{16451_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2835867404937744"
{16469_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2835867404937744
{16452_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.34388967975974083"
{16437_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3805301934480667"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3805301934480667
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3805301934480667
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3805301934480667
{16422_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4300246089696884"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4300246089696884
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4300246089696884
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4300246089696884
{16453_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5484476499259472"
{16438_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5800949186086655"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5800949186086655
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5800949186086655
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5800949186086655
{16423_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5998941510915756"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5998941510915756
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5998941510915756
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5998941510915756
{16454_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7167618684470654"
{16424_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7882398366928101"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7882398366928101
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7882398366928101
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7882398366928101
{16439_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7916320711374283"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7916320711374283
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7916320711374283
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7916320711374283
{16455_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8287060000002384"
{16469_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8519137501716614"
{16469_start} <-> {16469_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml