
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34070_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2149336189031601"
{34080_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2149336189031601
{34055_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22107644379138947"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22107644379138947
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22107644379138947
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22107644379138947
{34040_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23712587356567383"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.23712587356567383
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23712587356567383
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23712587356567383
{34071_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.37964189052581787"
{34056_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41735145449638367"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.41735145449638367
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41735145449638367
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41735145449638367
{34041_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.45776836574077606"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.45776836574077606
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.45776836574077606
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.45776836574077606
{34057_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6269966512918472"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6269966512918472
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6269966512918472
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6269966512918472
{34072_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6381239295005798"
{34073_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.644218975212425"
{34042_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6549837589263916"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6549837589263916
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6549837589263916
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6549837589263916
{34080_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7643676251173019"
{34080_start} <-> {34080_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml