
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11743_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.02553667686879635"
{11751_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.02553667686879635
{11727_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.16294774413108826"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.16294774413108826
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16294774413108826
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.16294774413108826
{11711_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2193497270345688"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2193497270345688
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2193497270345688
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2193497270345688
{11728_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.362577348947525"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.362577348947525
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.362577348947525
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.362577348947525
{11712_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3883773237466812"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3883773237466812
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3883773237466812
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3883773237466812
{11744_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4683912303298712"
{11745_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4817685289308429"
{11729_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5624396055936813"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5624396055936813
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5624396055936813
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5624396055936813
{11751_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5625542607158422"
{11751_start} <-> {11751_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml