
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{23259_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17867113649845123"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17867113649845123
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.17867113649845123
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.17867113649845123
{23290_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18445108830928802"
{23301_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.18445108830928802
{23274_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19199027121067047"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19199027121067047
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19199027121067047
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19199027121067047
{23291_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.33111341297626495"
{23275_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4003455191850662"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4003455191850662
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4003455191850662
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4003455191850662
{23260_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41963107883930206"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41963107883930206
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.41963107883930206
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.41963107883930206
{23276_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5795920342206955"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5795920342206955
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5795920342206955
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5795920342206955
{23261_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6509022116661072"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6509022116661072
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6509022116661072
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6509022116661072
{23301_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.680674597620964"
{23301_start} <-> {23301_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml