
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34848_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18343454599380493"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18343454599380493
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18343454599380493
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18343454599380493
{34833_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2139771729707718"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2139771729707718
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2139771729707718
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2139771729707718
{34849_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3910731226205826"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3910731226205826
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3910731226205826
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3910731226205826
{34834_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41878584027290344"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.41878584027290344
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.41878584027290344
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.41878584027290344
{34850_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.571162685751915"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.571162685751915
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.571162685751915
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.571162685751915
{34863_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5786787867546082"
{34872_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5786787867546082
{34835_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6433015763759613"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6433015763759613
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6433015763759613
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6433015763759613
{34864_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.663472443819046"
{34865_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7925523817539215"
{34851_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7960811257362366"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7960811257362366
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7960811257362366
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7960811257362366
{34836_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8403597921133041"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8403597921133041
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8403597921133041
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8403597921133041
{34872_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8712553381919861"
{34872_start} <-> {34872_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.8712553381919861"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml