
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{28626_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1672958880662918"
{28633_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1672958880662918
{28611_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19524070620536804"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19524070620536804
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19524070620536804
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19524070620536804
{28595_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22526046633720398"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22526046633720398
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22526046633720398
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22526046633720398
{28596_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39991380274295807"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.39991380274295807
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39991380274295807
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.39991380274295807
{28612_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.410482257604599"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.410482257604599
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.410482257604599
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.410482257604599
{28627_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.46371306478977203"
{28633_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5542144626379013"
{28633_start} <-> {28633_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml