
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3405_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17643535137176514"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17643535137176514
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17643535137176514
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17643535137176514
{3390_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1977587342262268"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1977587342262268
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1977587342262268
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1977587342262268
{3391_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38656166195869446"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38656166195869446
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38656166195869446
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38656166195869446
{3406_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38933539390563965"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38933539390563965
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.38933539390563965
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.38933539390563965
{3392_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5574786365032196"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5574786365032196
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5574786365032196
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5574786365032196
{3407_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.575199156999588"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.575199156999588
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.575199156999588
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.575199156999588
{3421_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6727369427680969"
{3431_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6727369427680969
{3422_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7557254657149315"
{3393_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7775610685348511"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7775610685348511
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7775610685348511
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7775610685348511
{3408_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8138812929391861"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8138812929391861
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8138812929391861
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8138812929391861
{3423_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9746803864836693"
{3394_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9935293942689896"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9935293942689896
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9935293942689896
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9935293942689896
{3409_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0249039828777313"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0249039828777313
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0249039828777313
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0249039828777313
{3424_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0629804953932762"
{3425_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1768925786018372"
{3431_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2198707461357117"
{3431_start} <-> {3431_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml