
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{8401_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19373130798339844"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19373130798339844
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19373130798339844
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19373130798339844
{8386_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21960829198360443"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21960829198360443
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21960829198360443
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.21960829198360443
{8416_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2536989748477936"
{8427_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2536989748477936
{8402_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3767111897468567"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3767111897468567
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3767111897468567
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3767111897468567
{8387_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41963425278663635"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41963425278663635
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41963425278663635
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41963425278663635
{8417_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.551032543182373"
{8418_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6032854728400707"
{8403_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6096600890159607"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6096600890159607
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6096600890159607
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6096600890159607
{8388_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6390668600797653"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6390668600797653
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6390668600797653
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6390668600797653
{8404_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8167482763528824"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8167482763528824
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8167482763528824
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8167482763528824
{8389_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8450594544410706"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8450594544410706
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8450594544410706
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8450594544410706
{8427_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.9012665450572968"
{8427_start} <-> {8427_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml