
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{7923_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19895566999912262"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19895566999912262
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19895566999912262
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19895566999912262
{7907_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2057924121618271"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2057924121618271
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2057924121618271
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2057924121618271
{7908_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37533898651599884"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.37533898651599884
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37533898651599884
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37533898651599884
{7924_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4109038859605789"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4109038859605789
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4109038859605789
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4109038859605789
{7909_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5864014178514481"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5864014178514481
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5864014178514481
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5864014178514481
{7925_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5988753885030746"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5988753885030746
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5988753885030746
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5988753885030746
{7910_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7843340337276459"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7843340337276459
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7843340337276459
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7843340337276459
{7926_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8219243288040161"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8219243288040161
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8219243288040161
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8219243288040161
{7911_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9951920807361603"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9951920807361603
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9951920807361603
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9951920807361603
{7927_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0102288126945496"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.0102288126945496
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0102288126945496
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0102288126945496
{7912_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1886354833841324"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.1886354833841324
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1886354833841324
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1886354833841324
{7928_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1994416862726212"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.1994416862726212
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1994416862726212
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1994416862726212
{7938_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2758259773254395"
{7943_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.2758259773254395
{7913_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3961448967456818"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.3961448967456818
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3961448967456818
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3961448967456818
{7939_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4231479614973068"
{7929_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4275381863117218"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4275381863117218
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4275381863117218
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4275381863117218
{7914_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.567925125360489"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.567925125360489
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.567925125360489
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.567925125360489
{7930_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6221837848424911"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.6221837848424911
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6221837848424911
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6221837848424911
{7940_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.6800548285245895"
{7915_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.7576850950717926"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.7576850950717926
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7576850950717926
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7576850950717926
{7943_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.7595345675945282"
{7943_start} <-> {7943_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml