
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{26641_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2120424211025238"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2120424211025238
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2120424211025238
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2120424211025238
{26673_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.21470947563648224"
{26684_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.21470947563648224
{26657_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2245274931192398"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2245274931192398
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2245274931192398
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2245274931192398
{26642_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3903874009847641"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3903874009847641
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3903874009847641
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3903874009847641
{26658_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42107047140598297"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42107047140598297
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42107047140598297
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42107047140598297
{26643_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5701792985200882"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5701792985200882
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5701792985200882
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5701792985200882
{26659_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6440109461545944"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6440109461545944
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6440109461545944
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6440109461545944
{26644_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7560324966907501"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7560324966907501
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7560324966907501
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7560324966907501
{26660_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8448743671178818"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8448743671178818
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8448743671178818
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8448743671178818
{26684_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8743028193712234"
{26684_start} <-> {26684_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml