
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3265_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2060750275850296"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2060750275850296
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2060750275850296
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2060750275850296
{3281_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21668767929077148"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21668767929077148
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21668767929077148
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21668767929077148
{3297_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.334615558385849"
{3306_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.334615558385849
{3266_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38500629365444183"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38500629365444183
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38500629365444183
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38500629365444183
{3282_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4487555921077728"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4487555921077728
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4487555921077728
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4487555921077728
{3267_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5648903697729111"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5648903697729111
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5648903697729111
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5648903697729111
{3283_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6490867286920547"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6490867286920547
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6490867286920547
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6490867286920547
{3306_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7504707872867584"
{3306_start} <-> {3306_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.7504707872867584"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml