
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10655_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19229978322982788"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19229978322982788
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19229978322982788
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19229978322982788
{10670_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20041191577911377"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20041191577911377
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20041191577911377
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20041191577911377
{10685_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3609639108181"
{10701_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.3609639108181
{10656_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40444615483283997"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40444615483283997
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40444615483283997
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40444615483283997
{10671_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42084769904613495"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42084769904613495
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.42084769904613495
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.42084769904613495
{10657_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5942724049091339"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5942724049091339
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5942724049091339
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5942724049091339
{10672_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6395504623651505"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6395504623651505
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6395504623651505
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6395504623651505
{10701_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6562201082706451"
{10701_start} <-> {10701_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.6562201082706451"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml