
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41098_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0010392757831141353"
{41113_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.0010392757831141353
{41099_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.007277371711097658"
{41066_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18751664459705353"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18751664459705353
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18751664459705353
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18751664459705353
{41082_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20570136606693268"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20570136606693268
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20570136606693268
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20570136606693268
{41100_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2615776382153854"
{41067_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.35138796269893646"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.35138796269893646
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.35138796269893646
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.35138796269893646
{41083_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4031447768211365"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4031447768211365
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4031447768211365
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4031447768211365
{41101_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4297028504079208"
{41102_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.47499608097132295"
{41084_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5500122904777527"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5500122904777527
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5500122904777527
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5500122904777527
{41068_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5525606721639633"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5525606721639633
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5525606721639633
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5525606721639633
{41113_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5582728477893397"
{41113_start} <-> {41113_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml