
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{10211_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18622425198554993"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18622425198554993
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18622425198554993
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18622425198554993
{10241_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.19031758606433868"
{10254_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.19031758606433868
{10226_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19205479323863983"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19205479323863983
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19205479323863983
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19205479323863983
{10242_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.30600378662347794"
{10212_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3701593577861786"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3701593577861786
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3701593577861786
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3701593577861786
{10227_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38472481071949005"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38472481071949005
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38472481071949005
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38472481071949005
{10243_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5089970752596855"
{10213_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5970795601606369"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5970795601606369
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5970795601606369
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5970795601606369
{10228_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.605295404791832"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.605295404791832
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.605295404791832
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.605295404791832
{10254_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6236553639173508"
{10254_start} <-> {10254_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.6236553639173508"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml