
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9267_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18907016515731812"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18907016515731812
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18907016515731812
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18907016515731812
{9282_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21340098977088928"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21340098977088928
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21340098977088928
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21340098977088928
{9268_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.41001829504966736"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.41001829504966736
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41001829504966736
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.41001829504966736
{9283_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4364025443792343"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4364025443792343
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4364025443792343
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4364025443792343
{9269_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5916640609502792"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5916640609502792
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5916640609502792
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5916640609502792
{9284_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6050194799900055"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6050194799900055
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6050194799900055
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6050194799900055
{9270_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7782410681247711"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7782410681247711
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7782410681247711
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7782410681247711
{9285_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8039574176073074"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8039574176073074
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8039574176073074
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8039574176073074
{9286_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9796342104673386"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9796342104673386
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9796342104673386
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9796342104673386
{9271_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.992887407541275"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.992887407541275
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.992887407541275
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.992887407541275
{9297_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1616042852401733"
{9303_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1616042852401733
{9287_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1870347708463669"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1870347708463669
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1870347708463669
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1870347708463669
{9272_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2195890843868256"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2195890843868256
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2195890843868256
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2195890843868256
{9273_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4263103902339935"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4263103902339935
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4263103902339935
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4263103902339935
{9288_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4652209132909775"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4652209132909775
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.4652209132909775
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.4652209132909775
{9274_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.6457243412733078"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.6457243412733078
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.6457243412733078
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.6457243412733078
{9289_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.679479405283928"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.679479405283928
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.679479405283928
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.679479405283928
{9303_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.6912314891815186"
{9303_start} <-> {9303_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml