
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41288_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19565725326538086"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19565725326538086
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19565725326538086
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19565725326538086
{41303_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19936016201972961"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19936016201972961
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19936016201972961
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.19936016201972961
{41289_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36915040016174316"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.36915040016174316
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36915040016174316
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36915040016174316
{41304_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3782065063714981"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3782065063714981
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3782065063714981
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3782065063714981
{41318_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.39940059185028076"
{41328_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.39940059185028076
{41305_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5696352273225784"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5696352273225784
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5696352273225784
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5696352273225784
{41290_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5878782272338867"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5878782272338867
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5878782272338867
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.5878782272338867
{41306_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7735000401735306"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7735000401735306
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7735000401735306
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7735000401735306
{41291_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8051970899105072"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8051970899105072
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8051970899105072
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8051970899105072
{41328_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8827320635318756"
{41328_start} <-> {41328_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml