
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27548_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2028740495443344"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2028740495443344
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2028740495443344
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2028740495443344
{27533_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21096578240394592"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21096578240394592
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21096578240394592
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21096578240394592
{27564_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2872006595134735"
{27572_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2872006595134735
{27549_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4191083163022995"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4191083163022995
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4191083163022995
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4191083163022995
{27534_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4239317774772644"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4239317774772644
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4239317774772644
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4239317774772644
{27565_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5885213911533356"
{27550_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.591414287686348"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.591414287686348
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.591414287686348
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.591414287686348
{27535_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6357764899730682"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6357764899730682
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6357764899730682
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6357764899730682
{27572_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7163872718811035"
{27572_start} <-> {27572_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml