
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{36192_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.14138604700565338"
{36205_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.14138604700565338
{36177_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18910107016563416"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18910107016563416
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18910107016563416
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18910107016563416
{36162_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23482568562030792"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.23482568562030792
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.23482568562030792
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.23482568562030792
{36178_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40112893283367157"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40112893283367157
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40112893283367157
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40112893283367157
{36163_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.47461238503456116"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.47461238503456116
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.47461238503456116
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.47461238503456116
{36193_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5104406327009201"
{36205_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5795586854219437"
{36205_start} <-> {36205_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml