
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11201_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18597957491874695"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18597957491874695
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18597957491874695
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18597957491874695
{11216_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.201660618185997"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.201660618185997
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.201660618185997
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.201660618185997
{11231_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3331525921821594"
{11243_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.3331525921821594
{11202_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37042559683322906"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.37042559683322906
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37042559683322906
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37042559683322906
{11217_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3815973252058029"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3815973252058029
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3815973252058029
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3815973252058029
{11232_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.455141119658947"
{11233_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5087175704538822"
{11203_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5657040029764175"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5657040029764175
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5657040029764175
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5657040029764175
{11234_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5682518109679222"
{11218_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5871256440877914"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5871256440877914
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5871256440877914
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5871256440877914
{11204_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7576654106378555"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7576654106378555
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7576654106378555
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7576654106378555
{11235_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7990665808320045"
{11219_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8015912920236588"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8015912920236588
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8015912920236588
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8015912920236588
{11243_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8883142471313477"
{11243_start} <-> {11243_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml