
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{19085_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19561894237995148"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19561894237995148
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19561894237995148
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19561894237995148
{19116_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2030031830072403"
{19130_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.2030031830072403
{19101_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20530429482460022"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20530429482460022
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20530429482460022
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20530429482460022
{19086_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.344870463013649"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.344870463013649
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.344870463013649
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.344870463013649
{19102_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40092112123966217"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.40092112123966217
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40092112123966217
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40092112123966217
{19117_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.43587321043014526"
{19087_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5515259206295013"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5515259206295013
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5515259206295013
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5515259206295013
{19103_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6425617337226868"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6425617337226868
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6425617337226868
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6425617337226868
{19118_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6682932376861572"
{19130_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6982645243406296"
{19130_start} <-> {19130_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml