
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4042_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.024644428864121437"
{4054_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.024644428864121437
{4043_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0490918904542923"
{4044_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17569123208522797"
{4027_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20251525938510895"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20251525938510895
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.20251525938510895
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.20251525938510895
{4011_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21308137476444244"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21308137476444244
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21308137476444244
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21308137476444244
{4012_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3651169091463089"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3651169091463089
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3651169091463089
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3651169091463089
{4028_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4134157598018646"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4134157598018646
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134157598018646
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4134157598018646
{4045_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5362683087587357"
{4013_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5634341388940811"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5634341388940811
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5634341388940811
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5634341388940811
{4029_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.643849179148674"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.643849179148674
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.643849179148674
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.643849179148674
{4054_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6733701173216105"
{4054_start} <-> {4054_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml