
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{24465_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.13621947169303894"
{24471_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.13621947169303894
{24449_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.14959464967250824"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.14959464967250824
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.14959464967250824
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.14959464967250824
{24433_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17772343754768372"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.17772343754768372
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17772343754768372
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17772343754768372
{24434_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.34979279339313507"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.34979279339313507
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34979279339313507
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.34979279339313507
{24450_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3590276837348938"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3590276837348938
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3590276837348938
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3590276837348938
{24466_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.38462384045124054"
{24435_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5549195408821106"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5549195408821106
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5549195408821106
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5549195408821106
{24451_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5766653269529343"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5766653269529343
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5766653269529343
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5766653269529343
{24471_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5782586634159088"
{24471_start} <-> {24471_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml