
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{36278_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08690989762544632"
{36287_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08690989762544632
{36262_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19834329187870026"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19834329187870026
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19834329187870026
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19834329187870026
{36246_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20524021983146667"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.20524021983146667
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20524021983146667
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20524021983146667
{36279_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2575344368815422"
{36247_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4105365723371506"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4105365723371506
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4105365723371506
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4105365723371506
{36263_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4228988438844681"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4228988438844681
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4228988438844681
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4228988438844681
{36287_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5417209342122078"
{36287_start} <-> {36287_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml