
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{15262_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20552371442317963"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20552371442317963
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20552371442317963
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20552371442317963
{15247_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23622256517410278"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.23622256517410278
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23622256517410278
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23622256517410278
{15263_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.43500955402851105"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.43500955402851105
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43500955402851105
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.43500955402851105
{15248_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.450285866856575"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.450285866856575
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.450285866856575
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.450285866856575
{15249_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6149922609329224"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6149922609329224
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6149922609329224
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6149922609329224
{15264_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.659700483083725"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.659700483083725
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.659700483083725
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.659700483083725
{15250_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7961601614952087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7961601614952087
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.7961601614952087
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.7961601614952087
{15277_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8035410046577454"
{15283_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.8035410046577454
{15265_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8453859239816666"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8453859239816666
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8453859239816666
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8453859239816666
{15251_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.983737125992775"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.983737125992775
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.983737125992775
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.983737125992775
{15266_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0430951863527298"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0430951863527298
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0430951863527298
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0430951863527298
{15252_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.190110370516777"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.190110370516777
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.190110370516777
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.190110370516777
{15267_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.242445483803749"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.242445483803749
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.242445483803749
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.242445483803749
{15283_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2788624167442322"
{15283_start} <-> {15283_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml