
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29061_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1882702112197876"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1882702112197876
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1882702112197876
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1882702112197876
{29076_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2049400359392166"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2049400359392166
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2049400359392166
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2049400359392166
{29062_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3883613348007202"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.3883613348007202
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3883613348007202
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.3883613348007202
{29077_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39852383732795715"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.39852383732795715
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39852383732795715
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39852383732795715
{29078_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5877798795700073"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5877798795700073
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5877798795700073
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5877798795700073
{29063_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6081654280424118"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6081654280424118
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6081654280424118
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6081654280424118
{29079_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7906599938869476"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.7906599938869476
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7906599938869476
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7906599938869476
{29064_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8194172382354736"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8194172382354736
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8194172382354736
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8194172382354736
{29080_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9689330607652664"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9689330607652664
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.9689330607652664
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.9689330607652664
{29065_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0118546932935715"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.0118546932935715
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0118546932935715
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0118546932935715
{29081_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1857438385486603"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.1857438385486603
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1857438385486603
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1857438385486603
{29066_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2378052920103073"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.2378052920103073
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2378052920103073
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2378052920103073
{29092_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2960176467895508"
{29101_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.2960176467895508
{29093_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.326256925240159"
{29082_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.3528122752904892"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3528122752904892
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3528122752904892
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.3528122752904892
{29067_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.427076816558838"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.427076816558838
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.427076816558838
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.427076816558838
{29083_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.5557865351438522"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.5557865351438522
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.5557865351438522
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.5557865351438522
{29068_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.61245197057724"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.61245197057724
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.61245197057724
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.61245197057724
{29094_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.7251869980245829"
{29084_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.7474894672632217"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.7474894672632217
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.7474894672632217
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.7474894672632217
{29101_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.7576749920845032"
{29101_start} <-> {29101_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml