
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{31574_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20694255828857422"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20694255828857422
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20694255828857422
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20694255828857422
{31558_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21650640666484833"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21650640666484833
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21650640666484833
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21650640666484833
{31575_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38657572865486145"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38657572865486145
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38657572865486145
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38657572865486145
{31590_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.4241580069065094"
{31599_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.4241580069065094
{31559_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.42476925253868103"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.42476925253868103
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42476925253868103
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.42476925253868103
{31560_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.601942390203476"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.601942390203476
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.601942390203476
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.601942390203476
{31576_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.614130899310112"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.614130899310112
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.614130899310112
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.614130899310112
{31561_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7869803756475449"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7869803756475449
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7869803756475449
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7869803756475449
{31577_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8112960755825043"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8112960755825043
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8112960755825043
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8112960755825043
{31562_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9726678431034088"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9726678431034088
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9726678431034088
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9726678431034088
{31578_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0285316705703735"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0285316705703735
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0285316705703735
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0285316705703735
{31591_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0371995270252228"
{31599_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.083956629037857"
{31599_start} <-> {31599_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml