
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34727_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18777315318584442"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.18777315318584442
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18777315318584442
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.18777315318584442
{34711_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19612371921539307"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19612371921539307
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19612371921539307
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19612371921539307
{34743_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.33032935857772827"
{34753_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.33032935857772827
{34728_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3775959610939026"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.3775959610939026
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3775959610939026
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.3775959610939026
{34712_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38275542855262756"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38275542855262756
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38275542855262756
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38275542855262756
{34744_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.46515749394893646"
{34729_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5582178384065628"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5582178384065628
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5582178384065628
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5582178384065628
{34713_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5852501392364502"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5852501392364502
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5852501392364502
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5852501392364502
{34730_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7670137584209442"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7670137584209442
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7670137584209442
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7670137584209442
{34714_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7810510247945786"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7810510247945786
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7810510247945786
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7810510247945786
{34753_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8519267439842224"
{34753_start} <-> {34753_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml