
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33089_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.17732128500938416"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17732128500938416
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17732128500938416
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.17732128500938416
{33105_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2039400190114975"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2039400190114975
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2039400190114975
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2039400190114975
{33106_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40307945013046265"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.40307945013046265
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40307945013046265
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40307945013046265
{33090_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40512876212596893"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.40512876212596893
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40512876212596893
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40512876212596893
{33120_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5929650664329529"
{33128_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5929650664329529
{33107_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6023163795471191"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6023163795471191
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6023163795471191
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6023163795471191
{33091_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.604585811495781"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.604585811495781
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.604585811495781
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.604585811495781
{33092_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8336186707019806"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8336186707019806
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8336186707019806
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8336186707019806
{33108_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8440362811088562"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8440362811088562
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8440362811088562
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8440362811088562
{33121_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8729646503925323"
{33093_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0383225828409195"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0383225828409195
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0383225828409195
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0383225828409195
{33109_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0665673166513443"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0665673166513443
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0665673166513443
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0665673166513443
{33128_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.1645709872245789"
{33128_start} <-> {33128_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml