
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{0_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.182341530919075"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.182341530919075
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.182341530919075
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.182341530919075
{16_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2096690982580185"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2096690982580185
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2096690982580185
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2096690982580185
{1_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.37476779520511627"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.37476779520511627
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37476779520511627
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.37476779520511627
{17_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40673045814037323"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.40673045814037323
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40673045814037323
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40673045814037323
{31_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5657822489738464"
{46_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5657822489738464
{2_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.591926172375679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.591926172375679
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.591926172375679
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.591926172375679
{18_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6186594218015671"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6186594218015671
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6186594218015671
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6186594218015671
{3_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7708741277456284"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7708741277456284
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7708741277456284
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7708741277456284
{19_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7871134132146835"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7871134132146835
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7871134132146835
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7871134132146835
{32_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8192593157291412"
{4_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8991615623235703"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8991615623235703
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8991615623235703
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8991615623235703
{33_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9193169549107552"
{46_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.0096758604049683"
{46_start} <-> {46_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 1.0096758604049683"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml