
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{3554_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2114173024892807"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2114173024892807
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2114173024892807
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2114173024892807
{3569_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2209077924489975"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2209077924489975
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2209077924489975
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2209077924489975
{3555_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4081052839756012"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4081052839756012
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4081052839756012
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4081052839756012
{3570_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4339432418346405"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4339432418346405
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4339432418346405
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4339432418346405
{3571_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6463746279478073"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6463746279478073
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6463746279478073
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6463746279478073
{3556_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6467444449663162"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6467444449663162
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6467444449663162
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6467444449663162
{3585_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6738600134849548"
{3594_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6738600134849548
{3586_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6839789506047964"
{3557_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8448161333799362"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8448161333799362
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8448161333799362
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8448161333799362
{3572_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8509526550769806"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8509526550769806
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8509526550769806
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8509526550769806
{3573_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0206095278263092"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0206095278263092
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0206095278263092
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0206095278263092
{3558_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0777254104614258"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0777254104614258
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0777254104614258
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0777254104614258
{3587_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1735045369714499"
{3574_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2333156317472458"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2333156317472458
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.2333156317472458
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 1.2333156317472458
{3594_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2364568710327148"
{3594_start} <-> {3594_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 1.2364568710327148"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml