
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{30032_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.016695251688361168"
{30042_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.016695251688361168
{30017_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21318629384040833"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21318629384040833
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21318629384040833
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21318629384040833
{30002_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22009530663490295"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22009530663490295
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22009530663490295
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22009530663490295
{30033_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.22872099839150906"
{30042_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.30635582469403744"
{30042_start} <-> {30042_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml