
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{11402_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.03356568142771721"
{11410_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.03356568142771721
{11372_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21015053987503052"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21015053987503052
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21015053987503052
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21015053987503052
{11387_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22190849483013153"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22190849483013153
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22190849483013153
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22190849483013153
{11373_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38294312357902527"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.38294312357902527
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38294312357902527
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38294312357902527
{11388_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.402474045753479"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.402474045753479
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.402474045753479
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.402474045753479
{11410_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.49345598742365837"
{11410_start} <-> {11410_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml