
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22061_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19770272076129913"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19770272076129913
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19770272076129913
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19770272076129913
{22047_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2124638855457306"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2124638855457306
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2124638855457306
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2124638855457306
{22077_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.27361464500427246"
{22094_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.27361464500427246
{22078_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.29070036858320236"
{22062_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39698638021945953"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39698638021945953
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39698638021945953
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39698638021945953
{22048_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4375748038291931"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4375748038291931
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4375748038291931
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4375748038291931
{22079_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5069142058491707"
{22063_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6002730429172516"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6002730429172516
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6002730429172516
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6002730429172516
{22049_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6318112760782242"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6318112760782242
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6318112760782242
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6318112760782242
{22080_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6905907616019249"
{22064_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7896844297647476"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7896844297647476
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7896844297647476
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7896844297647476
{22050_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8054542541503906"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8054542541503906
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8054542541503906
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8054542541503906
{22081_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.8062122762203217"
{22094_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8317346572875977"
{22094_start} <-> {22094_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml