
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{22572_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.19073036313056946"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19073036313056946
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19073036313056946
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.19073036313056946
{22557_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19613121449947357"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.19613121449947357
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19613121449947357
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19613121449947357
{22558_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3784386217594147"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.3784386217594147
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3784386217594147
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3784386217594147
{22573_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40655623376369476"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.40655623376369476
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40655623376369476
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.40655623376369476
{22587_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.41019579768180847"
{22596_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.41019579768180847
{22559_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5922826826572418"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5922826826572418
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5922826826572418
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5922826826572418
{22574_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6049970090389252"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6049970090389252
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6049970090389252
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6049970090389252
{22588_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7254498898983002"
{22575_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8021462708711624"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8021462708711624
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8021462708711624
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8021462708711624
{22560_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8039515614509583"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.8039515614509583
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8039515614509583
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8039515614509583
{22596_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.8779402077198029"
{22596_start} <-> {22596_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml