
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4815_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20150646567344666"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.20150646567344666
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20150646567344666
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20150646567344666
{4799_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21130940318107605"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21130940318107605
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21130940318107605
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21130940318107605
{4831_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.24720792472362518"
{4837_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.24720792472362518
{4816_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37347419559955597"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.37347419559955597
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37347419559955597
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37347419559955597
{4800_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4102386385202408"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4102386385202408
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4102386385202408
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4102386385202408
{4801_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5557850301265717"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5557850301265717
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5557850301265717
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5557850301265717
{4817_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5835123062133789"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5835123062133789
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5835123062133789
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5835123062133789
{4832_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6836110502481461"
{4802_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7710093855857849"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7710093855857849
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7710093855857849
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7710093855857849
{4837_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7811102122068405"
{4837_start} <-> {4837_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml