
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41605_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.19356779754161835"
{41614_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.19356779754161835
{41589_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.22330988943576813"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.22330988943576813
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22330988943576813
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.22330988943576813
{41574_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.24753880500793457"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.24753880500793457
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24753880500793457
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.24753880500793457
{41606_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3457908630371094"
{41607_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3602270744740963"
{41590_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42581476271152496"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.42581476271152496
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.42581476271152496
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.42581476271152496
{41575_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.47240324318408966"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.47240324318408966
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.47240324318408966
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.47240324318408966
{41591_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6499609500169754"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6499609500169754
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6499609500169754
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6499609500169754
{41576_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6501480340957642"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6501480340957642
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6501480340957642
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.6501480340957642
{41614_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6671320647001266"
{41614_start} <-> {41614_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml