
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{17054_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19466711580753326"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19466711580753326
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19466711580753326
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19466711580753326
{17070_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1972641497850418"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1972641497850418
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1972641497850418
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1972641497850418
{17085_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.23857788741588593"
{17094_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.23857788741588593
{17086_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2643441129475832"
{17055_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.3927157521247864"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3927157521247864
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3927157521247864
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.3927157521247864
{17071_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4174179285764694"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4174179285764694
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4174179285764694
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4174179285764694
{17094_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5651784390211105"
{17094_start} <-> {17094_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml