
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14632_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19818958640098572"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.19818958640098572
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19818958640098572
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19818958640098572
{14647_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2018185704946518"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2018185704946518
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2018185704946518
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2018185704946518
{14633_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4192911237478256"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4192911237478256
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4192911237478256
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.4192911237478256
{14648_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4384535253047943"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4384535253047943
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4384535253047943
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4384535253047943
{14634_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6255857348442078"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6255857348442078
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6255857348442078
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6255857348442078
{14649_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6931190490722656"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6931190490722656
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6931190490722656
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6931190490722656
{14635_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8330394327640533"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8330394327640533
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8330394327640533
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8330394327640533
{14650_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8738809674978256"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8738809674978256
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8738809674978256
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8738809674978256
{14662_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9550349116325378"
{14674_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9550349116325378
{14651_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0275858789682388"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0275858789682388
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0275858789682388
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0275858789682388
{14663_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.0703791975975037"
{14636_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0710794776678085"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0710794776678085
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0710794776678085
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0710794776678085
{14664_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.2254655063152313"
{14652_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2453638166189194"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2453638166189194
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2453638166189194
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2453638166189194
{14637_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.261505350470543"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.261505350470543
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.261505350470543
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.261505350470543
{14665_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.3007552102208138"
{14666_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.369100958108902"
{14667_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.371532775927335"
{14668_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4056594599969685"
{14653_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4489295929670334"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.4489295929670334
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4489295929670334
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4489295929670334
{14638_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4723468273878098"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4723468273878098
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4723468273878098
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4723468273878098
{14674_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.4762176275253296"
{14674_start} <-> {14674_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml