
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{41279_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.028787827119231224"
{41287_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.028787827119231224
{41263_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17903177440166473"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.17903177440166473
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17903177440166473
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17903177440166473
{41247_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21014641225337982"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.21014641225337982
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21014641225337982
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21014641225337982
{41264_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38862766325473785"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38862766325473785
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38862766325473785
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38862766325473785
{41248_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40089456737041473"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40089456737041473
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40089456737041473
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40089456737041473
{41249_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5577518492937088"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5577518492937088
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5577518492937088
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5577518492937088
{41265_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5947049260139465"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5947049260139465
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5947049260139465
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.5947049260139465
{41287_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6504291649907827"
{41287_start} <-> {41287_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml