
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{30611_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.18452653288841248"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.18452653288841248
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18452653288841248
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.18452653288841248
{30596_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20005890727043152"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20005890727043152
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20005890727043152
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20005890727043152
{30626_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.28395310044288635"
{30637_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.28395310044288635
{30612_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.36611507833004"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.36611507833004
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36611507833004
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.36611507833004
{30597_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4060860276222229"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4060860276222229
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4060860276222229
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4060860276222229
{30613_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5400319248437881"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5400319248437881
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5400319248437881
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5400319248437881
{30598_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5826661288738251"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5826661288738251
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5826661288738251
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5826661288738251
{30614_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7282489240169525"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7282489240169525
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7282489240169525
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7282489240169525
{30599_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7891485393047333"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7891485393047333
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7891485393047333
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7891485393047333
{30637_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.793167918920517"
{30637_start} <-> {30637_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml