
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{12145_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21425379812717438"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21425379812717438
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21425379812717438
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21425379812717438
{12161_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21805071830749512"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21805071830749512
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21805071830749512
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21805071830749512
{12162_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.38021403551101685"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.38021403551101685
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38021403551101685
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.38021403551101685
{12146_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4213077574968338"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4213077574968338
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4213077574968338
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4213077574968338
{12176_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49691084027290344"
{12183_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.49691084027290344
{12177_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.49863728147465736"
{12147_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5773105025291443"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5773105025291443
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5773105025291443
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5773105025291443
{12163_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6062386929988861"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6062386929988861
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6062386929988861
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6062386929988861
{12164_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7784090042114258"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7784090042114258
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7784090042114258
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.7784090042114258
{12148_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7791550159454346"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7791550159454346
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7791550159454346
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7791550159454346
{12178_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7989356146426871"
{12165_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9500606805086136"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9500606805086136
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9500606805086136
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9500606805086136
{12183_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.95362389087677"
{12183_start} <-> {12183_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml