
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{19202_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.006563812028616667"
{19216_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.006563812028616667
{19171_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19305671751499176"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.19305671751499176
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19305671751499176
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19305671751499176
{19187_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2187725007534027"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.2187725007534027
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2187725007534027
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2187725007534027
{19172_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.38586588203907013"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.38586588203907013
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38586588203907013
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.38586588203907013
{19188_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.40306995809078217"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.40306995809078217
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40306995809078217
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.40306995809078217
{19216_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.45788952661678195"
{19216_start} <-> {19216_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml