
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{14572_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.0725807249546051"
{14586_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.0725807249546051
{14573_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.20190411806106567"
{14542_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20576772093772888"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20576772093772888
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20576772093772888
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20576772093772888
{14557_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.244368314743042"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.244368314743042
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.244368314743042
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.244368314743042
{14543_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36843402683734894"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.36843402683734894
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36843402683734894
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36843402683734894
{14574_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3843952566385269"
{14558_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.46477995812892914"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.46477995812892914
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.46477995812892914
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.46477995812892914
{14544_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5860048979520798"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5860048979520798
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5860048979520798
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5860048979520798
{14575_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5997948795557022"
{14559_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6837120950222015"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6837120950222015
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6837120950222015
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.6837120950222015
{14586_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.7578059732913971"
{14586_start} <-> {14586_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml