
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4194_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21511176228523254"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.21511176228523254
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21511176228523254
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21511176228523254
{4179_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23138093948364258"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.23138093948364258
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23138093948364258
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23138093948364258
{4195_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.42147980630397797"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.42147980630397797
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42147980630397797
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.42147980630397797
{4180_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4371943771839142"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4371943771839142
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4371943771839142
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4371943771839142
{4196_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5930169075727463"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.5930169075727463
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5930169075727463
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5930169075727463
{4181_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6731052845716476"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6731052845716476
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6731052845716476
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6731052845716476
{4210_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7430879473686218"
{4219_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.7430879473686218
{4197_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7833239883184433"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7833239883184433
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7833239883184433
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7833239883184433
{4182_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8745109587907791"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8745109587907791
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8745109587907791
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8745109587907791
{4198_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9678940623998642"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9678940623998642
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9678940623998642
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9678940623998642
{4183_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0764703154563904"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0764703154563904
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0764703154563904
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0764703154563904
{4211_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1277784407138824"
{4199_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1748271584510803"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.1748271584510803
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1748271584510803
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1748271584510803
{4219_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2631353735923767"
{4219_start} <-> {4219_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml