
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{38488_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2005598396062851"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2005598396062851
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.2005598396062851
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.2005598396062851
{38504_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2125665247440338"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.2125665247440338
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2125665247440338
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2125665247440338
{38489_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4207526743412018"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4207526743412018
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4207526743412018
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4207526743412018
{38505_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4268893897533417"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4268893897533417
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4268893897533417
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4268893897533417
{38490_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6013786196708679"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6013786196708679
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6013786196708679
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6013786196708679
{38506_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6254797875881195"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6254797875881195
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6254797875881195
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6254797875881195
{38491_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8209139406681061"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8209139406681061
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8209139406681061
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8209139406681061
{38507_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8226321339607239"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8226321339607239
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8226321339607239
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.8226321339607239
{38519_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9154413342475891"
{38525_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.9154413342475891
{38520_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.9265689505264163"
{38492_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0049899518489838"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0049899518489838
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0049899518489838
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0049899518489838
{38508_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0106004029512405"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.0106004029512405
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0106004029512405
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0106004029512405
{38493_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2138662040233612"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2138662040233612
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.2138662040233612
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 1.2138662040233612
{38509_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.2485915273427963"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2485915273427963
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2485915273427963
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.2485915273427963
{38494_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4140025228261948"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4140025228261948
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4140025228261948
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4140025228261948
{38510_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4506018310785294"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.4506018310785294
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4506018310785294
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4506018310785294
{38521_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4585391534492373"
{38522_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.5253769410774112"
{38525_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.5519774556159973"
{38525_start} <-> {38525_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml