
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{40755_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21691642701625824"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21691642701625824
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21691642701625824
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21691642701625824
{40739_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2298872470855713"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2298872470855713
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2298872470855713
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2298872470855713
{40756_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.394222155213356"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.394222155213356
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.394222155213356
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.394222155213356
{40740_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.43181179463863373"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.43181179463863373
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43181179463863373
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.43181179463863373
{40757_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5850442349910736"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.5850442349910736
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5850442349910736
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5850442349910736
{40741_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6251257807016373"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.6251257807016373
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6251257807016373
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6251257807016373
{40742_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7895333468914032"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.7895333468914032
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7895333468914032
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7895333468914032
{40758_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.791103333234787"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.791103333234787
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.791103333234787
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.791103333234787
{40743_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9836698919534683"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.9836698919534683
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9836698919534683
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9836698919534683
{40759_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.9933759272098541"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9933759272098541
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9933759272098541
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.9933759272098541
{40770_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.1297132968902588"
{40778_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.1297132968902588
{40760_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.196899563074112"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.196899563074112
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.196899563074112
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.196899563074112
{40744_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2056120336055756"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.2056120336055756
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2056120336055756
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2056120336055756
{40771_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.343144953250885"
{40772_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.3742027636617422"
{40745_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.3860703855752945"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.3860703855752945
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3860703855752945
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.3860703855752945
{40761_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4198225736618042"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.4198225736618042
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4198225736618042
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4198225736618042
{40773_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4795646350830793"
{40746_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.571046769618988"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.571046769618988
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.571046769618988
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.571046769618988
{40762_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.6531842648983002"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.6531842648983002
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6531842648983002
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.6531842648983002
{40747_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.7365291118621826"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.7365291118621826
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7365291118621826
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7365291118621826
{40778_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.771557867527008"
{40778_start} <-> {40778_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml