
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34247_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.20839889347553253"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.20839889347553253
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20839889347553253
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.20839889347553253
{34263_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21440516412258148"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21440516412258148
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21440516412258148
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21440516412258148
{34248_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.40962928533554077"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.40962928533554077
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40962928533554077
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.40962928533554077
{34264_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4400375187397003"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4400375187397003
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4400375187397003
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4400375187397003
{34249_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6114856451749802"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6114856451749802
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6114856451749802
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6114856451749802
{34265_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6368315368890762"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6368315368890762
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6368315368890762
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6368315368890762
{34250_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8079701662063599"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.8079701662063599
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8079701662063599
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8079701662063599
{34266_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8556832373142242"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.8556832373142242
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8556832373142242
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8556832373142242
{34251_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9985400140285492"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.9985400140285492
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9985400140285492
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.9985400140285492
{34267_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.0695692896842957"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.0695692896842957
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0695692896842957
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.0695692896842957
{34252_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.1834336817264557"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.1834336817264557
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1834336817264557
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.1834336817264557
{34268_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.30754716694355"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 1.30754716694355
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.30754716694355
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.30754716694355
{34253_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.4019266366958618"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 1.4019266366958618
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4019266366958618
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.4019266366958618
{34278_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.4140647649765015"
{34286_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 1.4140647649765015
{34269_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.4898342937231064"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.4898342937231064
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4898342937231064
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.4898342937231064
{34254_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.598130777478218"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.598130777478218
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.598130777478218
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.598130777478218
{34270_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.7048388123512268"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.7048388123512268
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.7048388123512268
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.7048388123512268
{34255_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.7745112925767899"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.7745112925767899
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7745112925767899
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.7745112925767899
{34279_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 1.8171156346797943"
{34286_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.8440033793449402"
{34286_start} <-> {34286_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml