
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{33839_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.1710476130247116"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.1710476130247116
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1710476130247116
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.1710476130247116
{33855_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.18562822043895721"
{33866_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.18562822043895721
{33823_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.22083406150341034"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.22083406150341034
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22083406150341034
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.22083406150341034
{33840_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.3812641352415085"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.3812641352415085
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3812641352415085
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.3812641352415085
{33824_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4101594388484955"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4101594388484955
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4101594388484955
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4101594388484955
{33856_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.48294247686862946"
{33841_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.5607001036405563"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5607001036405563
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5607001036405563
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.5607001036405563
{33857_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5843556076288223"
{33825_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5950977802276611"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5950977802276611
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5950977802276611
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5950977802276611
{33866_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.6092887669801712"
{33866_start} <-> {33866_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml