
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{6761_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.07436903566122055"
{6771_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.07436903566122055
{6762_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.2013908252120018"
{6729_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2021992951631546"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2021992951631546
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2021992951631546
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2021992951631546
{6745_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2022683173418045"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2022683173418045
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2022683173418045
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2022683173418045
{6746_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.39179839193820953"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39179839193820953
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39179839193820953
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.39179839193820953
{6730_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4059998244047165"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4059998244047165
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4059998244047165
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4059998244047165
{6771_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5037939175963402"
{6771_start} <-> {6771_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.5037939175963402"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml