
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{27276_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.08898908644914627"
{27288_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.08898908644914627
{27261_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21220676600933075"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.21220676600933075
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21220676600933075
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.21220676600933075
{27245_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.23674552142620087"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.23674552142620087
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23674552142620087
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.23674552142620087
{27277_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3527730777859688"
{27246_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4079006165266037"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4079006165266037
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4079006165266037
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4079006165266037
{27262_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4207889884710312"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4207889884710312
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4207889884710312
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4207889884710312
{27288_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5798915401101112"
{27288_start} <-> {27288_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml