
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{4491_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.21958549320697784"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21958549320697784
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21958549320697784
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.21958549320697784
{4476_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.2334137111902237"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.2334137111902237
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2334137111902237
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.2334137111902237
{4492_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4267093986272812"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.4267093986272812
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4267093986272812
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4267093986272812
{4477_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4525650888681412"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.4525650888681412
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4525650888681412
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4525650888681412
{4493_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6266187578439713"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6266187578439713
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6266187578439713
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6266187578439713
{4478_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6696126610040665"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.6696126610040665
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6696126610040665
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6696126610040665
{4507_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.6834416389465332"
{4512_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.6834416389465332
{4508_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.7327069491147995"
{4494_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.8058639913797379"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8058639913797379
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8058639913797379
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.8058639913797379
{4479_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.8601947128772736"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.8601947128772736
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8601947128772736
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.8601947128772736
{4495_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.979113832116127"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.979113832116127
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.979113832116127
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.979113832116127
{4480_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.0101630091667175"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 1.0101630091667175
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0101630091667175
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.0101630091667175
{4496_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 1.1857513040304184"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.1857513040304184
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1857513040304184
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 1.1857513040304184
{4481_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 1.2166862785816193"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 1.2166862785816193
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2166862785816193
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 1.2166862785816193
{4512_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.2467713952064514"
{4512_start} <-> {4512_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml