
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{34903_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.15385790169239044"
{34917_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.15385790169239044
{34873_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.195159450173378"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.195159450173378
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.195159450173378
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.195159450173378
{34888_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.205922931432724"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.205922931432724
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.205922931432724
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.205922931432724
{34904_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3938426673412323"
{34874_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4060724526643753"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4060724526643753
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4060724526643753
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4060724526643753
{34889_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.41342009603977203"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.41342009603977203
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41342009603977203
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.41342009603977203
{34905_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.42912552133202553"
{34890_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6239686757326126"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6239686757326126
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6239686757326126
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6239686757326126
{34875_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6263567358255386"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.6263567358255386
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6263567358255386
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6263567358255386
{34917_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.664810910820961"
{34917_start} <-> {34917_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml