
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{47_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.21530605852603912"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.21530605852603912
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21530605852603912
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.21530605852603912
{63_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.23274587094783783"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.23274587094783783
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23274587094783783
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.23274587094783783
{78_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.3855191767215729"
{85_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.3855191767215729
{64_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4151242673397064"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4151242673397064
detmodel -> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4151242673397064
detmodel <-> stochmodel : System.Camera2.networkLoss :: LostImages+.NewData at 0.4151242673397064
{48_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4206336736679077"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4206336736679077
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4206336736679077
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4206336736679077
{49_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.6052898317575455"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6052898317575455
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6052898317575455
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.6052898317575455
{65_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.6161243915557861"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.6161243915557861
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6161243915557861
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.6161243915557861
{85_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.721864253282547"
{85_start} <-> {85_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.721864253282547"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml