
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{29463_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.13870303332805634"
{29472_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.13870303332805634
{29431_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.19004042446613312"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.19004042446613312
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19004042446613312
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.19004042446613312
{29447_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.20637956261634827"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.20637956261634827
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20637956261634827
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.20637956261634827
{29432_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.4121929258108139"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4121929258108139
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4121929258108139
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.4121929258108139
{29448_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4132174849510193"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.4132174849510193
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4132174849510193
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4132174849510193
{29472_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.4353962391614914"
{29472_start} <-> {29472_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml