
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{9094_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.1484907865524292"
{9105_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.1484907865524292
{9078_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17244769632816315"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.17244769632816315
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17244769632816315
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17244769632816315
{9095_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17913408391177654"
{9062_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18710777163505554"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.18710777163505554
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18710777163505554
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18710777163505554
{9096_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.34901746921241283"
{9079_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37873947620391846"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.37873947620391846
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37873947620391846
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37873947620391846
{9105_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.3863884210586548"
{9105_start} <-> {9105_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml