
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{20329_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.17810669541358948"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.17810669541358948
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17810669541358948
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.17810669541358948
{20313_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.1886696219444275"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.1886696219444275
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1886696219444275
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.1886696219444275
{20314_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.36260974407196045"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, False]) at 0.36260974407196045
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36260974407196045
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.36260974407196045
{20330_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.37014666199684143"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, False]) at 0.37014666199684143
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37014666199684143
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.37014666199684143
{20345_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.5093022584915161"
{20352_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.5093022584915161
{20315_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5365524291992188"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.5365524291992188
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5365524291992188
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5365524291992188
{20331_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.571929395198822"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.571929395198822
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.571929395198822
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.571929395198822
{20346_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.581776537001133"
{20316_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.7586183100938797"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.7586183100938797
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7586183100938797
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.7586183100938797
{20332_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.7754515409469604"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.7754515409469604
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7754515409469604
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.7754515409469604
{20317_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.9270491451025009"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.9270491451025009
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9270491451025009
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.9270491451025009
{20333_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.955382764339447"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([0.0, True]) at 0.955382764339447
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.955382764339447
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.955382764339447
{20352_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 1.003561407327652"
{20352_start} <-> {20352_stop} : delay
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml