
	@startuml
	participant "Stochastic Models" as stochmodel
	participant "Deteministic Models" as detmodel
	participant "Analysis Case" as analysis
	{13071_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17477911710739136"
{13076_start} detmodel -> stochmodel : System.Traffic.carDelay :: CarOut.NewEvent at 0.17477911710739136
{13072_stop} stochmodel -> detmodel : "System.Traffic.carArrival  ::  Cars.NewEvent at 0.17904560593888164"
{13041_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.18592600524425507"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.18592600524425507
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18592600524425507
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.18592600524425507
{13056_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.2129458487033844"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.2129458487033844
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2129458487033844
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.2129458487033844
{13042_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.39605166018009186"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.39605166018009186
detmodel -> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39605166018009186
detmodel <-> stochmodel : System.Camera1.networkLoss :: LostImages+.NewData at 0.39605166018009186
{13057_stop} stochmodel -> detmodel : "System.Camera2.softwareTimer  ::  Events.NewEvent at 0.4337293356657028"
detmodel <-> stochmodel : System.Camera2.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.4337293356657028
detmodel -> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4337293356657028
detmodel <-> stochmodel : System.Camera2.networkLoss :: ImageOut+.NewData at 0.4337293356657028
{13043_stop} stochmodel -> detmodel : "System.Camera1.softwareTimer  ::  Events.NewEvent at 0.5737990736961365"
detmodel <-> stochmodel : System.Camera1.Software.CameraSoftware.imageBlur :: ImageOut+.NewData([1.0, True]) at 0.5737990736961365
detmodel -> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5737990736961365
detmodel <-> stochmodel : System.Camera1.networkLoss :: ImageOut+.NewData at 0.5737990736961365
{13076_stop} stochmodel -> detmodel : "System.Traffic.carDelay  ::  CarOut.NewEvent at 0.5929163694381714"
{13076_start} <-> {13076_stop} : delay
detmodel -> analysis : "Failures.newEvent at time 0.5929163694381714"
hnote over analysis 
EndConditionSystem_CarLeave_NewEvent is reached
endnote
@enduml