/*
 * generated by Xtext 2.23.0.M1
 */
package hu.bme.mit.gamma.fmeda.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.gamma.fmeda.language.FMEDALanguageRuntimeModule;
import hu.bme.mit.gamma.fmeda.language.FMEDALanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FMEDALanguageIdeSetup extends FMEDALanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FMEDALanguageRuntimeModule(), new FMEDALanguageIdeModule()));
	}
	
}
