ServiceAvailability__System : 
    dummy : "dummy"
    $Camera1_OutputData_Blurred$ : "Camera1::OutputData::Blurred"
    $Camera1_OutputData_Car$ : "Camera1::OutputData::Car"
    $Camera2_OutputData_Blurred$ : "Camera2::OutputData::Blurred"
    $Camera2_OutputData_Car$ : "Camera2::OutputData::Car"
ServiceAvailability__System__Camera1 : 
    dummy : "dummy"
    $OutputData_Blurred$ : "OutputData::Blurred"
    $OutputData_Car$ : "OutputData::Car"
    $Software_Images_Blurred$ : "Software::Images::Blurred"
    $Software_Images_Car$ : "Software::Images::Car"
    $NetworkQueue_ImageOut_Blurred$ : "NetworkQueue::ImageOut::Blurred"
    $NetworkQueue_ImageOut_Car$ : "NetworkQueue::ImageOut::Car"
ServiceAvailability__System__Camera1__Software : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
ServiceAvailability__System__Camera1__Software__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__Camera1__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__Camera1__NetworkQueue : 
    dummy : "dummy"
    $ImageOut_Blurred$ : "ImageOut::Blurred"
    $ImageOut_Car$ : "ImageOut::Car"
ServiceAvailability__System__Software : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
ServiceAvailability__System__Software__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__NetworkQueue : 
    dummy : "dummy"
    $ImageOut_Blurred$ : "ImageOut::Blurred"
    $ImageOut_Car$ : "ImageOut::Car"
ServiceAvailability__System__Camera2 : 
    dummy : "dummy"
    $OutputData_Blurred$ : "OutputData::Blurred"
    $OutputData_Car$ : "OutputData::Car"
    $Software_Images_Blurred$ : "Software::Images::Blurred"
    $Software_Images_Car$ : "Software::Images::Car"
    $NetworkQueue_ImageOut_Blurred$ : "NetworkQueue::ImageOut::Blurred"
    $NetworkQueue_ImageOut_Car$ : "NetworkQueue::ImageOut::Car"
ServiceAvailability__System__Camera2__Software : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
ServiceAvailability__System__Camera2__Software__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__Camera2__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__Camera2__NetworkQueue : 
    dummy : "dummy"
    $ImageOut_Blurred$ : "ImageOut::Blurred"
    $ImageOut_Car$ : "ImageOut::Car"
ServiceAvailability__System__Software : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
ServiceAvailability__System__Software__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__CameraSoftware : 
    dummy : "dummy"
    $Images_Blurred$ : "Images::Blurred"
    $Images_Car$ : "Images::Car"
    $CameraDriver_Images_Blurred$ : "CameraDriver::Images::Blurred"
    $CameraDriver_Images_Car$ : "CameraDriver::Images::Car"
    cameraDriver_SCT : "__STATECHART__CameraDriver"
    $CameraControl_NetworkImages_Blurred$ : "CameraControl::NetworkImages::Blurred"
    $CameraControl_NetworkImages_Car$ : "CameraControl::NetworkImages::Car"
    cameraControl_SCT : "__STATECHART__CameraControl"
ServiceAvailability__System__NetworkQueue : 
    dummy : "dummy"
    $ImageOut_Blurred$ : "ImageOut::Blurred"
    $ImageOut_Car$ : "ImageOut::Car"
ServiceAvailability__System__Edge : 
    dummy : "dummy"
ServiceAvailability__System__Traffic : 
    dummy : "dummy"
ServiceAvailability__System__Traffic__TrafficSct : 
    dummy : "dummy"
ServiceAvailability__System__TrafficSct : 
    dummy : "dummy"

