<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="analysis" nsURI="www.mit.bme.hu/analysis/Model" nsPrefix="hu.bme.mit.gamma.environment.analysis">
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisComponent" eSuperTypes="../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedComponent" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentAsynchronousCompositeComponentInstance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//AnalysisCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspect" lowerBound="1"
        upperBound="-1" eType="#//AnalysisAspect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priorydistribution" upperBound="-1"
        eType="#//PrioryDistribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysismethod" lowerBound="1"
        eType="#//AnalysisMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisCondition" abstract="true" eSuperTypes="#//AnalysisAspect"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssumeRaised" eSuperTypes="#//AssumeCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssumeNotRaised" eSuperTypes="#//AssumeCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisAspect" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//ComponentPortEventReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Probability" eSuperTypes="#//AnalysisAspect"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimedProbability" eSuperTypes="#//AnalysisAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeanTime" eSuperTypes="#//AnalysisAspect"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeBoundedProbability" eSuperTypes="#//AnalysisAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementComponent" eSuperTypes="#//AnalysisComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" upperBound="-1"
        eType="#//RequirementAspect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementAspect" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowerThan" eSuperTypes="#//RequirementAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterThan" eSuperTypes="#//RequirementAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsBetween" eSuperTypes="#//RequirementAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPortEventReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//RecursiveComponentReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frequency" eSuperTypes="#//AnalysisAspect"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeanParameter" eSuperTypes="#//AnalysisAspect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParameterDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDistribution" eSuperTypes="#//AnalysisAspect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParameterDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecursiveComponentReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.model/model/environment.ecore#//EnvironmentAsynchronousCompositeComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recursivecomponentreference"
        eType="#//RecursiveComponentReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeanTimeBetweenEvents" eSuperTypes="#//AnalysisAspect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event2" lowerBound="1"
        eType="#//ComponentPortEventReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTimeRatio" eSuperTypes="#//AnalysisAspect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event2" lowerBound="1"
        eType="#//ComponentPortEventReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObserveParameter" eSuperTypes="#//ObserveCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParameterDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrioryDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="randomvariable" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.stochastic.model/model/stochastic.ecore#//RandomVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParameterDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObserveCondition" abstract="true" eSuperTypes="#//AnalysisCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="randomvariable" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.environment.stochastic.model/model/stochastic.ecore#//StochasticModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssumeCondition" abstract="true" eSuperTypes="#//AnalysisCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//DecimalLiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObserveTime" eSuperTypes="#//ObserveCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndCondition" eSuperTypes="#//AnalysisCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisMethod" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExactAnalysisMethod" abstract="true"
      eSuperTypes="#//AnalysisMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationAnalysisMethod" abstract="true"
      eSuperTypes="#//AnalysisMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endcondition" upperBound="-1"
        eType="#//EndCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationNumber" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//IntegerLiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="warmupTime" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationTime" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="samplingBatchSize" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//IntegerLiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jointSampling" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debug" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportanceSampling" eSuperTypes="#//SimulationAnalysisMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="MCMC" eSuperTypes="#//SimulationAnalysisMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kernel" lowerBound="1"
        eType="#//MCMCKernel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="warmupStepNum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//IntegerLiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SVI" eSuperTypes="#//SimulationAnalysisMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="MCMCKernel" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NUTS" eSuperTypes="#//MCMCKernel"/>
  <eClassifiers xsi:type="ecore:EClass" name="HMC" eSuperTypes="#//MCMCKernel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Simulation" eSuperTypes="#//SimulationAnalysisMethod"/>
</ecore:EPackage>
