Status_SM : ["main"]
Orion_Master_SM_ext : ["main_region_of_Orion_Master_SM", "region_1_in_Kapcsolodva_4", "region_2_in_Kapcsolodva_4"]
Orion_Slave_SM_ext : ["main_region_of_Orion_Slave_SM", "region_1_in_Kapcsolodva_1", "region_2_in_Kapcsolodva_1"]
