Orion_Performance__Orion : 
    dummy : "dummy"
Orion_Performance__Orion__OrionSystem : 
    dummy : "dummy"
    connStatus_SCT : "__STATECHART__ConnStatus"
Orion_Performance__Orion__OrionSystem__Master : 
    dummy : "dummy"
Orion_Performance__Orion__OrionSystem__Slave : 
    dummy : "dummy"
Orion_Performance__Orion__Master : 
    dummy : "dummy"
Orion_Performance__Orion__Slave : 
    dummy : "dummy"

