<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="www.mit.bme.hu/gamma/architecture/Model" nsPrefix="hu.bme.mit.gamma.architecture">
  <eClassifiers xsi:type="ecore:EClass" name="ArchitecturePackage" eSuperTypes="#//ArchitectureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="architectureelement" upperBound="-1"
        eType="#//ArchitectureElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpackeges" upperBound="-1"
        eType="#//ArchitecturePackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureElement" abstract="true"
      eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureComponent" abstract="true"
      eSuperTypes="#//PhysicalElement #//FunctionalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitecturePort" eSuperTypes="#//ArchitectureElementInstance #//ArchitectureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ArchitectureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conjugated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFunction" eSuperTypes="#//FunctionalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureElementInstance" abstract="true"
      eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureInterface" eSuperTypes="#//ArchitectureElement ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowproperties" upperBound="-1"
        eType="#//FlowProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareComponent" eSuperTypes="#//ArchitectureComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElectronicComponent" eSuperTypes="#//ArchitectureComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="MechanicalComponent" eSuperTypes="#//ArchitectureComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureSubcompnent" eSuperTypes="#//ArchitectureElementInstance #//PhysicalElement #//FunctionalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ArchitectureComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureSubfunction" eSuperTypes="#//ArchitectureElementInstance #//FunctionalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ArchitectureFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeInterface" eSuperTypes="#//ArchitectureInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subinterfaces" eType="#//ArchitectureInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//ArchitectureComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElectricalInterface" eSuperTypes="#//ElectronicComponent #//ArchitectureInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="MechanicalInterface" eSuperTypes="#//MechanicalComponent #//ArchitectureInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalInterface" eSuperTypes="#//ArchitectureInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareInterface" eSuperTypes="#//SoftwareComponent #//ArchitectureInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureRelations" abstract="true"
      eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement #//ArchitectureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ArchitectureElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ArchitectureElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation" abstract="true" eSuperTypes="#//ArchitectureRelations"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareAllocation" eSuperTypes="#//Allocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElectricalAllocation" eSuperTypes="#//Allocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalAllocation" eSuperTypes="#//Allocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//ArchitectureRelations"/>
  <eClassifiers xsi:type="ecore:EClass" name="InforationFlow" eSuperTypes="#//ArchitectureRelations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ArchitectureInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalElement" abstract="true" eSuperTypes="#//StructuralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subcompnents" upperBound="-1"
        eType="#//ArchitectureSubcompnent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalElement" abstract="true" eSuperTypes="#//StructuralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subfunctions" upperBound="-1"
        eType="#//ArchitectureSubfunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceConnector" eSuperTypes="#//Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ArchitectureInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveFunction" eSuperTypes="#//ArchitectureFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralElement" abstract="true" eSuperTypes="#//ArchitectureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//ArchitecturePort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//ArchitectureRelations" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalisation" eSuperTypes="#//ArchitectureRelations"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//ArchitectureRelations"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowProperty" eSuperTypes="#//ArchitectureElementInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//Direction" defaultValueLiteral="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
    <eLiterals name="INOUT" value="2"/>
    <eLiterals name="NONE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueType" eSuperTypes="#//ArchitectureElement"/>
</ecore:EPackage>
