name: mkdocs

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
        working-directory: .
      - run: mkdocs build --site-dir wiki
        working-directory: .
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        id: deploy1
        with:
          branch: gh-pages
          folder: wiki
          target_folder: docs
          single_commit: true
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        if: steps.deploy1.conclusion == 'failure'
        with:
          branch: gh-pages
          folder: wiki
          target_folder: docs
          single_commit: true